### ISSUE TITLE
Resource specific interceptor?

### ISSUE THREAD

**Issue by Narayane** [square/retrofit#1005]
Hi,

first of all, thanks for retrofit, it avoids me a lot of trouble :)

    @FormUrlEncoded
    @POST("/o/token/")
    TokenResponse refreshToken(@Field("refresh_token") String pRefreshToken, @Field("grant_type") String pGrantType, @Field
            ("client_id") String pClientId, @Field("client_secret") String pClientSecret);

I use it in an OAuth2 context and in some POST requests, I have to always specify same fields like grant_type, client_id, client_secret, ...
I wonder if it would be possible to create an interceptor for a particular resource and a particular HTTP action (e.g.  /o/auth and POST) which could add "base fields" (like previously quoted) and not on all requests like its "normal behavior".
In my example above, I would like to remove grant_type, client_id and client_secret from my request.
When I look at this link http://square.github.io/retrofit/javadoc/retrofit/RequestInterceptor.RequestFacade.html, it seems not possible to add some fields in a POST request.

Resource specific interceptor is it currently possible?
If not, is there any workaround for my need?
If not, any suggestion?

Best regards

**Comment by Avinash-Bhat** [comment]
you cannot use the `RequestInterceptor` for this.

The alternative to this is to use the OkHttp Interceptors for this. There you can check the URL before modifying the requests -- see https://github.com/square/okhttp/wiki/Interceptors

**Comment by JakeWharton** [comment]
Consider also wrapping the Retrofit interface into a high-level interface that you expose to your client code. Then your shim can add the constant values when passing data to Retrofit.

Just because Retrofit can sometimes expose a nice API that can be directly used by consumers does not make it a replacement for designing the correct abstractions. Since this deals with a form encoded bodies it doesn't make sense for this to live in something like our `RequestInterceptor` as requests might not have a body, might not be form encoded, and might already have these values. That's a lot of conditions that require checking, handling, and accounting for in your code.

You can use OkHttp interceptors as mentioned but it they are really not set up for modifying a request body in this way. I really think that you should just expose a different API to your consumers than the Retrofit interface.
