### ISSUE TITLE
There is no support for providing request type dynamically

### ISSUE THREAD

**Issue by ahmadshahzad** [square/retrofit#1007]
There is no support for providing request type on run time e.g. change the request type to PUT or POST.

**Comment by JakeWharton** [comment]
That is correct. Retrofit maps APIs which are relatively fixed. If you have only two http methods then you can define two interface methods for each. If your request is more dynamic than that, Retrofit probably isn't the right choice and you should use a normal HTTP client (like [OkHttp][1]) which will allow you to build a request using an object model rather than declaratively like Retrofit.

 [1]: https://github.com/square/okhttp

**Comment by felipecsl** [comment]
This exact feature is the reason why we opened this PR https://github.com/square/retrofit/pull/887
Let us know if this might be useful to you too!
