### ISSUE TITLE
How to build a query parameter with no value?

### ISSUE THREAD

**Issue by NeoLSN** [square/retrofit#1011]
I want to build a url like below:
```javascript
http://example.com/foo?bon=bom&bar
```
The query parameter, bar, which is a no value query parameter.
How can I build those kinds of parameter with this library?

**Comment by raniejade** [comment]
Something like:

```java
@GET("/foo?bar")
Response someMethod(@Query("bon") String bon);
```

**Comment by NeoLSN** [comment]
I want to it be controllable value.
It will show if it is true else disappear.

**Comment by caseykulm** [comment]
With the current version of Retrofit you could look at using the RequestInterceptor [addQueryParam](http://square.github.io/retrofit/javadoc/retrofit/RequestInterceptor.RequestFacade.html#addQueryParam-java.lang.String-java.lang.String-) method, but a possibly better way that would be better compatible with the Retrofit 2.0 API would be to use OkHttps interceptors instead since Retrofit RequestInterceptors seem to be going away in favor of the HttpClients per [839](https://github.com/square/retrofit/pull/839).

**Comment by alex-shpak** [comment]
Note that in Retrofit `null` values removing parameter from request but you can send an empty string
If it's okay for backend (it should) you can do `http://example.com/foo/?bon=bom&bar=`
With
```Java
GET("/foo/")
void get(@Query("bon") String bon, Query("bar") String bar, Callback<Void> cb);
```
And passing an empty string
```Java
service.get("bom", "", cb);
```

Or you can just have 2 interface methods, it a bit more complex to maintain
```Java
GET("/foo/?bar")
void get(@Query("bon") String bon, Callback<Void> cb);
GET("/foo/")
void get(@Query("bon") String bon, Query("bar") String bar, Callback<Void> cb);
```
And pass `bar` parameter if required

**Comment by NeoLSN** [comment]
@alex-shpak 
Thanks for your solution.
It is very useful.
