### ISSUE TITLE
Gson parsing freezes UI

### ISSUE THREAD

**Issue by ffelini** [square/retrofit#1067]
We just started to use some services in our project with big data results.
First thing we've noticed is that the UI freezes when response come. The api response is really big so we think it is cause of it.
We do async. retrofit calls so logically everything should be done in background.
Does deserialization works on the main thread ?

**Comment by artem-zinnatullin** [comment]
Try to debug it and see on what thread Gson do its work.

Probably, big responses cause frequent or long GCs which lead to UI freezes.

**Comment by jbaginski** [comment]
@ffelini check your callback executor.

**Comment by ffelini** [comment]
Thank you, I'l check it. Callback executor is fine, only adapter.notifyDataSetChanged() called there.
@artem-zinnatullin  I think you may be right.
But how generally this kind of issues is avoided (when GC becomes crazy cause of big responses) ?
I understand that this may be not a Retrofit related issue.

**Comment by ffelini** [comment]
Anyone tried this library with retrofit?
https://github.com/bluelinelabs/LoganSquare
Unfortunatelly not so much feedbacks about it, but looks promising.

**Comment by artem-zinnatullin** [comment]
>But how generally this kind of issues is avoided (when GC becomes crazy cause of big responses) ?

Usually, the solution is to use stream-based parsing which will parse response stream instead of loading all response to the memory and only then parsing it.

But, anyway, if you have REALLY big responses — JSON is not best format for such cases because it has a lot of duplications (imagine huge array of objects with same structure). Consider switching to more efficient formats, such as: [Apache Trift](https://thrift.apache.org), [Protocol Buffers](https://thrift.apache.org), [FlatBuffers](https://code.facebook.com/posts/872547912839369/improving-facebook-s-performance-on-android-with-flatbuffers/), etc.

**Comment by ffelini** [comment]
@artem-zinnatullin Thank you for quick feedbacks. Unfortunatelly we have only Json, no choice :) 
I'l see what I can do

**Comment by artem-zinnatullin** [comment]
@ffelini if you want to use JSON try all available parsers and choose the best one which will be fast and good enough for you, also make sure that responses are Gzipped: in combination with Stream parsing it should give good results!

Some JSON parsers/serializers: [Jackson](https://github.com/FasterXML/jackson), [Moshi](https://github.com/square/moshi), [Ig-Json-Parser](https://github.com/Instagram/ig-json-parser/), [LoganSquare](https://github.com/bluelinelabs/LoganSquare).

**Comment by ffelini** [comment]
Thank you for help :)
