### ISSUE TITLE
Usage of TypedInput in 2.0

### ISSUE THREAD

**Issue by damien5314** [square/retrofit#1079]
Hi, I'm looking for some clarification on the usage of TypedInput in Retrofit 2. Specifically, there are certain instances in my application where I am manually constructing JSON due to caveats with the endpoint I am consuming. 

In Retrofit 1.x we were able to pass this into an HTTP call with a @Body-annotated TypedString parameter.

    @PUT("/api/v1/me/friends")
    Observable<Response<ResponseBody>> addFriend(@Body TypedString json);

In the change log for 2.0.0-beta it states TypedInput has been replaced with OkHttp types RequestBody and ResponseBody. Therefore, I tried implementing my API method by changing TypedString to RequestBody, constructing and passing the RequestBody object instead (e.g. `RequestBody.create(MediaType.parse("application/json"), jsonString)`).

    @PUT("/api/v1/me/friends")
    Observable<Response<ResponseBody>> addFriend(@Body RequestBody friend);

That doesn't work, and I think it's because of my usage of GsonConverterFactory. GsonConverter attempts to convert my RequestBody object although I already constructed it myself.

Sorry if I'm jumping ahead of the available documentation, but is my understanding of the intended usage of TypedInput (RequestBody) in 2.0 correct?

**Comment by JakeWharton** [comment]
Thanks for the detailed report.

This has already been fixed on `master` and will be included in the next beta. You can depend on the 2.0.0-SNAPSHOT version from Sonatype's snapshot repo (linked in README) for an immediate fix (or build a jar yourself).

I had hoped the next beta would have been this week but it's looking more like next week since I've been busy with other things.
