### ISSUE TITLE
Support for method with return AND callback

### ISSUE THREAD

**Issue by MohMah** [square/retrofit#1146]
I need to have methods in the interface like this:

`@GET("/user/{id}/")`
`User userInfo(@Path("id") int Id, Callback<User> cb);`

I want to call `userInfo` and get the cached `User` right away and then wait for callback for the actual results from the server. I think it's a nice feature, I tried to implement it but I couldn't understand parts of the retrofit code. So is this gonna be implemented by you guys?
Or can you help me in a direction to how this could be implemented?
Thanks

**Comment by bryant1410** [comment]
I this goes beyond retrofit purpose. What I'd do is to return an Observable (of RxJava) and in other method return an observable, which first emits the cached item and then the one that comes from a service, in a second emition.

**Comment by JakeWharton** [comment]
What you describe is an application-level requirement, and would be hard to generalize so that it's useful to everyone. This is best encapsulated by two calls to Retrofit, one with a header that has `only-if-cached` for a `Cache-Control` header to check for initial value, and a second without the header for the up-to-date resource.

Retrofit tries its best to integrate into an application's infrastructure choices (serialization mechanisms, async frameworks), but it can't always encapsulate application-level choices for how you interact with the HTTP client like this.
