### ISSUE TITLE
Is possible create more of one converter?

### ISSUE THREAD

**Issue by oliveiradev** [square/retrofit#1160]
my problem is conflict in run app , Ex:
```
compile 'com.squareup.retrofit:converter-gson:2.0.0-beta2'
compile 'com.squareup.retrofit:converter-jackson:2.0.0-beta2'

```

**Comment by JakeWharton** [comment]
You can create more than one and add more than one to a single `Retrofit` instance, yes. We currently use a protobuf converter and a JSON converter.

That said, those two JSON-based converters won't both be usable in a single instance. Whichever was added first will always be the one that is used since the JSON converters have no way of telling which types they should and should not attempt to converter.

**Comment by oliveiradev** [comment]
thanks @JakeWharton !
