### ISSUE TITLE
TypedByteArray instead of TypedFile is not working.

### ISSUE THREAD

**Issue by rohanmahale** [square/retrofit#1166]
I am using a multi-part request(POST) to send 3 images to the server. My method definition is below 

    @Multipart
    @POST("/" + ENDPOINT_POST_PICTURE_SET)
    SendPictureSetResponse sendPictureSet(@Part("image_1") TypedFile photo1, 
    @Part("image_2") TypedFile photo2, @Part("image_3") TypedFile photo3,
    @Part("string1") TypedString string1, @Part("string2") TypedString string2);

I have decided to compress these jpeg images to maybe 90% quality(maybe even 70%) before I attach them.
     
    Bitmap bitmap = BitmapFactory.decodeFile(application.getImageFilePaths().get(0));
            ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream();
            bitmap.compress(Bitmap.CompressFormat.JPEG, 90, byteArrayOutputStream);

I updated the method to take in three TypedByteArrays instead using the following code. 

    @Multipart
    @POST("/" + ENDPOINT_POST_PICTURE_SET)
    SendPictureSetResponse sendPictureSet(@Part("image_1") TypedByteArray photo1, 
    @Part("image_2") TypedByteArray photo2, @Part("image_3") TypedByteArray photo3,
    @Part("string1") TypedString string1, @Part("string2") TypedString string2);

I create the bytearrays as shown below and passed it to the method .
    
    byteArrayOutputStream.toByteArray()

The server however does not recognize this format. What changes do I need to make in my request(or/and in the server) for the server to accept this request format. Do I need to add a different mime type or header or is my request in it's entirety wrong? I am only adding an authorization header(token) for now, using a request interceptor.

**Comment by JakeWharton** [comment]
> The server however does not recognize this format. What changes do I need to make in my request(or/and in the server) for the server to accept this request format. Do I need to add a different mime type or header or is my request in it's entirety wrong?

This is entirely dependent on the software running on your server. We can't know what server software you are using or the requirements of the application code written on top of it. Both `TypedFile` and `TypedByteArray` require you to supply the mime type, so assuming that is receiving the same value it likely isn't a factor.

You should consult with the person or team running your server and see what the problem is. You can also use tools like Charles Proxy to inspect the individual HTTP calls and see what differs.

With the information provided, however, there's no way for us to know what the problem is. Furthermore, it's highly unlikely to be a problem with Retrofit itself, but rather with how you are using it with this particular server's expectations.
