### ISSUE TITLE
ProGuard and Retrofit don't enjoy each other...

### ISSUE THREAD

**Issue by thorinside** [square/retrofit#117]
I think some documentation on proper proguard configuration for Retrofit would be great. Any idea what lines I would put into progaurd.cfg to avoid the following errors:

```
12-10 17:18:11.523: WARN/RestAdapter(3135): Method not annotated with GET, POST, PUT, or DELETE: public abstract void com.calgaryscientific.oncall.service.OnCallServiceAsync.deleteUser(java.lang.String,retrofit.http.Callback) from https://csi-oncall.herokuapp.com/
        java.lang.IllegalStateException: Method not annotated with GET, POST, PUT, or DELETE: public abstract void com.calgaryscientific.oncall.service.OnCallServiceAsync.deleteUser(java.lang.String,retrofit.http.Callback)
        at retrofit.http.RequestLine.fromMethod(RequestLine.java:64)
        at retrofit.http.HttpRequestBuilder.setMethod(HttpRequestBuilder.java:52)
        at retrofit.http.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:137)
        at retrofit.http.RestAdapter$RestHandler.access$400(RestAdapter.java:102)
        at retrofit.http.RestAdapter$RestHandler$1.obtainResponse(RestAdapter.java:115)
        at retrofit.http.CallbackRunnable.run(CallbackRunnable.java:30)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
        at retrofit.http.Platform$Android$2$1.run(Platform.java:93)
        at java.lang.Thread.run(Thread.java:856)
```

**Comment by ralphhm** [comment]
A more generic approach is to use
```
-keepclassmembernames interface * {
    @retrofit.http.* <methods>;
}
```
for the service interfaces so that you end up with following:
```
-keep class retrofit.** { *; }
-keep class package.with.model.classes.** { *; }
-keepclassmembernames interface * {
    @retrofit.http.* <methods>;
}
```

**Comment by daveztong** [comment]
@ralphhm Your approach is quite handy

**Comment by ened** [comment]
@JakeWharton Maybe publish it on the website http://square.github.io/retrofit/ ?

**Comment by JakeWharton** [comment]
Not a ProGuard user. Someone can send a PR for it.

**Comment by marcin-kozinski** [comment]
There are still some missing pieces not mentioned above that my team has found out the hard way. This is our take:
```
-dontwarn retrofit.**
-keep class retrofit.** { *; }
-keepattributes Signature
-keepattributes Exceptions
```

You need `-keepattributes Signature` if in your rest service interface you use methods with `Callback` argument. This argument is of generic type and Retrofit checks it at runtime. Proguard strips generic type information by default and this flag keeps it.

`-keepattributes Exceptions` is needed if your rest service methods throw custom exceptions, because you've defined an `ErrorHandler` that returns such exceptions. Again, at runtime Retrofit verifies if an exception returned by an `ErrorHandler` was declared on the interface. And again, Proguard by default strips information about exceptions declared on methods and this flag tells it to keep them.

You can find answers for specific problems on Stack Overflow once you come across them and have an exception to paste into Google. But this should help to prevent those problems for all the people who find this issue after searching Google with much more generic search term.

One other thing to note is that by default Retrofit uses GSON to convert server responses and you need some more Proguard configuration for GSON. But that is covered well on Stack Overflow and [by the GSON team](http://google-gson.googlecode.com/svn/trunk/examples/android-proguard-example/proguard.cfg) (though some of their configuration is not need on Android or do not apply to Android).

@JakeWharton I'd love to contribute our configuration to the Retrofit website. Is adding a new section for it between "Download" and "Contributing" all right? If not, it'd be great if you suggested an acceptable place for it.

**Comment by divyaansh** [comment]
@JakeWharton, you said you are 
> Not a ProGuard user.

Do you use something else for obfuscating code?

**Comment by jemshit** [comment]
As @ralphhm wrote, you have to keep web service Models from obfuscation, don't know why (android 6.0 does not require, android 4.1 requires):
`-keep class package.with.model.classes.** { *; }`

Also note this, if you have Modules in your project, you have to write 
 `consumerProguardFiles  'proguard-rules.pro'` and no `minifyEnabled` text in `build.gradle` file of Modules

**Comment by ascmp** [comment]
Following the suggestions here, when we use proguard with Retrofit (3.6.0) then I can see that the rest APIs paths are still kept readable. Any hint or suggestion on how to be able to make them obfuscated as well?

**Comment by JakeWharton** [comment]
You cannot
