### ISSUE TITLE
Why retrofit only supports okhttp

### ISSUE THREAD

**Issue by KingHanWen** [square/retrofit#1239]
I think, as a proxy framework, should be able to replace the http client

**Comment by KingHanWen** [comment]
I'm sorry, I just know that you are squareup company

**Comment by adriancole** [comment]
I'll give a try of explaining (as a non-employee, to the degree it matters)

Retrofit has a far simpler contract,l because it only works with
okhttp/okio transport. It offers more flexibility on the front end instead
(rx vs whatever).

By limiting transport, retrofit has no gnarly adapters for things that
aren't actually better for clients or that impede Android. Its support
story is far more clear as the answer to why something broke doesn't
require several questions about transport in use. Finally, the lead
committers to retrofit *really* know the stack underneath, and can fix it
easily.

In all projects, flexibility is not free. Usually, it is very expensive.
Sometimes, that expense isn't visible until the project grinds to a halt
years later due to technical debt buildup. Infinite flexibility on the
front end and the back end can aim the future towards this!

Retrofit presents a cleaner and more supportable api binder than before. It
presents a far more flexible front end (ex swap rxjava for a different
composition layer as you like). This story is paid for in part by limiting
transport to a *very good* choice of okhttp/okio.

Hope this helps (and is actually a correct answer)
