### ISSUE TITLE
Incoming message protocol does not match endpoint protocol.

### ISSUE THREAD

**Issue by lucas34** [square/retrofit#1275]
Hi,

I'm switching to retrofit 2.0 (Beta 2) and I'm facing a problem.
The response I get is :

<-- HTTP/1.1 500 Internal Server Error 
<faultstring>Incoming message protocol does not match endpoint protocol.</faultstring>

But If i put the same data on postman it works.

For the converter, I use SimpleXmlConverterFactory.

I have no issue with Retrofit 1.9.0

Is this error is a common error ?

Thanks for your help.

**Comment by JakeWharton** [comment]
This is a server error. While it may be a problem with your configuration of Retrofit, it's not a problem with the Retrofit library itself.

You need to consult with your server engineers or API documentation as to what is expected vs. what is actually being sent. You can use a Proxy like Charles to debug or install a [logging interceptor][1] to see what's being sent across the wire.

Without _a ton_ more information, there's no way to assist here, and even if that information was provided this isn't the right place to diagnose and address it. At best somewhere like StackOverflow is where this could be resolved since it is a usage problem and not a bug or feature request.

 [1]: https://github.com/square/okhttp/tree/master/okhttp-logging-interceptor
