### ISSUE TITLE
Unable to call the appropriate converter based on Content-Type

### ISSUE THREAD

**Issue by zawn** [square/retrofit#1384]
Unable to call the appropriate converter based on Content-Type，
eg：
@POST("...")
@Headers("Content-Type: application/json;charset=UTF-8")
Call<Result<LoginUser>> updateUserInfo(@Body UpdateUserInfoPost post);

**Comment by JakeWharton** [comment]
Converters are selected by the Java type, not the Content-Type. The Converter also specifies the `Content-Type` header automatically, so if you were using a JSON one it would be redundant to specify your own.

Please elaborate on the specific bug in Retrofit that you are seeing.

**Comment by zawn** [comment]
I understand that this is not the Issue,but i suggest add based Content-Type converter.
So implementation will close JAX-RS.This does not require cumbersome changes,Only needs Converter <T, RequestBody> declare a Method,

**Comment by JakeWharton** [comment]
I see. This is not the desired interaction pattern with Retrofit as it just ends up encoding a bunch of the same information over and over in your interfaces. Rarely do we see APIs that necessitate a wide-range of content types. Usually it's just one and occasionally two. Since we're not trying to match JAX-RS in any way, a really, really compelling argument would have to be made for supporting this behavior alongside the current behavior.
