### ISSUE TITLE
Multipart request overriding content-type not working

### ISSUE THREAD

**Issue by rahul-a** [square/retrofit#1433]
Hey! So I'm trying to send a multipart request to my backend which doesn't want the content-type to be set as 'application/json' somehow retrofit's RequestBuilder by default adds this header to all parts and it's not getting overridden I've tried to supply the header using @Headers({"Content-Type: multipart/form; charset=UTF-8"}) on the api request and also using request interceptor both the times I couldn't override it successfully. Finally I had to create my own Multipart Request body and use okHttp's call to successfully do it. But am I doing something wrong?

**Comment by bkach** [comment]
I'm having the same issue. The interceptor doesn't seem to want to stick that header in.

The only way the Content-Type sticks is if I put an @Headers({"Content-Type:... tag right above each one of my calls on the retrofit interface.

**Comment by JakeWharton** [comment]
Part values go through the converter so if you have a JSON converter the part content types will be JSON. If you are using Retrofit 1 you can use `TypedInput` and for Retrofit 2 use `RequestBody` to supply a raw part value with its own content type. Retrofit 2 also allows multiple converters so you can add a converter that supports whatever content type you like.

If you still have a problem please provide a snippet of executable code or a test case that demonstrates clearly what the problem is and what the expected output should be.

**Comment by rahul-a** [comment]
Hey thanks for the suggestion, it works when I use RequestBody, though one quick question, if my backend supports half the calls with json content-type and others as multipart I'd want to have both the converter factories in Retrofit so should I be re-indexing Converter factories. Correct me if i'm wrong but i think the first factory encountered takes precedence and writes the request.

**Comment by JakeWharton** [comment]
> Correct me if i'm wrong but i think the first factory encountered takes precedence and writes the request.

It's the first that can handle the type, not strictly the first in the list. The JSON converters [are documented][1] to handle all types:

> this converter assumes that it can handle all types

If you are using something like protocol buffers, its converter requires that the type be a subclass of `Message`, so by putting it first it would handle only the proto types and then the JSON converter would catch everything else.

If you need to use two converters that each want to handle all types then you have two options:
 1. Separate the endpoints into two interfaces and create a `Retrofit` instance for each one
 2. Define annotations for the serialization format (like `@Json` and `@Xml`) and wrap each of the converters in a `Converter.Factory` that checks the `Annotation[]` for one of those annotations.

I'm going to send a PR which adds a sample for 2.

 [1]: http://square.github.io/retrofit/2.x/converter-gson/retrofit2/GsonConverterFactory.html

**Comment by pmk2429** [comment]
I am trying to upload the image encapsulated in ```RequestBody``` on S3 using [Loopback.io](http://loopback.io/) but somehow the content-type in ```OkHttp``` header conflicts with that of ```Request``` object in the Node.
In other words, the content type is not accepted for a Multipart request

As a result, the image name does get written on the S3 using loopback in backend but image is not written to its length. Only 2 bytes are written to S3 storage and a new entry is added to bucket.

I tried to use every possible workarounds like Adding ```@Header```,  using ```@Body``` instead of ```@Part,``` decoding image to byte array etc. but it it doesn't seem to work.

Just to check my backend code [here is the gist](https://gist.github.com/pmk2429/5911951859d0217ef3c4), I tried uploading image using Postman and every thing works just fine.

Here are my OkHttp Logs

Body Log
```
--> END POST (244-byte body)
D/OkHttp: <-- HTTP/1.1 200 OK (583ms)
D/OkHttp: X-Powered-By: Express
D/OkHttp: Vary: Origin, Accept-Encoding
D/OkHttp: Access-Control-Allow-Credentials: true
D/OkHttp: Content-Type: application/json; charset=utf-8
D/OkHttp: Content-Length: 482
...
```
Header Log
```
D/OkHttp: --> END POST
D/OkHttp: <-- HTTP/1.1 200 OK (3583ms)
D/OkHttp: X-Powered-By: Express
D/OkHttp: Vary: Origin, Accept-Encoding
D/OkHttp: Access-Control-Allow-Credentials: true
D/OkHttp: Content-Type: application/json; charset=utf-8
D/OkHttp: Content-Length: 482
...
```

When I log the Request received by the server, the ```content-type``` is ```multipart/mixed``` provided with boundary. 

This conflicts with the content-type in the OkHttp header for the same request

Is there any way to fix this and get multipart/form-data along with boundary in the header?

**Comment by JakeWharton** [comment]
Can you show your interface declaration?

**Comment by yegeniy** [comment]
```java
      @POST("MyService")
      @Headers({
        // Yes... it's supposed to be a lower case type...
        // "Accept: application/soap+xml",
        "Content-Type: application/soap+xml",
        "SOAPAction: http://my.service.com/myService"
      })
      public Call<SoapResponse> foo(@Body String soapBody);
```

**Comment by yegeniy** [comment]
The SOAPAction header (and even the Accept header when I uncomment it) comes through when I log it, but the Content-Type header does not.

**Comment by yegeniy** [comment]
`RequestBody` might be the workaround though.

**Comment by yegeniy** [comment]
I thought about this a bit... It's probably for the best to not support "SOAP" (or whatever variant of SOAP that service I need to integrate with is using). (There's always the chance I'm doing something wrong, of course).

It's easy enough to fallback to a java.net.URLConnection for the SOAP integration and use Retrofit for more "rest-ful" APIs.

**Comment by swankjesse** [comment]
No action to take here.
