### ISSUE TITLE
Difference in logged performance on GET Retrofit vs curl

### ISSUE THREAD

**Issue by philippeluickx** [square/retrofit#1456]
Hey!

I am diving into performance improvements. My backend setup is a REST api and I am accessing it through Retrofit.
When I curl, I get timings around 700ms consistently.
However, when I log through Android Studio the timing is a lot higher, 3-6s.

<--- HTTP 200 https://my_api_endpoint (5148ms)

As the curl performs as expected, I am wondering where the time is getting lost. A few possibilities are:

- The request is different (don't think so, both point to the same url, have authentication token and request json format)
- The time logged does not only include the response time, but also some other stuff (what then?)
- My internet is quicker on my pc than my cellphone

I am not sure how to approach this. Any suggestions are welcome!

**Comment by dimitrovskif** [comment]
### Benchmark

Use https://github.com/square/okhttp/tree/master/okhttp-logging-interceptor to log and benchmark all your requests. It can be added as simply as:

```java
OkHttpClient client = new OkHttpClient.Builder();
  .addInterceptor(logging)
  .build();
retrofit.client(client);
```
### Compare with raw OkHttp (to bypass call and converter factories)

Although I really doubt it, the Retrofit pipeline may be slow. That includes a little bit of reflection and annotation parsing, and invoking the call and converter factories.

You could try executing an request using just `OkHttpClient` and compare with `curl`. If that request is 700ms too, then you should check your converter and call factories.

### Check external factors

* curl might not really perform the request and use cache
* if you are using HTTPS, there are a lot of factors which change the server behaviour like cipher suites available, keystores, etc.
* your server may be acting differently with different `User-Agent`s or different IPs

**Comment by JakeWharton** [comment]
> When I curl, I get timings around 700ms consistently.
> However, when I log through Android Studio the timing is a lot higher, 3-6s.

Retrofit has to do one-time reflection-based interface parsing, one-time allocation and lookup of converters and call adapters, schedule the work on a background thread in an executor, build the request object, serialize any body parameters using your converter, execute the request (this is the _only_ thing curl does), read the response, deserialize the response body with the converter, schedule the callback to happen on the callback executor, and deliver the callback to your code.

Retrofit is doing threading, serialization, and allocation in addition to the actual underlying HTTP request, the latter of which is the only thing that curl is doing.

> I am not sure how to approach this. 

The logging interceptor (installed as a network interceptor) will give times similar to curl since it's as close to the (lack of) behavior as curl. The network stacks between Android and curl will also differ wildly so expect to still see some variance.


I'm going to close this issue since it's neither a bug report or feature request and there's no clear action to be taken on our part.

**Comment by philippeluickx** [comment]
Great, thanks for the information! Definitely clears up a bit and makes me a bit less worried...!
