### ISSUE TITLE
java.lang.NoClassDefFoundError: retrofit.Retrofit$Builder

### ISSUE THREAD

**Issue by zhupengGitHub** [square/retrofit#1457]
java.lang.NoClassDefFoundError: retrofit.Retrofit$Builder
      at com.sublet.flip.AppConfig.newRetrofit(AppConfig.java:164)

Always wrong，But this class does exist.

**Comment by JakeWharton** [comment]
The class does exist, so this is a problem with your usage or your build is either not including or stripping away the needed class. Since this isn't a bug with the library itself, please ask your usage question on StackOverflow with the 'retrofit' tag. You should also try to include a lot more information as there's no way to diagnose what's causing the issue with the information presented.
