### ISSUE TITLE
Documentation for 1.8.0

### ISSUE THREAD

**Issue by piefel** [square/retrofit#1473]
The site http://square.github.io/retrofit/ only (partly) covers the 2.0.0 BETA. It would be nice to have documentation on the stable version as well.

**Comment by sohayb** [comment]
this was mentioned in #1061 by @JakeWharton that the old website won't be hosted anymore, but the version 1.x documentation would always be hosted [here](http://square.github.io/retrofit/1.x/retrofit/)

**Comment by piefel** [comment]
OK. But the link you gave leads to the JavaDoc, which is quite another beast. I now use https://web.archive.org/web/20150713235625/http://square.github.io/retrofit

**Comment by JakeWharton** [comment]
The website is hosted and versioned in the repo. If you need a specific
version you can checkout or download a zip for that tag.

**Comment by JakeWharton** [comment]
Here's the zip for 1.8.0 which has the website: https://github.com/square/retrofit/archive/parent-1.8.0.zip. You can also check out the `parent-1.8.0` tag locally or switch to it on GitHub to browse. Because of how we deploy the website there's not a good mechanism to host the older versions, and since there's barely time to finish 2.0 let alone document it, no one has time to setup something for it either.
