### ISSUE TITLE
Old Issue of GSON conversion when json received not meet the criteria !!

### ISSUE THREAD

**Issue by wal-kumail** [square/retrofit#1512]
1) D/RETROFIT: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING 

2) D/RETROFIT: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at 

and so and so..

Old issue, but I wonder what if Retrofit Api handle this exception and return proper error message!

**Comment by wal-kumail** [comment]
the problem is when it receive wrong json app goes crash, it must be fall in failure.

**Comment by JakeWharton** [comment]
This behavior is coming from Gson and the app crashing is the appropriate thing to do. The response content does not match the expected type you supplied in your interface method.

> proper error message

Both messages are clear to me. The first expected a `{` but saw a `"` and the second expected a `{` and saw a `[`. The JSON path is also included to point you at the exact property the failure happened on. For anything more than that, you'll want to file an issue on Gson since Retrofit has nothing to do with reading the body content.

**Comment by wal-kumail** [comment]
Ok thanks! @JakeWharton.

**Comment by akmalazlanjamal** [comment]
Thanks @JakeWharton for clearing things out.
