### ISSUE TITLE
data-urlencode problem

### ISSUE THREAD

**Issue by damianMolinski** [square/retrofit#1525]
I'm using Parse cloud to store data for my android aplication and when i want to get data from table for certain column value Parse suggesting a following cURL request [for given UserID]:

curl -X GET \
-H "X-Parse-Application-Id: Value1" \
-H "X-Parse-REST-API-Key: Value2" \
-G \
--data-urlencode "where={\"UserID\":\"xxx\"}" \
https://api.parse.com/1/classes/Photo

My question is how do i pass 'where' json data to request ?

PS. Get for all values
@GET("classes/Photo")
Call<PhotoList> getPhotos();

**Comment by JakeWharton** [comment]
You can add parameters to your method annotated with `@Query` for query params. In this case, you would use `@Query("where")` and pass the JSON value as the argument.

Retrofit doesn't have anything for automatically converting the value of a `@Query` parameter to JSON, because it's extremely rare to use JSON here. That said, Retrofit offers something called a "string converter" which allows you to create something that will do the JSON converter (using something like Gson) automatically. I realize this is a bit more advanced, so I'll create a sample for this tonight.

**Comment by JakeWharton** [comment]
Example here: https://github.com/square/retrofit/pull/1540
