### ISSUE TITLE
Abstract interface from Response to make Call mockable

### ISSUE THREAD

**Issue by cypressious** [square/retrofit#1533]
`Call.execute()` returns an instance of the final class `Response`. This makes the following mocking strategy (written in Kotlin) impossible:

```kotlin
val apiMock = mock(MyApi::class.java, RETURNS_DEEP_STUBS)
`when`(apiMock.callToApi(myParam).execute().body())
    .thenReturn(MyModel())
```

In my opinion, `Response` should be an interface and the current implementation should implement it.

**Comment by JakeWharton** [comment]
Why do you need to mock a value type?

**Comment by cypressious** [comment]
I'm mocking the complete call chain to the Retrofit interface in order to test the behavior of a class that uses the interfaces.

**Comment by JakeWharton** [comment]
Your example could be:
```kotlin
val apiMock = mock(MyApi::class.java, RETURNS_DEEP_STUBS)
`when`(apiMock.callToApi(myParam).execute())
    .thenReturn(Response.success(MyModel()))
```
or even
```kotlin
val apiMock = mock(MyApi::class.java, RETURNS_DEEP_STUBS)
`when`(apiMock.callToApi(myParam))
    .thenReturn(Calls.response(MyModel()))
```
if you use the 'retrofit-mock' module.

Both of those work today.

**Comment by JakeWharton** [comment]
You don't even need to use mocks for that matter. You can just implement `MyApi` on a class and return `Calls.response(MyModel())` from the implementation.

**Comment by cypressious** [comment]
I guess I could do that. It may be a matter of taste.

**Comment by JakeWharton** [comment]
For sure a matter of taste, but since there's 3 options and I don't see any added value by switching `Response` from a value object I'm going to close.

To summarize for any future travelers: We intentionally made `Call` and the like interfaces since they are stateful objects that might need to be replaced to mimc varying behavior (with fakes, mocks, whatever you want). `Response`, however, is a pure value object so we provide factory methods to allow arbitrary creation so that you explicitly don't have to fake or mock.
