### ISSUE TITLE
how to uplode one file and two String param with form-data 

### ISSUE THREAD

**Issue by woodygithub** [square/retrofit#1544]
@JakeWharton 
```
@Multipart
    @POST(API.URL.ME_UPLOAD_SINGLE)
    Observable<FileModule> postUploadSingle(@PartMap Map<String, RequestBody> filePara);
```

**Comment by JakeWharton** [comment]
You can add two string `@Part` parameters and have one `@Part RequestBody`. Otherwise what you have will work.

Please use StackOverflow with the 'retrofit' tag for usage questions. There's a much more active community and it serves as a place for archiving questions so that future travelers can find them when searching. Thanks.

**Comment by woodygithub** [comment]
thank you very much
