### ISSUE TITLE
Async OATH with Retrofit

### ISSUE THREAD

**Issue by bschnack** [square/retrofit#1591]
Hello,

We are using an OATH service to get a token asynchronously, and then use that token to talk to another service to make our Rest API calls. That would mean that any of the generated Rest API calls from the RestAdapter.create function would need to be wrapped in the callback for the token. Some psuedo code below in case that didn't make sense. Let's say doSomething is a Rest API that we would like to get and getToken gets the authenticated token.

```
getToken(new Callback {
    public void onSuccess(String token) {
        doSomething(token, new Callback {
            public void onSuccess(JsonResponse response) {
                // Handle response
            });
    });
});
```

Having to do that for each rest api that we have seems a bit cumbersome. Is there a way we could put the getToken code in some sort of shared place that all of the rest api's would use? I thought about using the interceptor, but because getting the token is async that wont work.

Thanks,
Brian

**Comment by JakeWharton** [comment]
You can do it in an interceptor but you just have to block the HTTP thread for a period of time while you wait for the oauth token to come back. And presumably you'd have some sort of timeout on that waiting since you don't want to wait forever.

It's not unreasonable that you might wrap the Retrofit interface behind a more domain-specific API which handles the oauth lookup and calling Retrofit for each API call. While Retrofit tries to accommodate as many use cases as possible, sometimes it just can't do everything.
