### ISSUE TITLE
java.lang.NoClassDefFoundError: retrofit2.Retrofit$Builder

### ISSUE THREAD

**Issue by zubyf09** [square/retrofit#1604]
I am facing this issue in 
  compile 'com.squareup.retrofit2:retrofit:2.0.0-beta4'
Getting error on this line/
  retrofit = new Retrofit.Builder()
                    .baseUrl(C.API_ROOT_URL)
                    .build();

**Comment by JakeWharton** [comment]
This is a problem with your build configuration, not Retrofit, and there's not enough information here to figure out what's wrong. Usage questions are best asked on StackOverflow with the 'retrofit' tag (and a lot more details about your build configuration) so that they can be resolved and archived for future developers experiencing similar problems.

**Comment by PaijoRX** [comment]
i got same error today.

**Comment by zubyf09** [comment]
@PaijoRX  this issue because of build configuration.Just Comment you google play services and try to rebuild your project it will works fine for you.After that user only Google Play service which you are using..in You app.https://developers.google.com/android/guides/setup

**Comment by pandiyan022** [comment]
I also got same Issue
 three days im  finding the solution 

please refer [http://stackoverflow.com/questions/37045787/java-lang-noclassdeffounderror-retrofit2-utils-in-android](url)

**Comment by dharmendragkv** [comment]
I also got same issue

**Comment by pandiyan022** [comment]
Remove **"compile 'com.google.android.gms:play-services:8.4.0"** This line in your gradle. and use what u exactly need like location,GoogleAccount,gsm and [etc](https://developers.google.com/android/guides/setup)

**Comment by VishalJogiya** [comment]
still Getting the same Error.. Can someone help me?
also i tried okhttp but still it is not working below 5.0 version.
Didn't find a stackoverflow answer useful to me so posting here.

dependencies {
    compile 'com.android.support:support-v4:25.3.1'
    compile 'de.hdodenhof:circleimageview:1.3.0'
    compile 'com.android.support:appcompat-v7:25.3.1'
    compile 'com.android.support:design:25.3.1'
    compile 'com.android.support:cardview-v7:25.3.1'
    compile 'com.android.support:palette-v7:25.3.1'
    compile files('libs/achartengine-1.1.0.jar')
    compile files('libs/poi-3.2-FINAL.jar')

//    compile files('libs/retrofit-1.9.0.jar')
    compile files('libs/itextpdf-5.1.0.jar')

    compile 'com.google.code.gson:gson:2.8.0'
    debugCompile 'com.amitshekhar.android:debug-db:1.0.0'
    compile 'jp.wasabeef:blurry:2.1.1'
    compile 'com.google.firebase:firebase-ads:10.2.4'

    compile project(path: ':text_drawable_library')
    compile('com.crashlytics.sdk.android:crashlytics:2.5.7@aar') {
        transitive = true;
    }
//    compile 'com.github.wooplr:Spotlight:1.2.3'
    compile 'com.squareup.okhttp:okhttp:2.2.0'
    compile 'com.google.android.gms:play-services-analytics:10.2.4'
    compile 'com.google.android.gms:play-services-auth:10.2.4'

    compile 'com.squareup.retrofit:retrofit:1.9.0'

}


=============================================================
FATAL EXCEPTION: AsyncTask #1
                                                                          java.lang.RuntimeException: An error occured while executing doInBackground()
                                                                              at android.os.AsyncTask$3.done(AsyncTask.java:278)
                                                                              at java.util.concurrent.FutureTask$Sync.innerSetException(FutureTask.java:273)
                                                                              at java.util.concurrent.FutureTask.setException(FutureTask.java:124)
                                                                              at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:307)
                                                                              at java.util.concurrent.FutureTask.run(FutureTask.java:137)
                                                                              at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:208)
                                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
                                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
                                                                              at java.lang.Thread.run(Thread.java:864)
                                                                           Caused by: java.lang.NoClassDefFoundError: retrofit.RestAdapter$Builder
                                                                              at com.tacktile.helper_classes.WebServices.getApi2(WebServices.java:112)
                                                                              at com.tacktile.helper_classes.WebServices.mainMethod(WebServices.java:47)
                                                                              at com.tacktile.helper_classes.WebServices.callWebService(WebServices.java:155)
                                                                              at com.tacktile.helper_classes.WebServices.doInBackground(WebServices.java:162)
                                                                              at com.tacktile.helper_classes.WebServices.doInBackground(WebServices.java:34)
                                                                              at android.os.AsyncTask$2.call(AsyncTask.java:264)
                                                                              at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
                                                                              at java.util.concurrent.FutureTask.run(FutureTask.java:137) 
                                                                              at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:208) 
                                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076) 
                                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569) 
                                                                              at java.lang.Thread.run(Thread.java:864)

**Comment by VishalJogiya** [comment]
> **FIXED!!!**
Updated retrofit lib from 1.9.0 -to - :2.2.0'

I tried removing " multiDexEnabled true" , but not working !!!
Tried adding compile 'com.android.support:multidex:1.0.0' still not working.!!!

# But Finally I fixed this issue by extending my base Application class
**_public class MyApplication extends MultiDexApplication { ... }_**

dependencies {
........
compile 'com.squareup.retrofit2:retrofit:2.2.0'
compile 'com.squareup.retrofit2:converter-gson:2.2.0'
compile 'com.android.support:multidex:1.0.1'
}

defaultConfig {
.......
multiDexEnabled true
}

Please Check this link to know more about multidex enable

(https://developer.android.com/studio/build/multidex.html)
Hope This would help to someone  facing the same issue
--Thanks

**Comment by Mkurbanov** [comment]
04-21 14:06:34.163 4469-4469/? E/Zygote: v2
04-21 14:06:34.173 4469-4469/? E/Zygote: accessInfo : 0
04-21 14:06:34.393 4469-4469/com.mkurbanov.realwebapp E/AndroidRuntime: FATAL EXCEPTION: main
04-21 14:06:34.393 4469-4469/com.mkurbanov.realwebapp E/AndroidRuntime: Process: com.mkurbanov.realwebapp, PID: 4469
04-21 14:06:34.393 4469-4469/com.mkurbanov.realwebapp E/AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/gson/Gson;
04-21 14:06:34.393 4469-4469/com.mkurbanov.realwebapp E/AndroidRuntime:     at retrofit2.converter.gson.GsonConverterFactory.create(GsonConverterFactory.java:42)
04-21 14:06:34.393 4469-4469/com.mkurbanov.realwebapp E/AndroidRuntime:     at com.mkurbanov.realwebapp.MainActivity.onCreate(MainActivity.java:24)
04-21 14:06:34.393 4469-4469/com.mkurbanov.realwebapp E/AndroidRuntime:     at android.app.Activity.performCreate(Activity.java:6904)
04-21 14:06:34.393 4469-4469/com.mkurbanov.realwebapp E/AndroidRuntime:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1136)
04-21 14:06:34.393 4469-4469/com.mkurbanov.realwebapp E/AndroidRuntime:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3266)
04-21 14:06:34.393 4469-4469/com.mkurbanov.realwebapp E/AndroidRuntime:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3415)
04-21 14:06:34.393 4469-4469/com.mkurbanov.realwebapp E/AndroidRuntime:     at android.app.ActivityThread.access$1100(ActivityThread.java:229)
04-21 14:06:34.393 4469-4469/com.mkurbanov.realwebapp E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1821)
04-21 14:06:34.393 4469-4469/com.mkurbanov.realwebapp E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:102)
04-21 14:06:34.393 4469-4469/com.mkurbanov.realwebapp E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:148)
04-21 14:06:34.393 4469-4469/com.mkurbanov.realwebapp E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:7406)
04-21 14:06:34.393 4469-4469/com.mkurbanov.realwebapp E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
04-21 14:06:34.393 4469-4469/com.mkurbanov.realwebapp E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
04-21 14:06:34.393 4469-4469/com.mkurbanov.realwebapp E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
04-21 14:06:34.393 4469-4469/com.mkurbanov.realwebapp E/AndroidRuntime:  Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.gson.Gson" on path: DexPathList[[zip file "/data/app/com.mkurbanov.realwebapp-2/base.apk"],nativeLibraryDirectories=[/data/app/com.mkurbanov.realwebapp-2/lib/arm, /vendor/lib, /system/lib]]
04-21 14:06:34.393 4469-4469/com.mkurbanov.realwebapp E/AndroidRuntime:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
04-21 14:06:34.393 4469-4469/com.mkurbanov.realwebapp E/AndroidRuntime:     at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
04-21 14:06:34.393 4469-4469/com.mkurbanov.realwebapp E/AndroidRuntime:     at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
04-21 14:06:34.393 4469-4469/com.mkurbanov.realwebapp E/AndroidRuntime:     at retrofit2.converter.gson.GsonConverterFactory.create(GsonConverterFactory.java:42) 
04-21 14:06:34.393 4469-4469/com.mkurbanov.realwebapp E/AndroidRuntime:     at com.mkurbanov.realwebapp.MainActivity.onCreate(MainActivity.java:24) 
04-21 14:06:34.393 4469-4469/com.mkurbanov.realwebapp E/AndroidRuntime:     at android.app.Activity.performCreate(Activity.java:6904) 
04-21 14:06:34.393 4469-4469/com.mkurbanov.realwebapp E/AndroidRuntime:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1136) 
04-21 14:06:34.393 4469-4469/com.mkurbanov.realwebapp E/AndroidRuntime:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3266) 
04-21 14:06:34.393 4469-4469/com.mkurbanov.realwebapp E/AndroidRuntime:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3415) 
04-21 14:06:34.393 4469-4469/com.mkurbanov.realwebapp E/AndroidRuntime:     at android.app.ActivityThread.access$1100(ActivityThread.java:229) 
04-21 14:06:34.393 4469-4469/com.mkurbanov.realwebapp E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1821) 
04-21 14:06:34.393 4469-4469/com.mkurbanov.realwebapp E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:102) 
04-21 14:06:34.393 4469-4469/com.mkurbanov.realwebapp E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:148) 
04-21 14:06:34.393 4469-4469/com.mkurbanov.realwebapp E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:7406) 
04-21 14:06:34.393 4469-4469/com.mkurbanov.realwebapp E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method) 
04-21 14:06:34.393 4469-4469/com.mkurbanov.realwebapp E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
04-21 14:06:34.393 4469-4469/com.mkurbanov.realwebapp E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
04-21 14:06:34.393 4469-4469/com.mkurbanov.realwebapp E/AndroidRuntime: 	Suppressed: java.lang.ClassNotFoundException: com.google.gson.Gson
04-21 14:06:34.393 4469-4469/com.mkurbanov.realwebapp E/AndroidRuntime:     at java.lang.Class.classForName(Native Method)
04-21 14:06:34.393 4469-4469/com.mkurbanov.realwebapp E/AndroidRuntime:     at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
04-21 14:06:34.393 4469-4469/com.mkurbanov.realwebapp E/AndroidRuntime:     at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
04-21 14:06:34.393 4469-4469/com.mkurbanov.realwebapp E/AndroidRuntime:     at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
04-21 14:06:34.393 4469-4469/com.mkurbanov.realwebapp E/AndroidRuntime:     		... 15 more
04-21 14:06:34.393 4469-4469/com.mkurbanov.realwebapp E/AndroidRuntime:  Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

How I can :(

**Comment by Nithinpj** [comment]
implementation 'com.squareup.retrofit2:retrofit:2.5.0'

implementation 'com.squareup.retrofit2:converter-gson:2.5.0'

implementation 'com.squareup.retrofit2:converter-scalars:2.5.0'
