### ISSUE TITLE
how can i get status code on failure in retrofit 2?

### ISSUE THREAD

**Issue by Aravind-Rajendran** [square/retrofit#1612]

**Comment by JakeWharton** [comment]
If failure is called where was no response to have a status code. When the response callback is called you must check `isSuccess()` (or the status code) to determine if the response was successful or not.

**Comment by siavashabdoli** [comment]
@JakeWharton we test it with something like wireshark and get 503 error from server but retrofit call onFailure. So seems 5xx errors call onFailure. How can we detect this kind of status code?

**Comment by siavashabdoli** [comment]
Ok I found the problem! socketTimeoutException occurs after 10s and server 503 error receive after this so I can't get this code! now I want to increase time of timeout! it related to OKhttp AFAIK.

**Comment by rkumar29** [comment]
@JakeWharton what is the response code we get in case of success and failure api calls using retrofit

**Comment by MGaetan89** [comment]
I've got the same request as @oscarshaitan.

The `onFailure` is called because of a `JsonSyntaxException` (my API returns some HTML instead of the expected JSON). But I would like to process the response body myself in this case. But as far as I can tell, there is no way to access that body from the `onFailure` method.
Am I missing something ?

**Comment by JakeWharton** [comment]
The response was consumed by the JSON converter. It's not available.

**Comment by MGaetan89** [comment]
Thanks for the confirmation. I managed to do what I wanted by using a custom Gson converter.
