### ISSUE TITLE
No retrofit annotation found.

### ISSUE THREAD

**Issue by yhj2062** [square/retrofit#1643]
Hello 
I'm using retrofit 2.0 beta and I got the error below

exception occurred while doing in background: No Retrofit annotation found. (parameter #1)
                                                                    for method FileUploadService.upload
                                                                java.lang.IllegalArgumentException: No Retrofit annotation found. (parameter #1)

I'm trying to upload multiple files.
```

Map<String, RequestBody> map = new HashMap<>(list.size());
RequestBody file = null;
File f = null;
for(int i = 0; i < list.size(); i++){
		f = new File(list.get(i).getPhotoPath());
	file = RequestBody.create(MediaType.parse("image/jpg"), f);
	map.put("" + i + "\"; filename=\"" + i + ".jpg", file);
	file = null;
	f = null;
}
Call<String> call = fileUploadService.upload(map, description);


```

```
public interface FileUploadService {
	@Multipart
	@POST("user/photographer/upload")
	Call<String> upload(
			@PartMap() Map<String, RequestBody> files,
			@Part("description") RequestBody description

	);
}

```

**Comment by JakeWharton** [comment]
Are you using proguard?

**Comment by yhj2062** [comment]
@JakeWharton yeah, I'm using proguard

**Comment by JakeWharton** [comment]
ProGuard is likely stripping the annotations because it's not smart enough to know they're useful. Use the ProGuard configuration from the website: http://square.github.io/retrofit/.

**Comment by yhj2062** [comment]
I added it to proguard-rules.pro

-dontwarn retrofit2.**
-keep class retrofit2.** { *; }
-keepattributes Signature
-keepattributes Exceptions


but still same error..

**Comment by yhj2062** [comment]
I'm using 2.0.0-beta3

**Comment by JakeWharton** [comment]
I'm not a proguard user, so you'll have to consult somewhere that proguard users browse. Maybe try #1635 first? Otherwise StackOverflow is your best bet.

**Comment by d-rahul** [comment]
Are you sure you can use PartMap and Part annotation with Multipart request just verify it. Or you should verify your request code, all retrofit request annotations should be there and well formatted. Check more here: https://readyandroid.wordpress.com/no-retrofit-annotation-found-retrofit/

**Comment by AlexJuca** [comment]
@JakeWharton any reason why you don't use proguard?

**Comment by AlexJuca** [comment]
I had a similar error message. It seems to be caused by pro-guard on my side. Pro-guard removes the annotations in build time while it creates the apk so by the time your actually running your code it blows with that error message because at runtime the retrofit annotations were not found.

I modified the pro-guard rules so that it does not effect the retrofit annotations.

-keep class retrofit2.http.** { *; }

Hope this is useful to anyone.

**Comment by gutoxp** [comment]
i had similar error as well in the app that use my library that uses **v2.9.0** and interface api:
```kotlin
@POST("v1/logs/list")
 suspend fun logsList(
            @Body logsRequest: List<LogData>,
            @Header("content-Type") contentType: String = "application/json"
 ): Response<Void>
```
The app was using the **v2.5.0** retrofit to another web service.
The StackTrace pointed the response: **Response<Void>** as cause of the missing annotation

When i updated the app retrofit version the problem was solved

**Comment by enshaw** [comment]
No Retrofit annotation found. (parameter #1) using v2.9.0

**Comment by enshaw** [comment]
> No Retrofit annotation found. (parameter #1) using v2.9.0

by adding @Body in request resolves the issue
