### ISSUE TITLE
How to deal with RequestBody in Spring

### ISSUE THREAD

**Issue by yhj2062** [square/retrofit#1646]
I'm developing sending multiple files to spring server.

My FileUploadService is as below.

    public interface FileUploadService {
        @Multipart
        @POST("user/photographer/upload")
        Call<String> upload(
                //@Part("myfile\"; filename=\"image.png\" ") RequestBody file,
                @PartMap Map<String, RequestBody> files,
                @Query("description") String description

        );
}

In that code, RequestBody in Map object has an image and send them to Spring server.

But I don't know to deal with it in server.

    @RequestMapping(value ="/photographer/upload", method = RequestMethod.POST)
    public @ResponseBody
    String uploadFileHandler(@RequestParam Map<String, MultipartFile> file,         @RequestParam("description") String description){
        return "";
    }

I thought I can get first parameter as Map, but It wasn't..

Even thought I put 3 things to Map object in client, server only get one thing in Map object having wrong informaiton than I expected.

Is there anyone knows about it?

**Comment by JakeWharton** [comment]
Since this is a question about Spring unfortunately you're not going to get a lot of traction on GitHub issues here. Your best bet is to ask a question on StackOverflow and include both the 'spring' and 'retrofit' tags. That will ensure the right people see it and can help you figure out how to handle the upload.
