### ISSUE TITLE
Retrofit 2.0 Migration Guide

### ISSUE THREAD

**Issue by eygraber** [square/retrofit#1669]
Can there be (or is there) a migration guide that goes through what is needed when upgrading to 2.0? Having a project that uses 1.X extensively, it would be nice to know what pieces are going to break, and how to fix them.

**Comment by eneim** [comment]
IMO R1 and R2 is different APIs from the core. You should rewrite them to save your head.

**Comment by DearDhruv** [comment]
Also links are not updated on the Read.me as well as on the website.

**Comment by peitek** [comment]
Retrofit 2 changes quite a few things, so I don't think it's as simple as changing a few method names & imports to migrate from 1.9. I used the opportunity to improve my app code internally, since Retrofit 2 makes some things much easier. I think it's worth it to spend some time thinking about the architectural changes and possibly adapt your usage as well.

But if you're curious for an overview of changes, you can give [this upgrade guide](https://futurestud.io/blog/retrofit-2-upgrade-guide-from-1-9) a read.

**Comment by JakeWharton** [comment]
There's a really good guide here: https://medium.com/@sasa_sekulic/quick-and-easy-guide-to-retrofit-2-0-setup-or-migration-with-rxjava-ab7a11bc17df

**Comment by eygraber** [comment]
Awesome.
