### ISSUE TITLE
allow ServiceMethod & the URI template parsing to be reused by server side frameworks?

### ISSUE THREAD

**Issue by jstrachan** [square/retrofit#1684]
We'd like to reuse the annotations and URI template parsing logic inside Retrofit so that we can use the same annotated Java interface both for the client side with Retrofit and to implement a server side via [vertx web](https://github.com/vert-x3/vertx-web/). 

For background see: 
https://github.com/vert-x3/vertx-web/issues/336

So we'd like to reuse code like this:
https://github.com/square/retrofit/blob/7b130a665d4cfbabc906e1d123446251220e1535/retrofit/src/test/java/retrofit2/RequestBuilderTest.java#L2219-L2226

to get an object like ServiceMethod but then navigate its data (URL, headers, paths, parameters and so forth) to then implement the server side equivalent for the same Java interface/method.  Right now this object is not public, nor are there any getters to access the information.

We could hack it with reflection but that sounds icky ;). Would you be cool with a PR to refactor the code so that ServiceMethod and the helper method to create it from a Retrofit + Method was moved into a separate package marked 'internal' or 'support' or something so that it can be excluded from the javadoc but can be reused by other libraries (e.g. vertx?)

**Comment by vietj** [comment]
:+1: that would certainly be something Vert.x would benefit of!

**Comment by vietj** [comment]
with a few modification (added a visitor interface because it keep retrofit service method data internal) it can be used to build a vertx web router like this https://github.com/vietj/vertx-retrofit/blob/master/src/test/java/retrofit2/ServerTest.java

**Comment by jstrachan** [comment]
@vietj ah great thanks!

**Comment by swankjesse** [comment]
Neat! I think it’s probably a bit awkward to define the same exact interface for both clients and servers. Were you planning on this?

Or just sharing the reflection & validation code that makes sure a method declaration makes sense as an HTTP method?

**Comment by jstrachan** [comment]
@swankjesse so in JAXRS folks do this quite often; defining a Java interface to represent a REST client and then implementing it to provide an implementation of the service. 

But yeah, the main goal here is to share reflection, validation & URI template parsing code & ensure consistency between client side & server side.

**Comment by vietj** [comment]
@swankjesse what's the best way to contribute ? a PR in which changes can be discussed ? I can push changes in a fork so you can have a look later.

**Comment by JakeWharton** [comment]
We've explored this twice before and it usually ends up making the interface API and annotations worse. It's the same problem as making a request/response model API (ala OkHttp) work on both client and server; it can be done, but it makes both APIs worse.

For example, there's no way to add headers/cookies to the response, read headers/cookies from the request, you'll require multiple server implementations for the same endpoint if the person is using fixed headers/query params/path segments/etc.

From what I've seen re-using the interface for both server and client only works in the most trivial of cases and it would require significant (breaking) changes to the annotations to make it smooth for both sides–but then we're likely just the same as JAX-RS.

My current best approach for this is defining your service in a language agnostic format (e.g., protocol buffers `service`) and then generating the client and server implementations. It's similar to what one would do to share model types. One could share model types between client and server but often it's easier to share the _shape_ of those model types to allow generating idiomatic versions for each platform that (de)serialize to the same thing. In this case, Retrofit is a service definition that's biased heavily towards the client.

I'm not discouraging you from trying, but I would prefer it evaluated much more comprehensively in a fork before we start making changes to Retrofit since I still need to be convinced of whether it's viable or not.

**Comment by vietj** [comment]
@JakeWharton actually I am not a proponent of using the same interface for client / server.

My only wish is to provide an annotated interface model for client (i.e retrofit base job) and also provide an interface + implementation on server. Interfaces don't have to be the same. Vert.x currently provides via vertx-web an api for building http server via a builder approach (similar to express-js). Retrofit would be used for building the vertx-web router and dispatching to the impl for those who prefer to use the retrofit model.

**Comment by vietj** [comment]
To sum up for server : retrofit would allow to build a jaxrs like model for server easily without having to implement an whole container approach like jaxrs does but more a programmatic / embeddable / lib approach.

**Comment by swankjesse** [comment]
Yep. Please fork the classes in Retrofit to accelerate building something better than JAX-RS. But I also don’t think we’re ready to make that stuff a public API.

**Comment by vietj** [comment]
actually I don't mind if it's not public and is subject to change. I could make vertx-retrofit in beta or tech preview for a while.

**Comment by swankjesse** [comment]
We’re experimenting with our own framework. No annotation sharing at the moment.
https://github.com/square/misk/blob/master/exemplar/src/main/kotlin/com/squareup/exemplar/actions/HelloWebPostAction.kt

No further action here.
