### ISSUE TITLE
Provide Proguard for us, so we dont have to add it to our own proguard configs

### ISSUE THREAD

**Issue by Spoetnic** [square/retrofit#1708]
[Feature Request]
An android library can provide a proguard configuration by add this line to the `defaultconfig` node:
`consumerProguardFiles 'proguard-rules-retrofit.pro'`

where the proguard-rules-retrofit.pro file can be managed/updated by Square itself, without people needing to add anything to their own proguard files.

I'd love to hear your thoughts on this.

Regards, 
JW

**Comment by JakeWharton** [comment]
Retrofit isn't packaged as an .aar so it cannot embed a consumer proguard file. The library is a .jar since it's also a library for general Java development. The best we can do is publish it somewhere, and so it's included on the website. It's also mostly managed by the community since I am not a ProGuard user.
