### ISSUE TITLE
using body annotation error in post xml

### ISSUE THREAD

**Issue by leonard0629** [square/retrofit#1726]
i defined method like this,
`
Call<WxPrepayOrderModel> createPrepay(@Body WxPrepayModel prepay);
`
and it throws
`
java.lang.IllegalArgumentException: Unable to create @Body converter for class com.test.WxPrepayModel (parameter #1)
`

i've already add @Root, @Element on my class and property
i use simplexml-converter

**Comment by leonard0629** [comment]
i solved it

**Comment by JakeWharton** [comment]
The full stacktrace will give you the reason for the failure as one of the "Caused by" exceptions lower in the trace. If you are using the Simple Framework converter that means this is a problem in how you've configured your model objects. You can either consult the documentation to try and resolve this yourself or I would recommend posting to StackOverflow (with more information). We don't use Simple Framework or XML at all so not only are we not suited to help but the problem isn't actually with Retrofit.

**Comment by leonard0629** [comment]
thx, i forgot to close it. i solved it by modify the judgment in requestBodyConverter method
from
`
for (Annotation annotation : parameterAnnotations) {
}
`
to
`
for (Annotation annotation : methodAnnotations) {
}
`

**Comment by SardarRashid** [comment]
same error here how you  solve?
