### ISSUE TITLE
Converter-SimpleXml(InvalidPackage: Package not included in Android)

### ISSUE THREAD

**Issue by riveryan** [square/retrofit#1758]
This is a SimpleXml Lib lint error, Will you guys fix it?
1.simple-xml-2.7.1.jar: Invalid package reference in library; not included in Android: javax.xml.stream.events. Referenced from org.simpleframework.xml.stream.StreamReader.
2. simple-xml-2.7.1.jar: Invalid package reference in library; not included in Android: javax.xml.stream. Referenced from org.simpleframework.xml.stream.StreamProvider.

**Comment by JakeWharton** [comment]
This is an issue of the Simple XML library itself, not the converter supplied by Retrofit.

**Comment by oliverlockwood** [comment]
For the reference of others who come across this, the following links are useful:
-  https://sourceforge.net/p/simple/mailman/simple-support/thread/339270128E13BE47A6B10EED7367E7852BC2A912@MERCMBX18D.na.SAS.com/ (explaining why the issue is not a problem)
-  https://bitbucket.org/KrzysztofKocel/wykrywaczaukcji/pull-requests/10/build-lint-fixing-lint-step-by-ignoring/diff (an example of how you might choose to ignore the issue).

**Comment by Vespira** [comment]
Hi there, as I don't think that suppress lint errors can be a good solution, I tried to solve the issue.

I found a resource on stackoverflow: http://stackoverflow.com/questions/18084285/using-simplexml-with-android-and-gradle

But still, excluding modules from simple-xml didn't work for me. The lint process ran by Gradle is always blocking on the fact that probably, Android API contains few modules that are also present in Simple-XML.

Anyone solved this ? (without just ignoring the error).
