### ISSUE TITLE
how can i do with Retrofit like     httpPost.setEntity(params);

### ISSUE THREAD

**Issue by zlm54585652** [square/retrofit#1826]
`DefaultHttpClient httpClient = new DefaultHttpClient();

        String url = "https://abc.123.com/app/channellist";

        HttpPost httpPost = new HttpPost(url);

        StringEntity params = new StringEntity("{\"records\":10, \"pnum\":1, \"ofield\": \"ctime\", \"sort\": 1}");

        httpPost.setEntity(params);

        HttpResponse response = httpClient.execute(httpPost);`

I use @Body String json  @Body RequestBody but not work

**Comment by JakeWharton** [comment]
`@Body String` will work if you install the 'scalars-converter'. You can also create a Java model object which represents the JSON and use a converter (like the Gson one) to automatically serialize it. Otherwise `@Body RequestBody` lets you specify raw request data and will allow any format.

If something is not working in Retrofit, please provide an executable test case that demonstrates the problem along with the expected result so that we can reproduce it and see exactly what you think should be happening.
