### ISSUE TITLE
Specifying the methods for dynamic requests

### ISSUE THREAD

**Issue by gmaglaka** [square/retrofit#1831]
It's really good HTTP client.
I would like retrofit to have possibility of specifying Http methods to request  at runtime.
In my Web Service I don't know what HTTP method to call in advance, so annotations @GET, @POST, ... are useless.

**Comment by JakeWharton** [comment]
We've had this request not long ago (#1607) and I wrote why we decided not to include this functionality: https://github.com/square/retrofit/issues/1607#issuecomment-185339633. Retrofit works best when endpoints are well-defined and static since the information can be encoded in the interface instead of client code. At this level of dynamism there's diminishing returns, and you're probably better off using OkHttp directly (or with a thin wrapper).
