### ISSUE TITLE
 GsonConverterFactory GsonRequestBodyConverter not handling Polymorphism 

### ISSUE THREAD

**Issue by surinderdua92** [square/retrofit#1834]
[http://stackoverflow.com/questions/5800433/polymorphism-with-gson](url)

This was working fine in Retrofit 1.9. Is there any way to avoid use of registerTypeAdapter?

**Comment by JakeWharton** [comment]
We have intentionally not support polymorphism by default because it is not the common use when defining API endpoints. You can see more information in #1192 and #1745.

If you need polymorphic serialization then you will need to create your own `Converter.Factory` whose request body `Converter` delegates to `Gson` using the runtime class of the object that's passed in.
