### ISSUE TITLE
Should HttpException be final?

### ISSUE THREAD

**Issue by matir91** [square/retrofit#1860]
Sometimes I need to map the `HttpException` in other exception in order to manage the error (for example to manage the body error message). So I created a custom exception class which extends `Exception`. In my opinion it would be better if my custom exception could extend from `HttpException` but as it's final, I cannot do so.

**Comment by JakeWharton** [comment]
I don't want to open the exception up to extendability for a few reasons. The biggest one is that exceptions are a poor delivery mechanism for typed data because of how they're propagated. Right now we only provide `HttpException` because we have to, but (assuming you're referring to the RxJava one and not Guava or Java 8) I much prefer using `Response<T>` or `Result<T>` as my type so that the exception can be avoided altogether. This makes much more clear the data's origin and how it's being acted upon. The second thing is that exception have weird serializable properties that we ran into problems with in Retrofit 1 that I don't want to deal with if it became a non-final type.

I would strongly suggest using a delivery mechanism that's not an exception but represents a failure as a regular class (similar to `Response<T>` and `Result<T>`) instead.
