### ISSUE TITLE
RxJava adapter: using OkHttp dispatcher as a Scheduler

### ISSUE THREAD

**Issue by llooz** [square/retrofit#1889]
I was thinking to make retrofit use the okhttp dispatcher when using the rxjava adapter
Would it be possible to create some sort of Scheduler that uses the dispatcher of the okhttp client instance assigned to retrofit? This to share same underlying threads (executor) and to comply to the limits for max requests per host etc.

**Comment by swankjesse** [comment]
OkHttp doesn’t manage other uses of its executor, so it’s difficult to see how this would work.

**Comment by JakeWharton** [comment]
You can write a separate RxJava `CallAdapter.Factory` which uses OkHttp's `Call.enqueue` instead of `Call.execute`. This will use OkHttp's built-in per-host limiting for all observable requests. The thing to be careful of it you do this, and the reason it's not the default already, is that it makes `subscribeOn` useless. Regardless of what thread you subscribe on, the observable will always execute asynchronously and on OkHttp's own executor.

We might make this the default behavior in Retrofit v3 which talks to an OkHttp v4 in the future for other reasons, but that decision and implementation is easily a year or more away.
