### ISSUE TITLE
Bug: Pipe (|) not encoded in parameter or value of @Query annotation in Retrofit 2.1.0

### ISSUE THREAD

**Issue by justingarrick** [square/retrofit#1891]
Pipe characters (`|`) are not properly URL encoded (`%7C`) in the parameter or value portion of a `@Query` annotation in Retrofit 2.1.0.  This looks like a possible regression of #1356.

Test case:

```
compile 'com.squareup.retrofit2:retrofit:2.1.0'
compile 'com.squareup.retrofit2:converter-jackson:2.1.0'
compile 'com.squareup.okhttp3:logging-interceptor:3.3.1'
testCompile 'junit:junit:4.12'
testCompile 'com.squareup.okhttp3:mockwebserver:3.3.1'
```

```
import okhttp3.ResponseBody;
import okhttp3.mockwebserver.MockResponse;
import okhttp3.mockwebserver.MockWebServer;
import okhttp3.mockwebserver.RecordedRequest;
import org.junit.Rule;
import org.junit.Test;
import retrofit2.Call;
import retrofit2.Response;
import retrofit2.Retrofit;
import retrofit2.http.GET;
import retrofit2.http.Headers;
import retrofit2.http.Query;

import static org.junit.Assert.assertEquals;

public class QueryPipeBug {
    @Rule public final MockWebServer server = new MockWebServer();

    interface Service {
        @GET("/path")
        @Headers("User-Agent: Test Case")
        Call<ResponseBody> search(@Query(value = "paramwith|pipe", encoded = false) String keyword);
    }

    @Test public void test() throws Exception {
        Retrofit retrofit = new Retrofit.Builder()
                .baseUrl(server.url("/"))
                .build();
        Service example = retrofit.create(Service.class);

        server.enqueue(new MockResponse()
                .addHeader("Content-Type", "text/plain")
                .setBody("Hi"));

        Call<ResponseBody> call = example.search("valuewith|pipe");
        Response<ResponseBody> response = call.execute();

        RecordedRequest recordedRequest = server.takeRequest();
        assertEquals("/path?paramwith%7Cpipe=valuewith%7Cpipe", recordedRequest.getPath());
    }
}
```
```
Expected :/path?paramwith%7Cpipe=valuewith%7Cpipe
Actual   :/path?paramwith|pipe=valuewith|pipe
```

**Comment by swankjesse** [comment]
This behavior is consistent with Safari, Firefox & Chrome.
https://docs.google.com/spreadsheets/d/1BgGAhJ5WE3JBsATeudamiBzxmgEhwkfcFqQmPx8qrkc/edit?usp=drive_web

**Comment by oliverlockwood** [comment]
I've just hit the same problem.  In my case, it was when testing against a Wiremock instance.  The code in Wiremock attempts to create a `java.net.URI` object from the URI string; this fail with an `IllegalArgumentException` saying "Illegal character in query", thrown [here](http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/8u40-b25/java/net/URI.java?av=f#3021).  This code, in the core JDK, clearly follows [RFC3986](https://tools.ietf.org/html/rfc3986) closely enough to reject the pipe character coming in as a query param.

The conflict here between Retrofit/OkHttp browser-convention based approach and Java's standards-based approach is therefore causing problems.

@swankjesse Can you please explain the rationale for following these browser conventions rather than the official IETF standards?  Many thanks.

**Comment by swankjesse** [comment]
Because it works better on the Internet, which has pages that aren’t reachable java.net.URI.

You can still get what you want though, use HttpUrl’s uri() method to force encoding of characters that don’t otherwise need it.

**Comment by oliverlockwood** [comment]
@swankjesse - thanks for answering.

**Comment by ralphhm** [comment]
With Apache Tomcat 8.0.39 they [don't accept unencoded pipe "|" in urls anymore](https://github.com/apache/tomcat80/commit/779d5d34e68e50d2f721897050b147106992f566). This broke a main functionality in our App by always reurning HTTP code 400 (bad request) because our API uses the pipe in query param values. How to go on with this? Is there any quick fix or switch to change the encoding behavior?

**Comment by swankjesse** [comment]
If you’d like a workaround, here’s an ugly one. Just use an interceptor to rewrite the request URL by passing it through java.net.URI, which will force encoding of certain characters.

```
    Interceptor interceptor = new Interceptor() {
      @Override public Response intercept(Chain chain) throws IOException {
        Request request = chain.request();
        request.newBuilder()
            .url(request.url().uri().toString())
            .build();
        return chain.proceed(chain.request());
      }
    };
```

Install that on your OkHttpClient and you’re good to go.

**Comment by swankjesse** [comment]
Relevant documentation: https://square.github.io/okhttp/3.x/okhttp/okhttp3/HttpUrl.html#uri--

**Comment by MisoMurin** [comment]
I bumped into the same problem when I tried to add a query parameter with more values, using `|` as a delimiter. I solved it without an Interceptor:

1. Append `%7C` instead of `|` as a delimiter.

2. Define the query param as following `@Query(encoded = true, value = "param") String param`

This way okhttp doesn't replace `%` character with `%25` and leaves the delimiter unmodified - `%7C`
