### ISSUE TITLE
how to get http code，like http 201 and 204

### ISSUE THREAD

**Issue by firelion0725** [square/retrofit#1941]
our server think http 201 and 204 is success，but I used okhttp3+retrofit2  I don‘t get respond http code，how could set okhttp to receive http 201 and 204 , is not onFailure.

**Comment by FabianTerhorst** [comment]
I have noticed the same, that okhttp without retrofit doesn´t throw the HttpException.

**Comment by JakeWharton** [comment]
All HTTP responses, 2xx code or otherwise, are delivered to `onResponse`. 201 and 204 are [treated as successful][1].

If `onFailure` is being called then you should look at the exception that was passed for the cause.

 [1]: https://github.com/square/retrofit/blob/fccedbeb4d5181c926fff450cdf5c5116ef0eeaa/retrofit/src/main/java/retrofit2/Response.java#L115

**Comment by FabianTerhorst** [comment]
@JakeWharton whats about Http 302?

**Comment by JakeWharton** [comment]
That will never reach the application layer. OkHttp will turn it into a 200
and serve from the cache.

**Comment by FabianTerhorst** [comment]
And when followRedirects is turned false?

**Comment by JakeWharton** [comment]
Then it will
