### ISSUE TITLE
when response is a simple string

### ISSUE THREAD

**Issue by zhuxiang1985** [square/retrofit#1944]
```
  public static interface testService{
        @POST("/")
        Call<String> send(@QueryMap Map<String, String> para);

        @POST("/json")
        Call<Map> send2(@QueryMap Map<String, String> para);
    }


testService service = retrofit.create(testService.class);
       Call<String> call = service.send(map);
        Response<String> response = call.execute();

       Call<Map> call = service.send2(map);
        Response<Map> response = call.execute();
```
I post a request(send2) to the server use this service. when the response is a Json formate or Java Entity,everything is ok, but when I use "send" service and server response a simple string ,like "errorCode=1234", we will catch a Exception " Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 1 path " . How can I do now?

**Comment by mhkubaid** [comment]
In other words, could a POST-call be established without a predefined response type or object? Meaning, taking the raw response from the server as it is. That way the response can then be parsed later from the response body or raw elements. Otherwise it becomes too difficult (by defining a custom adapter for such a trivial case) to read all failure case result messages from the server side that are not a JSON object.

In my case, when the login POST method is called, the server returns a JSON user object if the credentials match; or it returns some string error-messages pertaining to the failed credential. It's almost impossible to setup a call without losing the server-side error-messages. With retrofit2.1.0, I have tried using the okhttp3.Response and okhttp3.Responsebody objects for the Response type, but all in vain. 

What might be an easy solution for this?

**Comment by JakeWharton** [comment]
You can use `okhttp3.ResponseBody` as the type and then call `.string()` for a string result. Additionally, by installing the [scalar converter][1] before the JSON converter on your `Retrofit.Builder` you can use `String` directly as the response type. Both of these will prevent the response from being parsed as JSON.

 [1]: https://github.com/square/retrofit/tree/master/retrofit-converters/scalars
