### ISSUE TITLE
Multipart request may lost some params

### ISSUE THREAD

**Issue by kirsting** [square/retrofit#1956]
I am using @PartMap to build the multipart request.
````java
    @Multipart
    @POST("upload")
    Observable<FileUploadResponse> uploadFile(@PartMap Map<String, RequestBody> params);
````
There are three parts I need to send: "size", "type", and file part. "size" and "type" are text/plain parts.
If I use a HashMap, in some device the "size" part will be sent after file part, which will lead the lost of "size" part.
To solve this, I use a LinkedHashMap to keep parts in order.
````java
Map<String, RequestBody> map = new LinkedHashMap<>();
        map.put("size", RequestBody.create(MediaType.parse("text/plain"), String.valueOf(file.length())));
        map.put("type", RequestBody.create(MediaType.parse("text/plain"), mimeType));
        map.put(String.format("file\"; filename=\"%s", file.getName()), new ProgressRequestBody(file, MediaType.parse(mimeType), progressListener));
```` 
I've read the ParameterHandler.java and RequestBuilder.java and seems Retrofit doesn't care about  the order of parts. Did I miss something? Did I use Retrofit a wrong way to send multi-parts or the order of parts should not be controlled by Retrofit?

**Comment by JakeWharton** [comment]
Parts are added by calling `.entrySet()` and iterating over the result which means the order returned by the map is retained: https://github.com/square/retrofit/blob/c0bef604924007b5bcebf221ea626e4b7807c18b/retrofit/src/main/java/retrofit2/ParameterHandler.java#L264. Since HashMap guarantees no order, switching to a map that does is the right solution.
