### ISSUE TITLE
An error when I use Header with Chinese !

### ISSUE THREAD

**Issue by liuzhao2007** [square/retrofit#1976]
java.lang.IllegalArgumentException: Unexpected char 0x7ebd at 0 in deviceMode value: 纽麦-N960.

**Comment by JakeWharton** [comment]
This exception is from OkHttp, not Retrofit, but the problem is that header values are limited to the ISO 8859-1 charset per [RFC 5987][1]. If you are using dynamic values in headers then you need to guard against characters that cannot be represented in this charset.

 [1]: https://tools.ietf.org/html/rfc5987
