### ISSUE TITLE
Get Conversion Error API Response

### ISSUE THREAD

**Issue by MSayyaf** [square/retrofit#2058]
Retrofit version: 2.1.0

As I know, to handle conversion errors we should use onFailure method, and check if the error is instance of JsonSyntaxException or IllegalStateException or MalformedJsonException, but in general it should be instance of IOException.

My problem: I am expecting to get the invalid okhttp3.Response in onFailure method in case we have a server response, and to get the sent arguments.

For more details: I am sending all strange errors to Errbit (https://github.com/welaika/errbit-android), like the UncaughtException and the conversion errors ...etc, and I want to send the response in this case to know what exactly it was when the error happened, and unfortunately I didn't find a way to send the received response or the sent arguments to Errbit, because the onFailure method doesn't have the invalid response or the sent arguments, of course I can do it using the OkHttp intercepters but in this case I have to parse the response which not a correct solution.

Note: sorry for my English.

**Comment by JakeWharton** [comment]
We have no way of getting the response because it was consumed by the attempt at conversion. Retrofit would have to buffer every request so that it could be consumed twice in the case of an error which is a crazy thing to do when it adds so much overhead to the normal case where you only need to read the response once. A good way to handle this would be to mark your requests or responses with a trace ID and report the failed conversion using that trace ID. This way the much more powerful server can do things like record the responses it sends to clients for a limited period of time and when an error occurs they can be looked up by the trace ID.
