### ISSUE TITLE
Request Priorities for parallel requests 

### ISSUE THREAD

**Issue by saisasanksunkavalli** [square/retrofit#2066]
I have an app , where I will be making 7 parallel requests in a dashboard. I want the responses of 3 requests earlier than the other 4.  Is it possible to set a request priority for some requests like HIGH,MEDIUM & LOW, so that requests with HIGH will be executed first.

**Comment by JakeWharton** [comment]
Retrofit does not execute requests and so it has no mechanism for influencing request priorities. Requests are either executed asynchronously or by blocking by whatever `Call.Factory` you are using, usually it's OkHttp. OkHttp does not have a request priority mechanism, but it would be the point where you would need to get it added in order to provide requests at the Retrofit level.
