### ISSUE TITLE
[Feature Request] Add "returnType" to requestBodyConverter

### ISSUE THREAD

**Issue by stavfx** [square/retrofit#2086]
I'm trying to use Retrofit to communicate with an API that expects unique `Content-Type` and `Accept` headers for every object type that is sent/received.
I've managed to use a Converter to add the correct `Content-Type` according to the `@Body` object. But in order to set the `Accept` header, I need to know what the method is expecting to be returned.
E.g. if this is my code
```
@POST("invitation")
Observable<InvitationResponse> createInvitation(@Body InvitationRequest request);
```
I need to make sure the `Accept` header is set to `application/invitation_response+json`.

Of course this can be done with custom annotations, but I don't want to declare the expected return type is `InvitationResponse` twice.

Maybe there's a way I missed to achieve this without complicating the definition, but adding the "returnType" to Converter.Factory.requestBodyConverter() would allow me to solve this in a similar manner to how I handled `Content-Type`.

**Comment by JakeWharton** [comment]
We cannot add methods to the Converter interface since that would be source
and binary incompatible. I'm not sure how this change would help you anyway
unless you're saying that Retrofit would use this method for the Accept
header value which seems like a very specific change that would serve only
you and no one else.

As far as I can tell there's no way to do this at present. The best you
have is using @Header since we don't let CallAdapters or Converters add
arbitrary headers.

This is something a Retrofit-level interceptor would solve, but we haven't
come up with a good design for it yet.

On Thu, Nov 17, 2016 at 4:32 PM Stav Raviv <notifications@github.com> wrote:

I'm trying to use Retrofit to communicate with an API that expects unique
Content-Type and Accept headers for every object type that is sent/received.
I've managed to use a Converter to add the correct Content-Type according
to the @Body object. But in order to set the Accept header, I need to know
what the method is expecting to be returned.
E.g. if this is my code

@POST("invitation")
Observable<InvitationResponse> createInvitation(@Body
InvitationRequest request);

I need to make sure the Accept header is set to
application/invitation_response+json.

Of course this can be done with custom annotations, but I don't want to
declare the expected return type is InvitationResponse twice.

Maybe there's a way I missed to achieve this without complicating the
definition, but adding the "returnType" to
Converter.Factory.requestBodyConverter() would allow me to solve this in a
similar manner to how I handled Content-Type.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/square/retrofit/issues/2086>, or mute the thread

**Comment by stavfx** [comment]
Yes, I realize this is a very specific case.
I also noticed that the way I was able to "set the Content-Type header" was actually by using `RequestBody.create(MEDIA_TYPE, body)` which won't be applicable to other headers, like you said.
I guess I'll keep using the `@Header/@Headers` annotations, thanks :)
