### ISSUE TITLE
A way to define an error type for endpoints

### ISSUE THREAD

**Issue by BoD** [square/retrofit#2118]
Often, APIs return one type of objects for the "normal" case, and a different type for "error" cases.
Currently the way to get the error object is to "manually" deal with transforming it from the `Response`, as shown here for instance: http://stackoverflow.com/questions/35029936/centralized-error-handling-retrofit-2
 
It would be great if there was a way to define the error type when declaring an endpoint, and to get it directly with `errorBody()`.

**Comment by JakeWharton** [comment]
Since errors can come from applications, application servers, proxies, wifi portals, etc. there's no way to guarantee that the error format can be deserialized and now you have to deal with two errors at once. As such, we won't be providing this as a first-party feature.

You can, however, write it yourself in a custom CallAdapter that offers this behavior. I talk about it briefly here: https://youtu.be/t34AQlblSeE?t=3010.
