### ISSUE TITLE
@GET special characters not encoded

### ISSUE THREAD

**Issue by bsrAkdg** [square/retrofit#2156]
Response{protocol=http/1.1, code=400, message=Bad Request, url=https://foursquare.com/oauth2/access_token?grant_type=authorization_code&client_id=DBTS0TXLOE2TQRFQDZJRTHV4NHHN1E2FFJLOLILTCHCZPCOI&client_secret=3MZJ2UZ1IXTUY35TI4EPDZXEOUCMBGF5CMKKF1VAZDKEXP2M&redirect_uri=https://tr.linkedin.com/in/bsrakdg&code=WBXIGM44KUPGTXQAMKGFCFFECEDJSDWSG05VGMPWGWG0WNB5%23}

my url includes # character.  But retrofit 2.1 replaces it as %23. I dont want this issue. I used encoded = true but, it still replaces it. Do you have any idea about this ?

**Comment by pasali** [comment]
first of all you might want to update your issue description because your client id and secret are not so "secret" anymore. And then for your problem you can check this issue #1407

**Comment by JakeWharton** [comment]
Retrofit doesn't do URL encoding. That's done by the OkHttp library that Retrofit is built on. That said, the `#` character _must_ be encoded when present in a query parameter value since it would otherwise be treated as a delimiter for the URL fragment. Are you sure your code contains that character? I would try simply removing it since my guess is your redirect URL had an empty fragment on the end when you copied it.

**Comment by hellworld** [comment]
I don't want to do URL encoding with OkHttp library?And what should I do?

**Comment by TusharGogna** [comment]
How to handle this? With POST request,  we can do it using FormUrlEncoded but how to do it with GET request?
