### ISSUE TITLE
[Request] Add Synchronous Call Adapter

### ISSUE THREAD

**Issue by jaredsburrows** [square/retrofit#2186]
## Problem:

From Retrofit 1:

```java
interface Service {
   String someRequest();
}
```

For Retrofit 2, we are forced to use `Call` or some other call adapter such as `Observable` with RxJava/2 call adapters.

 ## Question:

See http://stackoverflow.com/a/35104080, can we add a synchronous call adapter?

**Comment by JakeWharton** [comment]
We very explicitly don't support this by default. `Call` was designed so that the interface could remain constant while allowing both synchronous and asynchronous invocation without needing the interface to change.

As the StackOverflow answer indicates, it's fairly easy to write your own adapter that provides the legacy behavior, although you miss out on things like the ability to cancel, see headers, get the response body, etc. These deficiencies plagued 1.x which is why we actively steer you away from it in 2.x.

**Comment by naturalwarren** [comment]
What's the advantage of doing this over just wrapping it in Call?
