### ISSUE TITLE
RxJava 2 Adapter: null may slip into RxJava

### ISSUE THREAD

**Issue by akarnokd** [square/retrofit#2242]
There was [a question on Stackoverflow](http://stackoverflow.com/questions/42624420/retrofit-2-with-rxjava2-and-plain-null-responses-error) recently which reported an unexpected `NullPointerException` caught by the one of the internal safeguards of RxJava 2.

Looks like `retrofit2.Response.body()` may return `null` which is handed over to RxJava 2 without validation in [BodyObservable](https://github.com/square/retrofit/blob/master/retrofit-adapters/rxjava2/src/main/java/retrofit2/adapter/rxjava2/BodyObservable.java#L51).

```java
@Test
public void responseBodyNull() throws Exception {
    
    Response<Integer> response = Response.success(null);
    
    Assert.assertNull(response.body());
    
    Class<?> clazz = Class.forName("retrofit2.adapter.rxjava2.BodyObservable");
    Constructor<?> c = clazz.getDeclaredConstructor(Observable.class);
    c.setAccessible(true);
    Observable<Integer> o = (Observable)c.newInstance(Observable.just(response));

    o.test()
    .assertNever(r -> r == null)
    .assertTerminated();
}
```

I don't know what the reasonably response to a `null` body could be:

  - complete the `Observable` without value or
  - signal a `NoSuchElementException`.

**Comment by naturalwarren** [comment]
I think it makes sense to complete the Observable. It's not really an error and if you've written a custom converter to return null when you've received an empty body (as JW described in #1554) this seems like the right behavior.

I could help out with a PR here. I've had trouble with backends returning empty response bodies and currently use a delegating converter to return null. This is going to cause troubles now that I'm moving to RxJava 2.

**Comment by JakeWharton** [comment]
I don't think there's any action to take here. A `null` body in the success (HTTP 2xx) case should warrant the use of `Observable<Response<Integer>>` in the Retrofit interface signature. 

Completing the stream without a value is definitely the wrong solution as it means the successful-but-empty response will go unprocessed due to the lack of actionable notification downstream onto which operators can be applied.

This is most strongly exemplified by the `Single<Integer>` case which more accurately represents an HTTP request. `Observable<Integer>` is just a variant of this where `onSuccess` is turned into the pair of `onNext`/`onComplete` calls (despite the implementation details actually being the reverse of this).

So there's three ways to handle this case:
 * Use `Observable<BodyType>` which indicates you expect to never receive `null` in the success case.
 * Use `Observable<Response<BodyType>>` which allows `null` bodies to be emitted inside the `Response<>` wrapper and handled accordingly.
 * Write a delegating `Converter` which transforms a `null` body into some other type which can abstract it (like `Optional<T>` such that you can use `Observable<Optional<BodyType>>`).

**Comment by JakeWharton** [comment]
We may want to add a first-party delegating converter that supports `Optional`...

**Comment by JakeWharton** [comment]
Optional converters released in 2.3.0

**Comment by iflove** [comment]
thanks

**Comment by sheaye** [comment]
@JakeWharton : Excuse me. You means that in release 2.3.0 we can solve the problem with the inner BuiltInConverters.VoidResponseBodyConverter ? But it seemes that the responseBodyConverter do not work when the status code is 204, I saw the code in the  OkhttpCall:
![qq 20170830184710](https://user-images.githubusercontent.com/26473649/29869185-8bc9e36e-8db4-11e7-95bf-97f6d6e5d033.png)
At last, forgive my English.

**Comment by JakeWharton** [comment]
Converters are `ResponseBody` --> `T` and we don't want them to have to understand `null`. What are you trying to solve?

**Comment by jiayouernv** [comment]
![1504870287 1](https://user-images.githubusercontent.com/5621486/30209806-72065812-94cc-11e7-95d3-b25fac528692.png)
I wish  if   response.body()    is   Null  ,   add a judgment   at  for   observer.onNext("stupid  Background developer");    this is   mine  ways of resolution .  because  nothing give my .

**Comment by jiayouernv** [comment]
I am very sad  for my  english .I'm your stupid monkey

**Comment by jiayouernv** [comment]
retrofit2.adapter.rxjava2. BodyObservable<T>

**Comment by davidbilik** [comment]
I have a one thing to note here, we needed to fork `BodyObserver` into our lib and we've converted it to Kotlin. If we use `Completable` type as return type in Retrofit interface, on this line https://github.com/square/retrofit/blob/master/retrofit-adapters/rxjava2/src/main/java/retrofit2/adapter/rxjava2/BodyObservable.java#L51 is the `response.body()` null and if we double bang it, it will throw an exception. I don't have such a deep knowledge of RxJava to know why it doesn't matter, its probably not checked inside onNext method and `.ignoreElements()` called later will hide this fact. We've solved it by sending info to BodyObservable if the type is `Completable` and if so, we call `observer.onComplete()` instead of `onNext`. Reference https://github.com/AckeeCZ/rxoauth/blob/master/retrofitadapter/src/main/java/cz/ackee/rxoauth/adapter/BodyObservable.kt#L42
