### ISSUE TITLE
Using @Url parameter with hardcoded query parameters

### ISSUE THREAD

**Issue by jrobinson3k1** [square/retrofit#2248]
Often times we have a known, hardcoded URL and variable parameters. There is also the case where we have a variable URL with known, hardcoded parameters. The current implementation does not allow you to define hardcoded query parameters while using the `@Url` annotation. For example:

```
@GET("?include=comments")
Call<Post> getPostComments(@Url String url);
```

This is not allowed because you cannot use both `@Url` and a defined `@GET` at the same time. The workaround is to use `@Query` and treat it as variable input.

My suggestion is to allow a defined `@GET` with `@Url` as long as it's only defining URL parameters.

**Comment by JakeWharton** [comment]
The problem here becomes how we build the full URL. We're currently using a
system like `<a href="">` which does all the heavy lifting. For this to
work we'd have to manually parse these query params.

I think we already do this in the normal static URL version though so we
likely have the code. I'll take a closer look when I get back from vacation.

**Comment by swankjesse** [comment]
Yep, the relative URL in `@GET()` would have been applied before the `@Url` parameter. We forbid it so you don’t specify a value that’ll always get clobbered.

The workaroud isn’t so bad; your caller needs to provide a string argument `"comments"` when calling the method.

```
    @GET
    Call<String> getPostComments(@Url String url, @Query("include") String include);
```

**Comment by swankjesse** [comment]
No action to take on this.
