### ISSUE TITLE
Retrofit 2.0.2 Doesn't Post Image

### ISSUE THREAD

**Issue by putraxor** [square/retrofit#2257]
I'm using Retrofit 2.0.2 for uploading image to server (using PHP). But it seems retrofit didn't post the form data since PHP can't trace $_FILES['gambar']['name'].

I'm sure that I've write correct codes for both client and server. Here it is my server code:

```
<?php
$path="uploads/".$_FILES["gambar"]["name"];
if(move_uploaded_file($_FILES["gambar"]["tmp_name"], $path)) {
    echo "Upload sukses ke $path";//success
} else {
    echo "Upload gagal ke $path";//fail
}
?>
```
This is my service interface:

```
public interface UploadService {
    @Multipart
    @POST("upload")
    Call<ResponseBody> upload(@Part MultipartBody.Part file);
}
```
And this is the code for uploading from client:

```
uploadService = new Retrofit.Builder()
                .baseUrl("http://10.0.2.2:8080")
                .client(client)
                .build()
                .create(UploadService.class);
File file = new File((filePath));

            RequestBody reqFile = RequestBody.create(MediaType.parse("multipart/form-data"), file);
            MultipartBody.Part body = MultipartBody.Part
                    .createFormData("gambar", file.getName(), reqFile);

            retrofit2.Call<okhttp3.ResponseBody> req = uploadService.upload(body);
            req.enqueue(new Callback<ResponseBody>() {
                @Override
                public void onResponse(Call<ResponseBody> call, Response<ResponseBody> response) {
                    Log.d("Response should be succeed");
                }

                @Override
                public void onFailure(Call<ResponseBody> call, Throwable t) {
                    t.printStackTrace();
                }
            });
```
I've also tried rest api using Postman and everything goes well.
There is no error in my codes, it's only retrofit doesn't post the form data. Am I miss something?

**Comment by JakeWharton** [comment]
Do you have an example HTTP request that you're trying to match? Or a failing test case per the issue template? Otherwise it's impossible to know what the problem is. Retrofit will be sending a multipart request with a single part named 'gambar' which is what you've instructed it to do so either there's a bug in Retrofit creating the request (unlikely), a bug in PHP processing the request (unlikely), or you're sending the data in the wrong format (likely). But without any idea of what format you're trying to achieve there's not a lot we can do here.

**Comment by putraxor** [comment]
Hi @JakeWharton  thanks for answering.
I have traced the request method through PHP and it showed  GET instead POST.
That is the problem, I thought something wrong with Retrofit itself since I've annotated as POST at the request interface.

**Comment by JakeWharton** [comment]
This happens when you server returns a 302 redirect instead of a 307 redirect. With a 302 the client cannot retry the upload of the body. This is why HTTP 307 was added which indicates the client should retry the upload without changing the HTTP method.

If you cannot change your server, the easiest way to fix this is to massage any 302 codes into a 307 using an [OkHttp network interceptor][1].

 [1]: https://github.com/square/okhttp/wiki/Interceptors
