### ISSUE TITLE
onResponse not getting called when using Authenticator

### ISSUE THREAD

**Issue by iAlex97** [square/retrofit#2263]
I'm using Retrofit 2.2.0 and I'm calling an API that uses simple http authentication.

I did a little bit of digging and found out that Authenticator is the way to go and the call itself works.
The only problem that I'm facing is that the `onResponse` method never gets called.

My guess is that Retrofit makes the first call without the authenticator and gets a `HTTP FAILED: java.net.ProtocolException: Too many follow-up requests: 21` and then uses the authenticator and gets a `200 OK` response, but fails to call `onResponse`

**Comment by JakeWharton** [comment]
Retrofit doesn't have an Authenticator, you're probably referring to the one inside of [OkHttp][1]? The too many redirects exception indicates you're causing a redirect loop with your authenticator and never actually receiving a 200. I would suggest trying to get the request to work using OkHttp directly before using it in Retrofit as that's where the problem lies.

 [1]: https://github.com/square/okhttp
