### ISSUE TITLE
Callback not on UI thread

### ISSUE THREAD

**Issue by shenliuyang** [square/retrofit#2282]
retrofit init:

```java
@Singleton
	@Provides
	public Retrofit provideRetrofit() {
		//TODO baseUrl may provided by repository
		String baseUrl = "http://www.bing.com/";
		return new Retrofit.Builder().baseUrl(baseUrl).addConverterFactory(ScalarsConverterFactory.create())
				.addConverterFactory(GsonConverterFactory.create())
				.addCallAdapterFactory(Java8CallAdapterFactory.create()).build();
	}
```

```java
@OnClick(R.id.submit)
	public void submit(Button button){
		Log.d("appsugar","click thread is "+Thread.currentThread());
		searchRepository.search("my love").thenAccept(
				e->{
					Log.d("appsugar","response thread is "+Thread.currentThread());
					button.setText(e.substring(0,6));
				});
	}
```
cat log is 
04-14 08:38:35.229 3287-3287/org.appsugar.android.archetypes D/appsugar: click thread is Thread[main,5,main]
04-14 08:38:35.233 1362-1403/? W/audio_hw_generic: Not supplying enough data to HAL, expected position 247765 , only wrote 247680
04-14 08:38:35.806 3287-3551/org.appsugar.android.archetypes D/appsugar: response thread is Thread[OkHttp http://www.bing.com/...,5,main]

**Comment by Philipp91** [comment]
I believe this should be re-opened. On Android with `Java8CallAdapterFactory`, the callback happens on the network thread. As far as I can tell, there is no easy way to make the `Java8CallAdapterFactory` work with the `ExecutorCallAdapterFactory`, which calls the `MainThreadExecutor` to execute callbacks on the UI thread.

**Comment by JakeWharton** [comment]
Using a CallAdapter to return anything but a built-in type (i.e., Call)
will likely alter the threading semantics.

You can write your own delegating call adapter that takes the type you want
(presumably CompletableFuture), delegates to the normal implementation, and
then takes the resulting instance and uses its API to change the callback
thread. This is similar to the sample for RxJava which applies
observeOn(AndroidSchedulers.mainThread()) to all returned Observables which
is included in the samples.

This cannot be done by default because there'd be no way to disable it.

**Comment by Philipp91** [comment]
Ok thanks. I now did [this](https://pastebin.com/FtMpCnVS). Let me know if the solution you proposed could look significantly more elegant (i.e. not duplicating all the code of `Java8CallAdapterFactory`). I couldn't find a modifier method similar to `observeOn` for the `CompletableFuture` class.

**Comment by JakeWharton** [comment]
I'll have to research it myself tomorrow. I'm a CompletableFuture noob.

**Comment by JakeWharton** [comment]
Looks like you have to do: thenApplyAsync(Function.identity(),
callbackThreadPool)

**Comment by Philipp91** [comment]
Thank you!
