### ISSUE TITLE
Issue when uploading an image using Retrofit 2.1.0

### ISSUE THREAD

**Issue by ankitkumar-webonise** [square/retrofit#2296]
What kind of issue is this?

 I am trying to upload image using multipart. When I upload image using multipart ,in response it's giving success response. But on server I am not getting any file.

My Request:
File file = new File(getPath(cropUriImage));
        RequestBody requestBody = RequestBody.create(MediaType.parse("*/*"),file);
        MultipartBody.Part imageToUpload = MultipartBody.Part.createFormData("profile_image",file.getName(),requestBody);

Call<DefaultModel> call = apiServiceInterface.UploadProfilePicFeed(filePart);
        call.enqueue(new Callback<DefaultModel>() {
            @Override
            public void onResponse(Call<DefaultModel> call, Response<DefaultModel> response) {
                FlashbackFeeds.this.onSuccess(response);
            }

            @Override
            public void onFailure(Call<DefaultModel> call, Throwable t) {
                FlashbackFeeds.this.onFailure(t);
            }
        });

My Service:
@Multipart
    @POST(Constants.URL.UPDATE_PROFILE_PIC)
    Call<DefaultModel> UploadProfilePicFeed(@Part MultipartBody.Part filePart);

**Comment by JakeWharton** [comment]
This isn't a bug in Retrofit. You are either creating your request in a way that the server doesn't expect (and it incorrectly returns success instead of failure) or there is a problem saving the image on the server-side. Consult with your server team or the API documentation for what the request should look like and compare that with something like Charles Proxy or OkHttp's logging interceptor.

There's no action for Retrofit to take here though.
