### ISSUE TITLE
retrofit2 +and / Escape String

### ISSUE THREAD

**Issue by sujiewen** [square/retrofit#2317]
@FormUrlEncoded
@POST("/app/lotteryyLottery")
Call<Bean> getPostBuyLottery(@FieldMap(encoded = true) Map<String, Object> map);

ios 

appId=app&betType=3%E4%B8%B21&buildversion=1&lotteryId=ZQHH&money=4800&multiple=1&payofftc=0&planNums=JQS%4020170509-002%3A%5B3%2C7%2B%5D/SPF%4020170509-001%3A%5B%E8%83%9C%2C%E5%B9%B3%2C%E8%B4%9F%5D/RQSPF%4020170509-003%3A%5B%E8%B4%9F%2C%E5%B9%B3%2C%E8%83%9C%5D/SPF%4020170509-003%3A%5B%E8%B4%9F%5D&sign=00333135926c5a19e7df849e2cab6f25&stime=1494319389248&type=ZG&userId=10515&version=1.0.0

android
appId=app&betType=3%E4%B8%B21&buildversion=1&lotteryId=ZQHH&money=4800&multiple=1&payofftc=0&planNums=JQS%4020170509-002%3A%5B3%2C7+%5D%2FSPF%4020170509-001%3A%5B%E8%83%9C%2C%E5%B9%B3%2C%E8%B4%9F%5D%2FRQSPF%4020170509-003%3A%5B%E8%B4%9F%2C%E5%B9%B3%2C%E8%83%9C%5D%2FSPF%4020170509-003%3A%5B%E8%B4%9F%5D&sign=00333135926c5a19e7df849e2cab6f25&stime=1494319389248&type=ZG&userId=10515&version=1.0.0

android is error?!

**Comment by sujiewen** [comment]
{"appId":"app","betType":"3串1","buildversion":"1","lotteryId":"ZQHH","money":4800,"multiple":1,"payofftc":0,"planNums":"JQS@20170509-002:[3,7+]/SPF@20170509-001:[胜,平,负]/RQSPF@20170509-003:[负,平,胜]/SPF@20170509-003:[负]","stime":"1494319389248","type":"ZG","userId":"10515","version":"1.0.0"}

**Comment by JakeWharton** [comment]
Hmm I can't spot the difference if there is one.

Form encoding is handled by [OkHttp's `FormBody`][1] class. Retrofit has no control over the encoding. If you think there's a bug in the encoding you can file a bug against OkHttp. You should include a reference to the HTTP specification on form encoding which backs up your claim, though, since the implementation is based on the spec.

 [1]: https://square.github.io/okhttp/3.x/okhttp/okhttp3/FormBody.html
