### ISSUE TITLE
Allowing authenticator to react to user-defined HTTP errors

### ISSUE THREAD

**Issue by Mordag** [square/retrofit#2378]
While using the latest version of retrofit (2.3.0) inside my project, I got the idea to allow authenticators to match any possible HTTP error which is set by the user for that specific instance. I definitively like the approach of authenticators in general but for example my web service is throwing a 403 when the token (session) is not valid anymore. Currently authenticators are only reacting to 401 HTTP errors, is that right? So it would be great to react to even that case using that solution. Any thoughts?

**Comment by JakeWharton** [comment]
Retrofit does not have an authenticator. Perhaps you wanted to ask on OkHttp?

That being said you can use an OkHttp interceptor for any arbitrary logic to retry based on HTTP error code. Just be sure to use an application interceptor and not a network interceptor so that you're allowed to make multiple requests.

**Comment by tranktechnologies** [comment]
@JakeWharton I am using a service which gives 403 and I have implemented token refresh in 403 via interceptor but the problem is if request again fails interceptor does not re run.
