### ISSUE TITLE
@QueryName doesn't encode "/" (slash) to %2F

### ISSUE THREAD

**Issue by ildar2** [square/retrofit#2384]
I have a string:
`FGgOzxaG07UTP0T39t71IDCJFzwyj9QaiofNK3M5ZGr0tgpVOXWVI3N3Yz4JSTWktle+MMukcV/znss5qORMWQ==`
it should look like this in url:
`FGgOzxaG07UTP0T39t71IDCJFzwyj9QaiofNK3M5ZGr0tgpVOXWVI3N3Yz4JSTWktle%2BMMukcV%2Fznss5qORMWQ%3D%3D`
instead it looks like this:
`FGgOzxaG07UTP0T39t71IDCJFzwyj9QaiofNK3M5ZGr0tgpVOXWVI3N3Yz4JSTWktle%2BMMukcV/znss5qORMWQ%3D%3D`

while "+" and "=" get encoded properly, "/" doesn't

this means, i can't use api, which uses encoded xml strings

I guess, I should encode it manually and use (encoded = true) property, right?

**Comment by JakeWharton** [comment]
The / character is valid in a query value since which is why it isn't
encoded. This is consistent with what major browsers do as well.

If you're API absolutely requires this, you should file a bug on them
first, but then second you can encode the query yourself and then use
encoded=true as you said.

**Comment by shily** [comment]
The server in our company can't accept the "/" char in query value, so I have to use addEncodedQueryParameter

`
import java.net.URLEncoder;
  
  String token = getToken();
  commonParams.addEncodedQueryParameter(KEY_TOKEN, URLEncoder.encode(token, "UTF-8"));
`
