### ISSUE TITLE
BaseUrl with parameters doesn't work.

### ISSUE THREAD

**Issue by ParadiseHell** [square/retrofit#2410]
I have a url like **http://example/?a=b&b=c** ,which I want to make it to be retrofit's baseUrl,But when I log the request info in the interceptor,I got **http://example/**

**Comment by JakeWharton** [comment]
That's correct. This is by design. Retrofit's relative URLs work like `<a href="">`. When you're on `http://example/?a=b&b=c` and click a link for `/` you get `http://example/`. If you want persistent query parameters, you should add them in an OkHttp interceptor as URL constant additions instead of as part of the base URL.
