### ISSUE TITLE
Multipart not working with Kotlin

### ISSUE THREAD

**Issue by ngochuu90** [square/retrofit#2412]
**in ServiceApi.java**: Everything works very well
```
  @Multipart
  @POST(FUNCTION_POST_PRODUCT)
  Flowable<ServerResponse<ProductBean>> postProduct(
      @PartMap Map<String, RequestBody> partMap,
      @Part List<MultipartBody.Part> files);
```

But when I convert to kotlin, callback is not triggered. I do not get any error log
```
  @Multipart
  @POST(FUNCTION_POST_PRODUCT)
  fun postProduct(
      @PartMap partMap: Map<String, RequestBody>,
      @Part files: List<MultipartBody.Part>): Flowable<ServerResponse<ProductBean>>
```

**Comment by JakeWharton** [comment]
Can you define "not working" more, preferably with a test case per the
issue template.

**Comment by luiztorres** [comment]
I'm having the same issue here. I have tried to implement the same thing but using HttpURLConnection, and the error is still happening.

@JakeWharton When he said "not working" is because nothing happen, no response. When I tried with the HttpURLConnection I received a 504 error after a certain time, the same in Retrofit.

I'm using Kotlin with Retrofit 2.3.0 and okhttp 3.8.1.

Do you think it can be a error with kotlin?

**Comment by luiztorres** [comment]
I solved the issue.

I had to change the header property `Accept` to `*/*`.
