### ISSUE TITLE
Retrofit enqueue methods not being called

### ISSUE THREAD

**Issue by dilonne** [square/retrofit#2422]

**Comment by dilonne** [comment]
Im making an asynchronous call, im able to send a request to the server and getting my desired JSON(using postman) but for some reason the OnResponse and OnFailure methods are not being executed.

**Comment by dilonne** [comment]
I finally got the cause, I had another method which was interfering with my request, everything works perfectly now.

**Comment by charmainewee** [comment]
Hi, I hope you don't mind me asking, how did you manage to solve it? I mean, how did you know another method was interfering with your request? 

I'm facing the same problem (everything works fine until I try to implement a lazy loading function for my recyclerView), and I don't know where to start, or how to tell if its because of an interfering method!
