### ISSUE TITLE
Application getting crashed giving following error A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0xf8ef7f29 in tid 19272 (OkHttp Dispatch)

### ISSUE THREAD

**Issue by shunishya** [square/retrofit#2446]
this is the only log im getting as crash log

A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0xf8ef7f29 in tid 19272 (OkHttp Dispatch)

can you please help. Im doing anything wrong?

**Comment by JakeWharton** [comment]
Retrofit doesn't have any nor interact with any native code so it cannot cause a SIGSEGV. Based on the thread name, this happened on an OkHttp dispatcher thread which also doesn't have any native code but does interact with some. The problem is likely deep inside Android in the SSL stack, but there isn't anything Retrofit or OkHttp can do about it. You should gather more information than the single line of text used to create this issue and file a bug on Android's bug tracker.

**Comment by shunishya** [comment]
sure thanks for the reply..
