### ISSUE TITLE
Use the @POST request , but  Charles capture, using GET request

### ISSUE THREAD

**Issue by zdongcoding** [square/retrofit#2455]
@POST("user/snsLoginCallback")
@FormUrlEncoded
Observable<BaseEntity<LoginEntity>> snsLoginCallBack(@FieldMap Map<String, String> map);

![image](https://user-images.githubusercontent.com/8479883/29344845-458010a6-826d-11e7-862e-6b3f0f08bb6a.png)

**Comment by swankjesse** [comment]
Executable test case? My guess is you're being redirected.

**Comment by zdongcoding** [comment]
@swankjesse  not redirected ,  Low probability of occurrence

**Comment by JakeWharton** [comment]
Without a test case or reproducible sample it's impossible to know. I can say, though, with a really high degree of confidence that Retrofit isn't changing the request method. This likely happens at some lower layer (like OkHttp) either in an interceptor or as the result of a redirect.

If you're able to write an executable test case or sample we can take a look, but otherwise there's no action to take here.
