### ISSUE TITLE
Passing an object as a Get request

### ISSUE THREAD

**Issue by GaniduAsh** [square/retrofit#2456]
I have a request and its GET and its mentioned as following, 

http://SERVERV4/product/859257-0014/0/222D71B7-1BAA-4C89-AEFE-E05703F86E47/recommendations?currency=GBP&gender=woman&maxNumberOfProducts=4

So the @Path and @Querry  should be use in-order to make it work ,  so my question is how i directly map an object to this, lets i have a kotlin data class as below 

data class RecommendedProduct(
        @Path("sku")val sku: String,
        @Path("customerId")val customerId: String,
        @Path("sessionId") val sessionId: String,
        @Query("currency")val currency: String,
        @Query("gender") val gender: String,
        @Query("maxNumberOfProducts") val maxNumber: Int
);

is it possible that i can map this directly

**Comment by ris58h** [comment]
@GaniduAsh It's not possible out of the box but you could implement your own retrofit2.Converter and retrofit2.Converter.Factory.

**Comment by JakeWharton** [comment]
I investigated this nearly 5 years ago prior to 1.0 and we decided against this approach. The problem is that this fundamentally changes the behavior of the library to act more like an object serializer than an interface method binder and the complexity goes way up. The other part we weren't comfortable with was that these objects would turn Retrofit much more into a request/response arbiter instead of a higher-level abstraction.

So at this time we have no plans for this functionality. That being said, #626 would probably allow you to do this but we haven't decided to implement it yet.
