### ISSUE TITLE
Get response code in onFailure

### ISSUE THREAD

**Issue by abbasiehsan1991** [square/retrofit#2477]
Hello .
I am using retrofit to get some data from my server. in the server when I send a request that is acceptable I will get 200 from a server with a JSON in response.
but when my request is not acceptable, I will get 208 from the server with a null body.
in the case with a null body 'onFailure' will works. How can I Know what is 'onFailure' response code in this method?
Thank you.

**Comment by JakeWharton** [comment]
I don't quite follow. If your server can return a 208 which has a 0-byte
body then you should account for this in the serialization part of your
configuration. By default most of the parsers are fairly strict, but you
can either configure the serialization library you're using to allow this
or you can write a custom Converter which checks for an empty body and
returns null or otherwise delegates to the real one.

You cannot access the response in onFailure because it means that you
either got a transport (aka network) error and there was no response or the
parsing of the response failed in an unrecoverable way.

**Comment by JakeWharton** [comment]
Here's an example I wrote before: https://github.com/square/retrofit/issues/1554#issuecomment-178633697
