### ISSUE TITLE
Batch support, multipart batching

### ISSUE THREAD

**Issue by OleksandrKucherenko** [square/retrofit#2525]
Feature Request. For optimizing rest api calling in javascript world was developed extension "batching of request". In short its a specially composed multi-part request that in each part contains a request to a specific web API method.

More details: https://medium.com/@mustafa.ileri/optimize-your-rest-api-with-http-multipart-batched-request-b7a060f77e40

Will be great to have support of this feature. It will allow to optimize number of calls to web API.

**Comment by JakeWharton** [comment]
This is a non-standard multipart content type and thus is unsupported by the OkHttp multipart support that Retrofit relies on. If you want to use this, you can create your own `RequestBody` subclass which encodes the multipart batch content type to its specification.

Beyond that, HTTP/2 is a much better option (which is already supported by OkHttp) because it reduces the overhead of multiple API calls to near zero and actually offers benefits that multipart batch cannot such as interleaving and not blocking requests and responses on the slower participant.
