### ISSUE TITLE
Retrofit Mock - Easy integration

### ISSUE THREAD

**Issue by rafa0809** [square/retrofit#2562]
Hi!
I'm not sure if I understand the target of the _RetrofitMock_. Moreover the testing purposes, it would be pretty cool to use Retrofit arround the app without care about is we are using the mock or real Retrofit.

Let me show you an example:

Anywhere in you app code:

`
GitHubService service = AppComponentsFactory.create().getRetrofit().create(GitHubService.class);
`

So that the _AppComponentsFactory_ decides if provides us a real or a mock Retrofit.

```
public class AppComponentsFactory {

    public static AppComponentsFactory create() {
        return new AppComponentsFactory ();
    }

    public Retrofit getRetrofit() {
        Retrofit retrofit = new Retrofit.Builder()
                .baseUrl(BuildConfig.API_ENDPOINT)
                .addConverterFactory(GsonConverterFactory.create())
                // Any other customization here
                .build();
        if (BuildConfig.MOCK_HTTP_REQUESTS){
            retrofit = new MockRetrofit.Builder(retrofit)
                    .networkBehavior(NetworkBehavior.create()).build();
        }
        return retrofit;
    }
}
```

Where's the current problem? We need both MockRetrofit and Retrofit implement some common abstraction to be transparent. This cannot be posible right now.

The simplest solution comes to my mind is just add the following interface, so both Retrofit and MockRetrofit implement it:

```
public interface RetrofitServiceFactory {
    public <T> BehaviorDelegate<T> create(Class<T> service);
}
```

This way, the AppComponentsFactory would look more like this: 

```
public class AppComponentsFactory {

    ...

    public RetrofitServiceFactory getRetrofit() {
        // Choose the Mock, Real or even Custom retrofit!
    }
}
```
I'm implementing a kind of wrapper that contains the convenient instance for each case and delegates the service creation to them, so I have a "common interface" to be used around the app, but I get the impression this is a more common issue and can be generalized by this way.

What are your thoughts on this? Is there any solution to this currently? 

Thanks in advance!

**Comment by JakeWharton** [comment]
The solution is inversion of control. Anywhere you need a `GitHubService` the code should accept and instance rather than eagerly fetch one.

For example, in the u2020 app [we use dependency injection to retrieve an instance](https://github.com/JakeWharton/u2020/blob/68a5f3109ee585df276b3f541fdef31360331433/app/src/main/java/com/jakewharton/u2020/ui/trending/TrendingView.java#L63) and allow someone else to decide what instance fulfills that request. It can be backed by a real implementation from Retrofit, a mocked implementation for unit tests, or a Mock Retrofit implementation for UI tests. The point is that the consumer doesn't have to care what the instance is or where it comes from.
