### ISSUE TITLE
Retrofit POST request converts into GET request when URL have “?” inside

### ISSUE THREAD

**Issue by pranavpari** [square/retrofit#2711]
Retrofit converts POST in GET request when URL is like this

https://www.example.com/index.php?route=api/account/login

**Comment by JakeWharton** [comment]
This is extremely unlikely. What's more likely is your HTTP server is returning an HTTP 303 instead of 307 forcing the HTTP client, OkHttp, to issue a GET request for the follow-up request rather than reply the POST.

If you believe it's Retrofit that's actually causing this behavior, please provide a failing test case.
