### ISSUE TITLE
Please Help! I want to decode response by use a custom ConverterFactory but after a decode the response something got wrong.

### ISSUE THREAD

**Issue by ironman6121** [square/retrofit#2744]
Retrofit retrofit = (new Retrofit.Builder())
                .client(client).baseUrl(baseUrl)
//                .addConverterFactory(ScalarsConverterFactory.create())
                .addConverterFactory(DecodeConverterFactory.create())
                .addCallAdapterFactory(RxJava2CallAdapterFactory.create()).build();
        return retrofit;

public class DecodeResponseBodyConverter<T> implements Converter<ResponseBody, T> {
    private final TypeAdapter<T> adapter;

    DecodeResponseBodyConverter(TypeAdapter<T> adapter) {
        this.adapter = adapter;
    }

    @Override
    public T convert(ResponseBody value) throws IOException {

        String response = Authcode.Decode(value.string());

        return adapter.fromJson(response);
    }
}

the error is :
Decode ResponseBodyConverter Method threw 'java.lang.IllegalStateException' exception.

**Comment by JakeWharton** [comment]
There is far too little information here to be able to diagnose any kind of problem. But since this is a question and not a bug report or feature request, posting to StackOverflow with the 'retrofit' tag is much more suitable. When you do so, please provide more information, ideally enough such that it's easy to reproduce the behavior you are seeing.
