### ISSUE TITLE
Callback cannot be resolved with Gradle 3.1.2

### ISSUE THREAD

**Issue by alexander-fischer** [square/retrofit#2752]
After upgrading to Gradle version 3.1.2 from Gradle 2.x.x, `retrofit2.Callback` cannot be resolved. I use Retrofit in a submodule that is added like this: 
`api project(path: ':sdk', configuration: 'default')`

The retrofit dependency is added like this: 
`api "com.squareup.retrofit2:retrofit:2.4.0"`

My error message is:
`Supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath:
    class ***, unresolved supertypes: retrofit2.Callback`

I tried everything like resetting the Gradle cache etc. Please add support for Gradle 3.1.2.

**Comment by JakeWharton** [comment]
Retrofit doesn't know anything about your build system. The jar we publish contains that class, so the problem lies in the configuration of your build system and not something with Retrofit itself. The most likely candidate is something relating to the fact that the Retrofit jar isn't being included on the classpath of the project which produces the error.
