### ISSUE TITLE
Getting "Unresolved reference" when compileSdkVersion is set to 'android-P'

### ISSUE THREAD

**Issue by jerryc05** [square/retrofit#2779]
I am getting "Unresolved reference" on [retrofit2, Callback, onResponse, Call, Response, onFailure, GET, QueryMap, POST, Body, okhttp3, Retrofit, GsonConverterFactory, OkHttpClient, Interceptor and even LeakCanary(I knew it is outside of this project)] when I upgrade compileSdkVersion from 27 to 'android-P' and use androidx library.  Any way to fix those? Thx

**Comment by JakeWharton** [comment]
You should file a bug on whichever tool is giving you that error, presumably Android Studio? This isn't related to Retrofit as evidenced by the fact that it happens with multiple libraries and only occurs when you change the build configuration specific to your app. We aren't going to be able to provide any help here because it's something build system and/or IDE-specific.
