### ISSUE TITLE
run报错，build不会，okio？

### ISSUE THREAD

**Issue by PengHesheng** [square/retrofit#2784]
Program type already present: okio.AsyncTimeout$Watchdog
Message{kind=ERROR, text=Program type already present: okio.AsyncTimeout$Watchdog, sources=[Unknown source file], tool name=Optional.of(D8)}

![image](https://user-images.githubusercontent.com/24489804/41188390-e221ba16-6bee-11e8-8a32-0a69f341020a.png)

Android Studio 3.1.3，Kotlin开发
![image](https://user-images.githubusercontent.com/24489804/41188418-3edcf658-6bef-11e8-8fd1-7fc7d19a3e24.png)

**Comment by PengHesheng** [comment]
Android Studio 3.1.3，Kotlin开发

**Comment by JakeWharton** [comment]
This occurs when okio is being included twice which doesn't really have anything to do with retrofit but more in your local build system. Since okio is a transitive dependency of okhttp which is a transitive dependency of this library, Gradle will take care to only ever add one copy. So you likely have another copy somewhere, perhaps as a jar, that is also being included. This is entirely specific to your build setup so you'll just have to explore until you find it. There's no action for us to take though.
