### ISSUE TITLE
Add support for OkHttp's request tags

### ISSUE THREAD

**Issue by FCBXavi** [square/retrofit#2812]
I want to cancel all request for Activity or Fragment  during the end of their life style. In OkHttp, I can use Request.Builder.setTag method to setTag for every Request.
 
And then, in my client, I add this method:

    public static void cancelRequest(Object tag) {
        if (tag == null) {
            return;
        }
        List<Call> queuedCalls = mClient.dispatcher().queuedCalls();
        for (Call call : queuedCalls) {
            if (tag.equals(call.request().tag())) {
                call.cancel();
            }
        }
        List<Call> runningCalls = mClient.dispatcher().runningCalls();
        for (Call call : runningCalls) {
            if (tag.equals(call.request().tag())) {
                call.cancel();
            }
        }
    }
And in BaseActivity and BaseFragment's onDestroy method, I can do this:

    APIRestClient.cancelRequset(this);    

I think it's useful and convenient.
But in Retrofit, I can't use field tag. So how can I do above in Retrofit efficiently and can you give me some suggestions？ Thanks！😊

**Comment by anandwana001** [comment]
Have a look at this [issue](https://github.com/square/retrofit/issues/2394)

**Comment by JohNan** [comment]
+1

I have a use case where a custom header wont do it as suggested in the linked issue. I just wanted to share my use case to hopefully bump this a bit :)

My initial request goes through an Interceptor to add a Authorization header based on a value (now set as a custom header). If the API respons challenges the authorization I catch it in an Authentication interceptor to request a new token based on the same initial value.

If I use a custom header I wont be able to remove it in the first Interceptor because it _might_ be needed in the Authentication interceptor to generate a new token. Hence it will be sent along to the API if the authorization was successful in the first place.

Using a tag would solve this since it wont be passed to API like a header is.

**Comment by JakeWharton** [comment]
Yeah this is a planned feature
