### ISSUE TITLE
javax.net.ssl.SSLException:

### ISSUE THREAD

**Issue by muhammad-umair-khan** [square/retrofit#2824]
Server side has used Let's Encrypt cert and i am frequently getting `javax.net.ssl.SSLException: Read error: ssl=0x7b5e1e8980: I/O error during system call, Connection reset by peer` error on all Android versions 5.1, 6.0, 7.1, 8.0. Please provide me some solution to this problem. iOS is not creating any issue. But Android is not working. I am using retrofit 2.4.

**Comment by JakeWharton** [comment]
TLS happens at a layer below Retrofit inside of OkHttp. You will experience the same exception if you invoke OkHttp directly. As a result, we at the Retrofit layer have no control over this but also we're unequipped to even guide you on the right path. If you can phrase the problem in the form of a bug such that you believe OkHttp is doing something wrong you can file a bug on its issue tracker. Otherwise StackOverflow and its 'okhttp' tag is monitored and is a good place for troubleshooting issues of configuration which are not necessarily bugs in the library.
