### ISSUE TITLE
retrofit not get byte array 

### ISSUE THREAD

**Issue by kecoli2** [square/retrofit#2828]
Hi ,
I use wcf service mine method return one object (Model.cs) model.cs in 
public string Name {get;set;}
public string Surname {get;set;}
public byte[] foto1 {get;set;}
public byte[] foto2 {get;set}

property.
Retrofit get object no seriliaze end response time very log but IOS alamofire no problem.
I want the object not stream

**Comment by JakeWharton** [comment]
Retrofit doesn't know anything about how your model is deserialized. The functionality is delegated entirely to your chosen converter and if you are having problems with deserialization of a byte array you'll have to figure out how to reconcile that with whichever converter you are using.

For example, JSON has no mechanism for representing bytes. All kinds of ugly hacks like Base64-encoding them are used but it's unlikely that your JSON library (if you are using JSON) handles that automatically and so you'll have to register a custom deserializer so that it's supported. Contrast that to something like protocol buffers which support byte arrays natively.

**Comment by kecoli2** [comment]
Thanks
But do you know one example
