### ISSUE TITLE
failed to rename

### ISSUE THREAD

**Issue by ningjiaqi** [square/retrofit#2973]
failed to rename /data/user/0/cn.mdruby.doctork/cache/cache/49351138fef726a2c1805e1851e29003.1.tmp to /data/user/0/cn.mdruby.doctork/cache/cache/49351138fef726a2c1805e1851e29003.1

Cache Problem? What's wrong? Please help me!

**Comment by JakeWharton** [comment]
Retrofit doesn't have a cache. OkHttp, the default HTTP client Retrofit uses, has a disk cache though. Without more information what the actual underlying problem is will be impossible to discern, but there's nothing that Retrofit can do here because OkHttp's cache is entirely opaque as far as its concerned.
