### ISSUE TITLE
Include ANNOTATION_TYPE as target for annotations

### ISSUE THREAD

**Issue by hmartinezd** [square/retrofit#3006]
I'm implementing a wrapper to isolate retrofit from the rest of my code. Of course the intention here is to no have Retrofit dependencies all over my projects. 
So far I created my custom adapter and with that I have removed most Retrofit dependencies, except Annotations. I still need to use Retrofit Annotations or it won't work at all, of course. 
Here my request will be to allow the annotations to be applied to other annotations, that way I can create my custom annotations, and use those instead of Retrofit ones. 

For example, the Body annotation, change the line:
`@Target(PARAMETER)`

To this:
`@Target({PARAMETER, ANNOTATION_TYPE})`

Needless to say I would help with the changes if the team agrees. 
Thanks

**Comment by JakeWharton** [comment]
Just to make sure I follow, you're proposing that we allow every annotation to also target other annotations and then changing the implementation to look for any annotation which is annotated with one of our annotations?

**Comment by hmartinezd** [comment]
Well, at first I thought it could be as easy as "instance of". Didn't think it very thru I guess. The real option seems to be something like what you mention. 
I wrote and tested this helper method that could say if one annotation is annotated with an specific annotation class. 

`private boolean isTypeAnnotation(Class type, Annotation annotation) {
        for (Annotation anno : annotation.annotationType().getAnnotations()) {
            if ((anno.annotationType() == type)) {
                return true;
            }
        }
        return false;
    }`

**Comment by JakeWharton** [comment]
I'm not really convinced that this is something we want to support. You're trying to encapsulate Retrofit but without actually guarding yourself against future breaking changes. If we release a new major version with new annotations and different parameter and return type restrictions or mechanisms then you're not guaranteed to be insulated. Proper encapsulation should mean that you can remove Retrofit and replace it with OkHttp directly or some other HTTP client like Ktor.

If you want an annotation-based approach like Retrofit then perhaps you should use an annotation processor to code-generate the Retrofit interfaces based on your annotations. Or since you likely are restricting the feature set just use `Proxy` yourself and delegate directly to OkHttp with your chosen serialization library and async execution mechanism.

I'm happy to hear more arguments for supporting this to try and change my mind but for now I'm going to close this feature request.
