### ISSUE TITLE
Retrofit 2.5.0 Upload File Error

### ISSUE THREAD

**Issue by HalyangDream** [square/retrofit#3030]
[Retrofit2.5.0Bug.txt](https://github.com/square/retrofit/files/2878099/Retrofit2.5.0Bug.txt)
Error Info:
java.lang.IllegalArgumentException: 
  at okhttp3.Headers.checkValue (Unknown Source:59)
  at okhttp3.Headers.of (Unknown Source:53)
  at okhttp3.MultipartBody$Part.createFormData (Unknown Source:37)
  at okhttp3.MultipartBody$Builder.addFormDataPart (Unknown Source)

 Error Phone Info:
Android Version: Android 8.0 ,Android 8.1,Android 5.1
Android Brand: Samsung
Android Model: Galaxy A7 (2018) (a7y18lte)，Galaxy J8(j8y18lte) ,Galaxy  One7 Prime(on7xreflte), Galaxy S8+ (dream2lte),Galaxy J2 (j2lte)

**Comment by JakeWharton** [comment]
The code is failing in OkHttp, likely because your filename contains characters which are invalid for use in a header. This was fixed in OkHttp by https://github.com/square/okhttp/pull/4584 and released in version 3.13.1. If you upgrade your OkHttp you shouldn't see this crash anymore, and if you do please file a bug on OkHttp.
