### ISSUE TITLE
Simplexml is deprecated but cannot use JAXB ?

### ISSUE THREAD

**Issue by SAGARSURI** [square/retrofit#3056]
Today I was looking at the `simplexml` converter. Since it is deprecated and is recommended to move to `JAXB` as mentioned in the README. But when I saw the `JAXB` converter's README file it's saying not to use in Android as it wont work. So what is the solution for XML serialisation and deserialisation using retrofit?

**Comment by JakeWharton** [comment]
That's up to you. Retrofit can work with any serialization framework you choose. It's just that we no longer provide a first-party converter that works on Android for XML. Although that's not even true since you can still use the Simple one, we just plan to remove it in the next major version. There may be other converters for XML listed on the wiki created by the community. Otherwise it sounds like there's room for one to be made if you're interested.

**Comment by SAGARSURI** [comment]
Thanks for the info @JakeWharton
