### ISSUE TITLE
[Question] Optional with CompletableFuture?

### ISSUE THREAD

**Issue by RaviH** [square/retrofit#3081]
Hello,

I am using retrofit 2.5.0 and have an API like:

`CompletableFuture<Optional<String>> getCustomer(int customerId)`

But the response is null instead of Optional.empty().

Here's my retrofit builder:

```
new Retrofit.Builder()
                .baseUrl(getBaseUrl())
                .addConverterFactory(new NullOnEmptyConverterFactory())
                .client(getOkHttpClient(getOAuthInterceptor(decrypter())))
                .addCallAdapterFactory(RxJava2CallAdapterFactory.create())
                .addConverterFactory(ScalarsConverterFactory.create())
                .addConverterFactory(create(objectMapper))
                .build();
```

**Comment by JakeWharton** [comment]
What's the HTTP response code you're getting?

**Comment by RaviH** [comment]
204 No Content

**Comment by JakeWharton** [comment]
Damn, ok. This is #2867. There's a PR for a proposed fix but I haven't had time to look at it yet. We definitely need to figure something out for this.

**Comment by RaviH** [comment]
Thanks Jake.

a. What are you leaning towards? I don't think 204 is an error as the person who made the PR is recommending. So a null or Optional.empty() makes more sense to me.

b. Until then what's the best way to approach this? Also, I had to add `NullOnEmptyConverterFactory` to handle null. Seems like a hack to me.

What's the best approach in general to handle 204 right now?

**Comment by JakeWharton** [comment]
`NullOnEmpty` is for broken servers who return 0-length bodies instead of JSON literals of `null` for an absent body.

Right now there's not a good way to differentiate this case because the HTTP status code bypasses the converter. If you don't care about distinguishing between 204 and 205 you can use an OkHttp interceptor to rewrite them to 200's with a `null` literal as the root element.

Beyond that, we probably need to add a method to `Converter.Factory` for handling HTTP 204/205 since there is no body but the user requested an instance of a particular type. I need to think about it more.

**Comment by RaviH** [comment]
Great. I might have a question later but thank you for the explanation.
