### ISSUE TITLE
@FormUrlEncoded and fields

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [square/retrofit#3108]
If I use fields I have to use the @FormUrlEncoded annotation. But if this is always mandatory, is it not possible to avoid the use of @FormUrlEncoded when there are fields so Retrofit does it by default without the annotation?

**Comment by JakeWharton** [comment]
Sure, it's likely possible. I haven't thought about it in depth. But I prefer the explicitness it provides. The normal mode of operation is calling the converter with your body and the annotations take it out of that mode and into another at the method-level rather than having to search the parameters to infer behavior.
