### ISSUE TITLE
[Feature Request] Detect Server Errors and execute onFailure

### ISSUE THREAD

**Issue by drmelectronic** [square/retrofit#3169]
Im testing with error servers and always onResponse is execute, with Debug tool I see what

response.code() = 500 or 502
response.body() = null

this is confuse, because this is a error and would be execute onFailure function for show the correspondent message.

**Comment by JakeWharton** [comment]
As an HTTP client abstraction, the execution of that HTTP call was successful which is why the success callback is invoked.

If you want this behavior you can implement a custom version of `Call` with whatever callbacks and semantics you want. Here's a somewhat-elaborate example which breaks out all HTTP errors to granular callbacks: https://github.com/square/retrofit/blob/master/samples/src/main/java/com/example/retrofit/ErrorHandlingAdapter.java

We're not going to be changing this behavior in the library, but we provide you facilities for doing it yourself.
