### ISSUE TITLE
API return Response<T> without suspend keyword

### ISSUE THREAD

**Issue by dscoppelletti** [square/retrofit#3205]
I would like to define an API like this:

```
interface MyApi {
   @POST("fun")
   fun myfun(@Body req: MyRequest): Response<MyResult>
```

I would use it in a coroutine with `Dispatchers.IO` so I don't really need to mark `myfun` with `suspend`.  
When I execute `myfun` it raises the IllegalArgumentException "Unable to create call adapter for Response<MyResult> for method MyApi.myfun".  
If I mark `myfun` with `suspend` it works property, but, again, I should not need this.  
Maybe you can expose a `CallAdapter` for `Response<T>`, so that you don't need to sort out this use-case by yourself.

**Comment by JakeWharton** [comment]
For now you can use `Call<MyResult>` and invoke `execute()`. I'm not sure if we want to support this out of the box or not. Retrofit 1 did this and we explicitly decided to move away from it. It has all kinds of unsavory implications on the HTTP client as well since you're no longer subject to per-host connections limits or per-client connection limits.

Maybe I could just publish it as a sample. The call adapter literally just calls `execute()`. It's like 10 lines of code.

**Comment by dscoppelletti** [comment]
You are right, I am still learning about coroutines. Maybe making the function `suspend` is useful anyway for the cancel stuff and other things like that.  
Sorry for the newbie question.
