### ISSUE TITLE
Reaktive adapter

### ISSUE THREAD

**Issue by AlexeyKorshun** [square/retrofit#3227]
Hello. What do think about adding retrofit adapter for [Reaktive](https://github.com/badoo/Reaktive) library. Your repository doesn't contain coroutines adapter. Why was it published in another repo?

**Comment by JakeWharton** [comment]
Retrofit has included support for using `suspend` directly since [version 2.6.0](https://github.com/square/retrofit/blob/master/CHANGELOG.md#version-260-2019-06-05). I don't see much reason to support anything else for Kotlin directly since it doesn't get much better than `suspend`.

If you need support for Reaktive, I would suggest making a standalone call adapter and adding it to the [Call Adapter wiki page](https://github.com/square/retrofit/wiki/Call-Adapters).
