### ISSUE TITLE
Retrofit Suggestion & Issue

### ISSUE THREAD

**Issue by halimpuckjava** [square/retrofit#3252]
hi

1. add support for kotlin coroutines Flow 

2. exception of conversion data (pojo) when use protobuf as converter

**Comment by JakeWharton** [comment]
Support for `Flow` is not needed since HTTP requests are one-shot operations that are more accurately and flexibly modeled by a `suspend` function.

I have no idea what the second point is trying to say. If you have an issue please provide a failing test case or sample that demonstrates the issue in a new issue. As-is there's no information provided to go on.
