### ISSUE TITLE
Runtime Exception suddenly because of missing of this class Retrofit.Platform

### ISSUE THREAD

**Issue by honey-hoper** [square/retrofit#3253]
Didn't find class "retrofit2.Platform" on path: DexPathList[[zip file "/data/app/com.webhopers.demo-nBrZflRf04drTk9I-HiUoQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.webhopers.demo-nBrZflRf04drTk9I-HiUoQ==/lib/x86, /data/app/com.webhopers.demo-nBrZflRf04drTk9I-HiUoQ==/base.apk!/lib/x86, /system/lib]]

I don't know why but this suddenly started to happen.
Proguard is disabled.
I enabled Multidex but still no luck.

Why is this suddenly started to happen?

**Comment by sakshi805** [comment]
Didn't find class "retrofit2.Platform" on path: DexPathList[[zip file "/data/app/com.webhopers.demo-nBrZflRf04drTk9I-HiUoQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.webhopers.demo-nBrZflRf04drTk9I-HiUoQ==/lib/x86, /data/app/com.webhopers.demo-nBrZflRf04drTk9I-HiUoQ==/base.apk!/lib/x86, /system/lib]]

same issue occured.

**Comment by AshishMohite96** [comment]
Got same issue
`Caused by: java.lang.ClassNotFoundException: Didn't find class "retrofit2.Platform" on path: DexPathList[[zip file "/data/app/com.drivify.drivifydriver-2/base.apk"],nativeLibraryDirectories=[/data/app/com.drivify.drivifydriver-2/lib/arm, /data/app/com.drivify.drivifydriver-2/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]`

![retrofitbuilder](https://user-images.githubusercontent.com/18052898/69490412-739cac00-0ead-11ea-8356-57d80ada892e.png)

tried enabling multidex, but facing same issue

**Comment by honey-hoper** [comment]
Downgrading to these versions solved this issue

`   implementation "com.squareup.retrofit2:converter-gson:2.3.0"
    implementation 'com.squareup.retrofit2:retrofit:2.3.0'
    implementation 'com.squareup.okhttp3:logging-interceptor:3.8.0'`

**Comment by JakeWharton** [comment]
Unfortunately there's nothing Retrofit can do to help with this, it's a packaging problem caused by the Android Gradle plugin. Moreover, it's impossible to even know what's going on based solely on the exception message alone. You could have more than 100 dex files and be running on API 21 and 22. You could have more than one dex file and be running without legacy multidex. Or it may be something else like ProGuard or R8 messing up. But in the end Retrofit isn't causing this, it just happens to be the first class that triggers the failure.

I would recommend asking on StackOverflow or if you can create a reproduction project filing a bug on the Android issue tracker.
