### ISSUE TITLE
Retrofit 302 Error!

### ISSUE THREAD

**Issue by hardypatel30** [square/retrofit#3270]
Getting 302 response in retrofit get url parameter whereas same get url works with httpurl connection with same configuration any idea?

**Comment by fireuse** [comment]
302 code means redirection.

**Comment by hardypatel30** [comment]
@fireuse  yes I knw but why it works with httpurlconnection and not in retrofit ?

**Comment by JakeWharton** [comment]
It is the responsibility of OkHttp to follow redirects, not Retrofit. The only way you should be seeing a 302 is if you have too many redirects (e.g., 20 or more).

Please provide a public URL that exhibits the behavior. Or you can craft a test case using MockWebServer to reproduce the behavior. Otherwise, it's impossible to know what you're actually seeing.

**Comment by Khorsan** [comment]
This happened to me this week. I was trying to request an HTTP URL and it was redirecting to the HTTPS and OkHttp did not follow it by default. It must be a security feature.

Check if this is your case, else try these:
1. https://stackoverflow.com/questions/34881775/automatic-cookie-handling-with-okhttp-3/35346473#35346473
2. https://www.baeldung.com/guide-to-okhttp#10-do-not-follow-redirects

While searching for solutions for you, I realized that it should've been enabled by default in the past. For me, it wasn't.
