### ISSUE TITLE
Feature Request: Move annotations to a separate library

### ISSUE THREAD

**Issue by dragossusi** [square/retrofit#3277]
I am willing to make a way to create a multiplatform way of creating clients using ktor, i want to use retrofit on jvm, but i cant have annotations from JVM inside common modules.

Suggestion:
Migrate annotations to kotlin and make a new library with them, then implement them in retrofit.

**Comment by JakeWharton** [comment]
Switching to Kotlin is not enough. It would have to be a multiplatform Kotlin library. I don't see any value in doing this since the main library is not Kotlin and we're not shipping a multiplatform client in any form.

You can achieve this today by duplicating the annotations into your common code as `expect annotation` and then in the JVM source set doing a `actual typealias` to Retrofit's annotations. That will unblock you without requiring any changes in the library.
