### ISSUE TITLE
FATAL EXCEPTION: OkHttp Dispatcher Process: 11993 java.lang.IllegalArgumentException: Unexpected char 0x92f at 16 in loc value: Reston,Virginia,यूनाइटेड स्टेट्‍स,US,20190,Fairfax County

### ISSUE THREAD

**Issue by vijay28** [square/retrofit#3292]
FATAL EXCEPTION: OkHttp Dispatcher 
Process: 11993 java.lang.IllegalArgumentException: Unexpected char 0x92f at 16 in loc value: Reston,Virginia,यूनाइटेड स्टेट्‍स,US,20190,Fairfax County

I am getting this error on OkHttp Library.How to solve this issue

**Comment by JakeWharton** [comment]
Seems like you're passing invalid data into a header. HTTP headers do not support the full UTF-8 charset. You'll need to sanitize before setting the header or supply the information as part of the body rather than as a header. This exception also comes from OkHttp not Retrofit, so there's nothing we can really do here.
