### ISSUE TITLE
Follow links

### ISSUE THREAD

**Issue by benoitdion** [square/retrofit#333]
Retrofit works great and probably has the cleanest api as far as rest clients goes in the java world. The one limitation is that it's really hard to use to follow links. I understand that it probably wasn't a design goal but would it be something you'd consider? I could easily call the url directly but I really want to be able to use the error handling, logging, converters and everything else configured in the RestAdapter. 

Currently you can do:
```
@GET("/{path}")
SomeObject get(@EncodedPath("path") String path);
```
It works well but this means you can only follow links going to the server configured with the RestAdapter. What do you think about adding a Url annotation?
```
@GET 
SomeObject get(@Url String url);

@POST
void post(@Url String url, @Body SomeObject object);
```

**Comment by IntegersOfK** [comment]
I don't mean to "me too" this Closed issue, I just wanted to point out that Google's Blobstore requires a server to request the upload URL for file content. Naturally, my backend returns the URL to the client as @benoitdion supposes in the OP, where I then need to upload my file content to this newly provided URL, which looks something like this:

     http://myappengineproject.appspot.com/v1/upload/AMmfu6a_UnifhJWCArFhenZj-ReJtPqCsW54fTy6zPLuV61IWaHpnTUKwDIUmJkqg4AdmAx7DgxRMvko8_J8FQ4o49yv6IpifaKeVdJERSgurmXwI3ty5AsaJvC6zk9MyNAuyA5FTf4q/ALBNUaYAAAAAVKnSCBJqm9jIZKt4cx1AnRxFH-dbq3Lc/

Currently it seems that I'm forced to remove the root of the URL (as it is already the setEndpoint) in order to do something like:

````@Multipart
    @POST("/{blobpath}/")
    void storeImageBlob(@EncodedPath("blobpath") String blobpath, @Part("file") TypedFile image, Callback<String> response);
````
Also, you'll notice I have to use the EncodedPath annotation instead of Path because the slashes in the Blobstore-returned URL are inappropriately being converted to %2F.

It's just all inconvenient and it doesn't seem like best practice considering that the EncodedPath annotation is deprecated. I just started using this library and I'm new to all this so I was hoping to have clarified the preferred way of using a URL path returned by an API, to make subsequent requests.

**Comment by Kondra007** [comment]
But I found solution! 
First, we make custom Endpoint (I've found it somewhere on Stack Overflow):
```java
public final class UploadEndpoint implements Endpoint {
        private String url;

        public void setUrl(String url) {
            this.url = url;
        }

        @Override public String getName() {
            return "default";
        }

        @Override public String getUrl() {
            if (url == null) throw new IllegalStateException("url not set.");
            return url;
        }
    }
```
Now, let's look at the URL:
https://example.com.
Yes! We have 2 slashes (/) here.Why not using them?! So, I divided URL into 2 parts: https:/ with one slash and all other part (and one slash goes to @ PUT("/{path}") )
```
String secondPart = httpadress.substring(httpadress.indexOf("https")+7);
```
Now, When I make RestAdapter I write:
```java
endpoint = new UploadEndpoint();
        RestAdapter restAdapter = new RestAdapter.Builder()
                .setEndpoint(endpoint)  //call your base url
                .setLogLevel(RestAdapter.LogLevel.FULL)
                .build();
 worker = restAdapter.create(MyApi.class)
```
And when needed, I write:
```java
endpoint.setUrl("https:");
worker.uploadFile(secondPart,.... something else)
```

**Comment by sockeqwe** [comment]
+1
For instance I have a REST web service that I want to contact. It will return data and a pagination object with absolute urls like this:

```json
{
    "result": [
        {
            "id": 101,
            "name": "Daniel"
        },
        {
            "id": 102,
            "name": "Michael"
        },
        {
            "id": 103,
            "name": "Chris"
        }
    ],
    "pagination": {
        "next": "http://www.foo.com/users?offset=150",
        "previous": "http://www.foo.com/users?offset=50"
    }
}
```

I think the proposal of @benoitdion ( introducing `@Url`) would be a good idea. You could make it more strict  by saying that the method signatures with an `@Url` doesn't allow `@Path` and must have exactly one parameter (a string annotated with `@Url`) or exactly two parameter (a string annotated with `@Url` and the `Callback`)

**Comment by sockeqwe** [comment]
+1 

For instance a REST web service returns a pagination object as part of the result with absolute URLs like this:
```json
{
    "result": [
        {
            "id": 101,
            "name": "Daniel"
        },
        {
            "id": 202,
            "name": "Michael"
        },
        {
            "id": 103,
            "name": "Chris"
        }
    ],
    "pagination": {
        "next": "http://www.foo.com/users?offset=150",
        "previous": "http://www.foo.com/users?offset=50"
    }
}
```

I think @benoitdion proposal (`@Url`) is good. You can make it more strict by saying that the method signature has exactly one  parameter (type of string, with `@Url`) or exactly two (first parameter: type of string, with `@Url` ; second: `Callback`).

**Comment by deadly-cat** [comment]
Uploading images looks not too easy...

```java
public interface ImageService {

    @GET("/{url}")
    Response download(@Path(value = "url", encode = false) String url);

}
```

```java
public Bitmap downloadImage(Uri uri) {
        Bitmap result = null;

        String scheme = uri.getScheme() + ":";
        imageEndpoint.setUrl(scheme);
        Response response = imageService.download(uri.toString().replaceAll(scheme + "/", ""));
        InputStream is = null;
        try {
            is = new BufferedInputStream(response.getBody().in());
            result = BitmapFactory.decodeStream(is, null, null);
        } catch (IOException e) {
            throw new RuntimeException(e);
        } finally {
            if(is != null) {try {is.close();} catch (Exception e) {}}
        }
        return result;
    }
```

imageEndpoint is same as Kondra007 used.

**Comment by snowpong** [comment]
The solution suggested by @Kondra007 doesn't seem to work with asynchronous calls (where you supply a Callback). I created an OverrideEndpoint that extends Endpoint. I override the base url right before I call my special endpoint, and reset it right after. This doesn't work. The default endpoint is still used for my call.

Most likely this is because the asynchronous calls are queued in an executor and by the time the call to getUrl(..) actually happens, we've already reset the url.

Now, a solution to this problem, could be to only reset the endpoint after the next call to getUrl(..), but this doesn't work either since you don't know that your call is the next one in the queue. There could be many calls not yet executed waiting to go.

At the moment I can't find a workable workaround.

**Comment by benoitdion** [comment]
#927 only handles relative urls. It is still inadequate if the url returned is absolute or has a different base url.

**Comment by swankjesse** [comment]
@benoitdion https://github.com/square/retrofit/pull/927/files#diff-aa79c8ed1e0e2557340c01412ea54f7cR898

**Comment by benoitdion** [comment]
:coffee:, thank you

**Comment by ersen-osman** [comment]
When will these features be released? The API of my next project has fields that go the next set of data with the params pre set. The URL is relative however.

**Comment by JakeWharton** [comment]
There is no timeline.

**Comment by ersen-osman** [comment]
Thanks, soon (tm) :)

**Comment by JakeWharton** [comment]
Hoping a first beta at the end of this month. Final release will be this
year*




*almost certainly but not definitely

**Comment by ber4444** [comment]
I have a proof of concept of talking to a HATEOAS service with Retrofit 2 but I'm still struggling with merging the converters for the response types (which are all a subclass of HalResource from the halarious library so it should be easy but it isn't). You can find my code here with more details: http://stackoverflow.com/questions/33404734/ and I can also post the full source if needed.

**Comment by sky-joaofranco** [comment]
I just wrote an article about that subject. It gets quite easy to follow hatoas (hypermedia) links using retrofit: http://mrshogun.tumblr.com/post/146259558212/retrofit-2-and-hateoas
