### ISSUE TITLE
get ping of request

### ISSUE THREAD

**Issue by MohammadB72** [square/retrofit#3348]
how can we get ping of request in retrofit?

**Comment by JakeWharton** [comment]
This is a usage question which is generally more appropriate for StackOverflow. GitHub issues are reserved for bug reports with test cases or samples, or new feature requests. You can use the 'retrofit' tag which is monitored by us and many library users. Feel free to link the asked question back here on the issue.

In general, it's not clear what you mean by "ping" since that's a concept reserved for web sockets or as an implementation detail of http/2 that is not exposed to consumers.
