### ISSUE TITLE
Coroutine cannot catch exceptions

### ISSUE THREAD

**Issue by evansherry** [square/retrofit#3439]
When the network requests, json has an exception, kotlin coroutine cannot catch the exception, and the application crashes.

```
retrofit = Retrofit.Builder()
            .baseUrl(baseUrl)
            .addConverterFactory(GsonConverterFactory.create())
            .addCallAdapterFactory(RxJava2CallAdapterFactory.create())
            .client(okHttpClient)
            .build()
```
NetworkInterceptor
```
override fun intercept(chain: Interceptor.Chain): Response {

        val request = newRequest(chain)
        val response = chain.proceed(request)
        return adapterData(response)   
 }

  private fun adapterData(response: Response): Response{
        response.body()?.let {body ->
            var json = body.string()
            //org.json.JSONException: End of input at character 0 of
            val job = JSONObject(json)
            ...
            val newBody = ResponseBody.create(body.contentType(), json)
            // new response
            return response.newBuilder().body(newBody).build()
        }
        return response
    }

```

```
fun CoroutineScope.launchTryCatch(block: suspend CoroutineScope.() -> Unit,
                                  onError: ((t: Throwable) -> Unit)?){
    launch {
        try {
            block()
        }catch (t: Throwable){
            onError?.invoke(t)
        }
    }
}

viewModelScope.launchTryCatch({
            Repository.device().groupName(group.groupId, content)
            ...
        }, ::handleException)
```

Coroutine uses try/catch and still can't catch the exception. Is there anything wrong with the usage?

**Comment by swankjesse** [comment]
This isn't due to Retrofit coroutines; rather it's in the contract for OkHttp Interceptors. They are only allowed to throw IOExceptions; any other exception is a crash and is delivered to the uncaught exception handler.

If you need an exception then use an IOException subclass, or wrap your exception in an IOException.

**Comment by evansherry** [comment]
I see, thank you for your reply

**Comment by mboukadir** [comment]
Thank you @swankjesse, now I understand the problem we have in our code base, after a migration from rxjava to coroutines. 

We didn’t have this problem with retrofit + rxjava because the `Rxjava2calladapter` catches a `Throwable`.

I wonder if retrofit + coroutines should not catch `Throwable` like the `Rxjava2calladapter`?

**Comment by JakeWharton** [comment]
The behavior difference with the RxJava 2 adapter is that it executes calls synchronously which allows OkHttp to propagate all exceptions directly to the called to adapt into the Rx stream. You'll see the same behavior of coroutines in Rx if you create the adapter using async calls instead of synchronous calls.

It's not great, but it's just how OkHttp behaves for async calls.

**Comment by mboukadir** [comment]
Ok, thanks for your reply.
