### ISSUE TITLE
@POST data 'sometimes' work

### ISSUE THREAD

**Issue by suryoaji** [square/retrofit#3441]
Hello @JakeWharton,

I'm an Android Developer.
Most of my projects are using retrofit, thanks for your work!
But currently i have an issue for posting data with retrofit using okhttp as client then add GsonConverterFactory (as common)
I had posted data with these params
- annotation @Formurlencoded and @FieldMap with HashMap (String,String)/(String,RequestBody)
- annotation @Multipart and @PartMap with HashMap (String,String)/(String,RequestBody)
- @Body with JsonObject from gson

I have JsonObject in POJO to retrieve the response

Already check on postman to ensure the issue is from serverside, but no.
In postman the API is running well.

I'm using Android Studio v3.6.3, with gradle dist wrapper 5.1.1, gradle tools build 3.4.1, retrofit 2.6.2
with those environment, my previous projects are running well.

Thanks.

**Comment by JakeWharton** [comment]
Can you provide a failing test case or executable sample which demonstrates the problem? How do I reproduce the failure you're seeing such that I can debug what's happening?

**Comment by suryoaji** [comment]
Can you provide me ur email? I will send you my project to test

**Comment by swankjesse** [comment]
@suryoaji you're making unreasonable expectations of your open source project maintainers.

Our job is to provide source code that we believe solves a problem. Your may use that code rather than write it yourself. If you think our code is incorrect, you can get us interested is by showing us a failing test case.

At no point will we debug your program for you! Our company pays us to debug its problems; your organization has you to debug their problems.

Please open a new bug once you have a failing test. If you just want to ask questions, I recommend StackOverflow.
