### ISSUE TITLE
Getting 'Unable to create converter for java.util.List<CUSTOM_CLASS> for method ...' when trying to parse list of (int)enums from JSON

### ISSUE THREAD

**Issue by otj-itf** [square/retrofit#3452]
Custom class:

```
@JsonClass(generateAdapter = true)
@Parcelize
data class InfoObject(
        val id: String,
        val name: String,
        val email: String,
        val phone: String,
        @MyEnumAnnotation
        val myEnumList: List<MyEnum>
) : Parcelable
```

Adapter for MyEnum:
```
@Retention(AnnotationRetention.RUNTIME)
@JsonQualifier
annotation class MyEnumAnnotation

class MyEnumAdapter {
    @ToJson
    fun toJson(@MyEnumAnnotation myEnum: MyEnum): Int {
        return myEnum.type
    }

    @FromJson
    @MyEnumAnnotation
    fun fromJson(type: Int): MyEnum {
        return MyEnum.from(type)
    }
}
```

Have added this to moshi builder, but getting the error back when trying to parse JSON from API response.
When changing from type `List<MyEnum>` to `List<Int>`, everything works fine...

(Names changed for privacy reasons)

**Comment by JakeWharton** [comment]
Based on the code you've shown, this is a usage question about Moshi, not Retrofit. Retrofit does not participate in how Moshi creates its adapters. Please ask on StackOverflow with the 'moshi' tag. Ideally also include the full stack trace since the first cause of the thrown exception actually contains details of the problem.

**Comment by otj-itf** [comment]
https://stackoverflow.com/questions/63390650/how-to-convert-list-of-int-in-json-to-list-array-of-enums-using-moshi
