### ISSUE TITLE
post body shows up in memory dump

### ISSUE THREAD

**Issue by LukeLinXu** [square/retrofit#3459]
I was using https://github.com/Nightbringer21/fridump to dump memory in rooted device. 
I saw lots of post body show up in the report. 
sometimes we posted username/pwd to service, but they were dumped. 
Any idea how to fix it?

reproduce steps:
1. prepared fridump environment, and rooted android device
2. using retrofit to post some data as body, like JsonObject
3. run memory dump, you will see post body data shows up.

**Comment by JakeWharton** [comment]
I don't think there's anything to fix. It is expected that this will be in memory in order to be sent by some (or multiple) layers of the stack. If you have root then the device is entirely compromised and we will be making no effort to combat your ability to access things which are being sent because it is impossible.
