### ISSUE TITLE
GsonConverterFactory comes into conflict with ScalarsConverterFactory

### ISSUE THREAD

**Issue by Vicent9920** [square/retrofit#3486]
When you use RxJava, setting both GsonConverterFactory and ScalarsConverterFactory causes the returned string to generate a Gson parsing exception. Using Retrofit's Call can circumvent the above exceptions, but can cause RxJava requests in the project to be inconsistent; If you delete Retrofit and delete the GsonConverterFactory using only one ScalarsConverterFactory, it works fine using Observable, but most cases in your project require the GsonConverterFactory to parse, so two Retrofit must be used to work in this case?

**Comment by JakeWharton** [comment]
It sounds like you have an ordering problem. If you register the scalars converter factory first it will only handle `String`, `int`, etc. With the Gson converter factory registered second it will handle all other types because it assumes that it can deserialize into any type.

If, for some reason, you need the handling of `String` to be conditional on something else then you can follow the JSON and XML sample for setting up two converter factories that handle the same type: https://github.com/square/retrofit/blob/7128bf34c649daca5977b1fbf93f0278fab4267c/samples/src/main/java/com/example/retrofit/JsonAndXmlConverters.java
