### ISSUE TITLE
Way of handling kotlin coroutine suspend keyword

### ISSUE THREAD

**Issue by lulumeya** [square/retrofit#3491]
I looked into how retrofit handles 'suspend' keyword. 

I found that retrofit uses 'suspendCancellableCoroutine' with retrofit's regular enqueue call.

This means, retrofit's suspend keyword handling done in regular java thread.

I wonder why this has to be done like this.

I think the 'suspend' keyword has to be handled on kotlin coroutine's context to get advantages regarding coroutine's concurrency handling.

**Comment by JakeWharton** [comment]
> This means, retrofit's suspend keyword handling done in regular java thread.

It means we delegate to OkHttp to decide what to do. Yes, it uses regular threads, but coroutines also uses threads. Everything uses threads on the JVM.

> I wonder why this has to be done like this.

It doesn't. We could just as easily do `withContext(IO) { call.execute() }` which uses a thread from the coroutines library rather than one from OkHttp.

The advantage of using OkHttp is that it can share a single thread for the majority of a HTTP/2 connection's bookkeeping and only move to a dedicated thread when reading the response body.

> I think the 'suspend' keyword has to be handled on kotlin coroutine's context to get advantages regarding coroutine's concurrency handling.

What led you to believe this?

**Comment by JakeWharton** [comment]
Here's another way to think about it:

`suspendCancelableCoroutine` is used with UI callbacks where the user is performing a background task ("thinking") before interacting with a UI component like a button. If coroutines did not work in this model the UI use case would be fundamentally broken.

**Comment by lulumeya** [comment]
I could relate to you that it can take advantages with okhttp's networking but also let us use suspend keyword.
Thanks.
