### ISSUE TITLE
make it possible to ignore some parameters

### ISSUE THREAD

**Issue by nnobelis** [square/retrofit#3492]
Hello,,

I am using **Retrofit 2.9.0** and I'm facing a problem with my current Kotlin Code :

```
@POST("api.php")
    fun getProject(
        apiKey: String,
        user: String,
        vararg pairs: Pair<String, String>,
        @Body body: PostRequestBody = PostRequestBody("get_information", "projects", apiKey, user, *pairs)
    ): Call<EntityPostResponseBody<Project>>
```
This code is failing with the following error :
`No Retrofit annotation found. (parameter #1)`

In fact, only the parameter 4 is supposed to be used for the request. The others are just here to fill the default value.
Would it be possible to have an _@Ignore_ annotation so that Retrofit ignores the annotated parameters ?
e.g.
```
@POST("api.php")
    fun getProject(
        @Ignore apiKey: String,
        @Ignore user: String,
        @Ignore vararg pairs: Pair<String, String>,
        @Body body: PostRequestBody = PostRequestBody("get_information", "projects", apiKey, user, *pairs)
    ): Call<EntityPostResponseBody<Project>>
```

**Comment by JakeWharton** [comment]
You can use an overload with a default body that calls the Retrofit-backed abstract method.
```kotlin
interface Whatever {
  fun getProject(
    apiKey: String,
    user: String,
    vararg pairs: Pair<String, String>,
  ) = getProject(PostRequestBody("get_information", "projects", apiKey, user, *pairs))

 @POST("api.php")
  fun getProject(@Body body: PostRequestBody): Call<EntityPostResponseBody<Project>>
}
```
Or use an extension function to not pollute the interface.
```kotlin
interface Whatever {
   @POST("api.php")
    fun getProject(@Body body: PostRequestBody): Call<EntityPostResponseBody<Project>>
}

fun Whatever.getProject(
  apiKey: String,
  user: String,
  vararg pairs: Pair<String, String>,
) = getProject(PostRequestBody("get_information", "projects", apiKey, user, *pairs))
```

**Comment by sschuberth** [comment]
I believe the whole point was to *not* introduce overloads / wrapping functions to reduce code duplication and to have a better overview over the functions. That's why I'd still like to ask: Would it be feasible to introduce such an `@Ignore` annotation? Or why doesn't Retrofit ignore non-annotated parameters by default?

**Comment by JakeWharton** [comment]
> reduce code duplication and to have a better overview over the functions

There is no duplication in my examples. One function is an instruction to Retrofit and the other is a convenience version with deconstructed parameters. Same number of parameters, same number of annotations (fewer if you count `@Ignore`), and same amount of code which creates the body object.

I would also argue that it's far easier to understand what is happening as it's abundantly clear what parts are being handled automatically by Retrofit and which parts are being handled by user code.

> Would it be feasible to introduce such an @Ignore annotation? Or why doesn't Retrofit ignore non-annotated parameters by default?

I have not seen a compelling reason to introduce the annotation. All parameters are required to be Retrofit instructions since it is Retrofit which is implementing the interface. Having a parameter with no functionality that is parsed by Retrofit would be weird.

In the original proposal, a caller could supply both the individual parameter values _and_ the body object with different contents. My two versions eliminate that possibility.
