### ISSUE TITLE
Update okhttp library to solve some vulnerabilities

### ISSUE THREAD

**Issue by danielgielowjr** [square/retrofit#3508]
- [ ] Feature Request. Update `okhttp` to the newest version to resolve a **vulnerability** issue. Before the version 4.5.0 of Okhttp, the library makes reference to  `conscrypt-openjdk-uber` that until version 2.2.1 makes reference to `org.bouncycastle:bcprov-jdk15on:1.56`, this version contains 3 known vulnerabilities (1 Critical, 1 High, 1 Medium) as we can see in [CVE-2018-1000613](https://nvd.nist.gov/vuln/detail/CVE-2018-1000613), [CVE-2018-1000180](https://nvd.nist.gov/vuln/detail/CVE-2018-1000180) and [CVE-2017-13098](CVE-2017-13098). In the newest versions neither `okhttp` nor `conscrypt` makes reference to `bcprov-jdk15on` anymore.

https://github.com/square/retrofit/blob/master/build.gradle#L6
`buildscript {
  ext.versions = [
      'okhttp': '3.14.9'
  ]`

https://github.com/square/okhttp/blob/parent-3.14.9/pom.xml
`<conscrypt.version>2.0.0</conscrypt.version>`

https://github.com/google/conscrypt/blob/2.0.x/build.gradle
`                bouncycastle_apis: 'org.bouncycastle:bcpkix-jdk15on:1.56',
                bouncycastle_provider: 'org.bouncycastle:bcprov-jdk15on:1.56',`

**Comment by swankjesse** [comment]
The OkHttp artifacts Retrofit depends upon is build-time only. Retrofit users do not transitively depend upon Conscrypt, or BouncyCastle, regardless of which OkHttp version they use.

The okhttp-tls artifact used to depend on BouncyCastle, but this artifact is not used by Retrofit.

**Comment by hbsis-danieljunior** [comment]
Thank you for your answer. So, it's not interesting to keep this dependency updated?
Since 4.8.0 version okhttp doesn't make reference to Bouncy Castle saving 6.5 MiB in dependencies.

https://square.github.io/okhttp/changelog/#version-480
_"New: Change HeldCertificate.Builder to use its own ASN.1 certificate encoder. This is part of our effort to remove the okhttp-tls module’s dependency on Bouncy Castle. We think Bouncy Castle is great! But it’s a large dependency (6.5 MiB) and its security provider feature impacts VM-wide behavior."_

**Comment by swankjesse** [comment]
That's for the okhttp-tls module, that Retrofit doesn't depends on.

**Comment by danielgielowjr** [comment]
You're right, I'm sorry about de confusion

**Comment by JakeWharton** [comment]
Retrofit is tied to 3.x for the foreseeable future because it's the last version written in Java. We are not prepared to force the Kotlin stdlib dependency on our consumers without first reevaluating what Retrofit looks like in a Kotlin world, likely with a major API change to support things like Kotlin multiplatform and switching from runtime reflection to ahead-of-time code generation.

Consumers of Retrofit are encouraged to update OkHttp to the latest 4.x which remains binary compatible with 3.x, however. We just aren't going to force it yet.
