### ISSUE TITLE
Not possible to set Content-Type header for GET request

### ISSUE THREAD

**Issue by code-guru** [square/retrofit#3551]
We need to set Content-Type header for GET requests to conform a 3rd party API service. However it is not possible to set the header. I tried setting the header both in interceptor and `@Headers` annotation, but none of them worked. 

Is there a way to set Content-Type header on GET requests? 

(since the RFC does not explicitly prohibit setting content-type on GET requests, there should be a way to override this behaviour if needed)

**Comment by JakeWharton** [comment]
Sounds like it's an OkHttp issue if it doesn't work inside of an interceptor either. It's possible OkHttp removes the header because of the lack of body. I would file an issue on OkHttp.

Retrofit is basically a fancy Request builder for OkHttp, and I just confirmed we support this case fine: https://github.com/square/retrofit/pull/3552. If you observe it not being sent across the wire, this is further evidence the problem lies in OkHttp.
