### ISSUE TITLE
Headers Annotation not accepting multiple headers

### ISSUE THREAD

**Issue by blood-rogue** [square/retrofit#3572]
`
@Headers({
    "Accept: application/json",
    "Content-Type: application/json"
})
` is showing error _Type mismatch: required: String, found: () -> String_ in IntelliJ IDEA.
Any help is appreciated.
Using retrofit version 2.9.0
![image](https://user-images.githubusercontent.com/64477767/121126468-d4989480-c845-11eb-975b-1488faeba2cc.png)

**Comment by blood-rogue** [comment]
`
Headers("Accept: application/json", "Content-Type: application/json")
`
is now not showing error.
Hope you change the docs shown for the annotation

check this out
![image](https://user-images.githubusercontent.com/64477767/121132602-f64a4980-c84e-11eb-9f8e-f46ecff38f7f.png)

**Comment by JakeWharton** [comment]
The documentation is written in Java because the library is written in Java. Retrofit works in all JVM languages, but each may vary in their syntax slightly and there's not really anything we can do to automatically show the right one. I also don't think it makes sense to have ever example have a version in each language.
