### ISSUE TITLE
SimpleXML 2.7.1 prone to XXE vulnerability

### ISSUE THREAD

**Issue by fernandogross** [square/retrofit#3625]
Our security team reported an old XXE vulnerability on SimpleXML, which is a transitive of Converter: SimpleXML 2.9.0. I did some research here but couldn't find any discussion about it, are there plans to implement the community solution (see below) or anything like that? What is the recomendation you guys have to avoid this security issue? Is there even an issue on the way the converter implements SimpleXML?

More details on the vulnerability: https://github.com/ngallagher/simplexml/issues/18
Community solution: https://github.com/dweiss/simplexml

**Comment by JakeWharton** [comment]
You can use a resolution strategy in Gradle to switch to one of the third-party forks with mitigations in place in the SimpleXML codebase. Alternatively, depending on which XML provider you are using, there is a potential to configure it globally on that library. SimpleXML is after all only delegating to one of three actual XML parsers to do the work. For us, the library seems like abandonware anyway which is why we deprecated it long ago.

I don't think we'll be taking any direct action on this.
