### ISSUE TITLE
How to refresh the livedata which responsed by a retrofit api ? 

### ISSUE THREAD

**Issue by jj532655203** [square/retrofit#3689]
How to refresh a livedata which responsed by a retrofit api ? 

 Actually ,I hope retrofit can import LiveDataCallAdapterFactory from https://github.com/jj532655203/LiveDataCallAdapter

**Comment by JakeWharton** [comment]
Do not use `LiveData` as your service return type. An HTTP call is not a live source of data. It's a single-shot operation. If you want to refresh a `LiveData` backed by an HTTP request then put some code between the two whose responsibility it is to know when to re-issue the HTTP request.

We will not be providing a built-in `LiveData` adapter because aside from HTTP calls not being a streaming type it forces processing on the main thread and has no error-handling channel. It is not suitable to model an HTTP request.

**Comment by jj532655203** [comment]
Jake Wharton, YYDS 👍
