### ISSUE TITLE
NullPointerException: @Url parameter is null.  不知道怎么发生的导致崩溃

### ISSUE THREAD

**Issue by xuehuashi** [square/retrofit#3697]
外网偶发，不知道怎么出现的，导致崩溃。
   和请求方式get/post有关?？还是@Url 作为参数偶发有问题？
    @GET
    Observable<BaseResponse<LiveCourseListEntity>> getLive(@Url String url);
    @FormUrlEncoded
    @POST
    Observable<BaseResponse<Object>> deleteExer(@Url String url)

   打算url 不作为参数，试一下，比较难复现，杯具了
    @GET（“/xx/xx.do）
    Observable<BaseResponse<LiveCourseListEntity>> getLive();
 
希望大佬遇到类似分享下经验和方案

**Comment by JakeWharton** [comment]
Based on the exception message the problem seems like your code is allowing a `null` reference to be used as the argument value.

If you can provide a failing test case or executable sample that demonstrates other I will take a look. But otherwise it seems like a problem in your code rather than in Retrofit.
