### ISSUE TITLE
A synchronous use of the retrofit with the .execute method giving Error

### ISSUE THREAD

**Issue by abhishekpathak-agva** [square/retrofit#3710]
While using retrofit in synchronous mode while using .execute method giving an error gives a error Fatal signal 11 (SIGSEGV), code 1, fault addr 0x14 in tid 16155 (JDWP), pid 16148.  But the situation I am stuck in can be solved by only by the synchronous approach since the main thread initiates shutdown process and until the .enqueue method comes up with the result the main thread of the android app already reaches end.  So .execute synchronous approach is the only way to resolve it, but the error is a pain.

**Comment by JakeWharton** [comment]
Can you provide a self-contained sample which reproduces the problem? We have plenty of usage of `.execute()` in Retrofit's own test suite without issue.

**Comment by AbhishekPathak-Agva** [comment]
Fatal signal 11 (SIGSEGV), code 1, fault addr 0x14 in tid 16155 (JDWP), pid 16148 was some issue arose because of some local build.  And the .execute works but it didn't solved the problem the mainthread is in closing process, and .execute is a synchronous request but due to framework issues the network request cannot be made on the main thread so a background thread.  But thanks.

**Comment by JakeWharton** [comment]
This limitation is imposed by Android, yes.
