### ISSUE TITLE
http exception in gradle 7.1.3 

### ISSUE THREAD

**Issue by piseysen** [square/retrofit#3727]
I upgrade project to gradle 7.1.3 and kotlin 1.6.20  it error, when I downgrade to 7.1.2 is ok

**Comment by JakeWharton** [comment]
There is no Gradle version 7.1.3. Did you mean Android Gradle plugin version?

In either case, you have provided no information here as to the exception or what might be causing it. In general, bumping the Kotlin version and Android Gradle plugin should have no effect on Retrofit. The only thing that may have changed is the version of R8 was upgraded which could change the semantics of code shrinking/optimization. But again, I'm just guessing since no information was provided.

Please attach a minimally-reproducing sample project or code for a failing unit test. Otherwise it is impossible to know what is going on.

**Comment by JakeWharton** [comment]
Without a sample it's impossible to know if that's the fix or not for their issue, or yours.
