### ISSUE TITLE
Too many requests at same time leads to trouble with headers

### ISSUE THREAD

**Issue by mathislaurentpiquoti** [square/retrofit#3775]
I'm using Retrofit 2.9.0 to call a RESTful API based on Symfony. 

I observed that sometimes, some requests returns 400 Bad Requests but when I retry them it's good. 

After investigating a long time, I found that sometimes my custom header for authorization is duplicated : 

![screen bug 400](https://user-images.githubusercontent.com/70519372/192288169-bb8c53d4-b6f6-4b5c-afd0-e60c43c0aad7.png)

In my code it's normally impossible, I remove the header "authorization" before add it and when I log the header in requestBuilder just before the chain.proceed, it's well formatted and not duplicated...

``` kotlin
try {
      requestBuilder.removeHeader(TOKEN)
 } catch (e: Exception) {
      e.printStackTrace()
 }
 requestBuilder.addHeader(TOKEN, "Bearer ${token.token}")
```
 
 Other information, I add the custom header in an interceptor (okhttp3)

**Comment by JakeWharton** [comment]
Retrofit has no control over how OkHttp and its interceptors behave. That being said, the semi-colon indicates the header is being added twice as that is what happens when you add multiple values for the same name. If you want to overwrite you should use the `header` function over `addHeader`. Additionally, it's not clear why you would need to try/catch the `removeHeader` call.

**Comment by mathislaurentpiquoti** [comment]
Thanks for your answer. I'm testing with header function instead of addHeader and for now the problem is not happening anymore.
