### ISSUE TITLE
Unknown Host exception.working fine in iOS and postman using same network.

### ISSUE THREAD

**Issue by aftab-b** [square/retrofit#3783]
Bug in Retrofit : 2.9.0
Okhhtp : 4.10.0

<img width="322" alt="Screen Shot 2022-11-14 at 7 58 46 PM" src="https://user-images.githubusercontent.com/58593121/201685555-b9e13dfe-d768-49fb-a58b-9a890f3f1888.png">
Issue : We are getting Unknowhost exception in our application.and once it come application never connect to backend server.
Other application are working fine.
We have checked all the possibilities like Internet permission and all but nothing works.

This is the error logs we are getting.

<-- HTTP FAILED: java.net.UnknownHostException: Unable to resolve host "cms-api-uat.hoabl.in": No address associated with hostname
2022-11-11 14:00:55.169 16077-16077/

**Comment by JakeWharton** [comment]
Retrofit has no control over this. We build a request object and send it to OkHttp to fulfill. Even OkHttp has very little control over this. In the full stack trace you can see that the exception comes deep within the Android OS stack which is responsible for DNS resolution. So the problem lies elsewhere, such as a missing INTERNET permission, a captive Wi-Fi portal, or something of the like.
