### ISSUE TITLE
Socket Timeout Issue 

### ISSUE THREAD

**Issue by NazarAbbas** [square/retrofit#3868]
We are getting sockettimeoutexception most of the times applications gets started on mobile, we are using Mobile Network with Private APN. And once it starts throwing this exception, Retrofit always send the same behaviour of sockettimeout. If we disable the internet and enable again, then it agains starts working again.

**Comment by JakeWharton** [comment]
Retrofit is an OkHttp abstraction. We merely hand requests to OkHttp and parse its responses. We have no ability to control or influence how the actual network transport works. Or, put another way, if you manually issued HTTP requests and responses with OkHttp you would see the same behavior as Retrofit, because that's all the library is doing.
