### ISSUE TITLE
Associate HTTP Method Annotations with Request to simplify metrics gathering.

### ISSUE THREAD

**Issue by kylannjohnson** [square/retrofit#3988]
What kind of issue is this?

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/retrofit

 - [ ] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9

 - [x] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

I would like to use the contents of the http method annotations (e.g. `@GET, @POST`) as an alias or name for data/metrics gathered as a result of using the the associated Retrofit Service.    e.g. `/foo/bar/{id}` would be the operation identifier for a specific request so that any request made could then be associated with other to the same endpoint regardless of the path values.

It seems that the current method of doing this would be to create a CallAdapter factory which can process the method annotation and capture it in some way such that an OkHttp interceptor or EventListener can act on it.

However, I'm wondering if there is a better way to gain access to the annotations without have to write a Factory.  E.g.  Could an API be added which allows a request to be tagged via the [Request.Builder](https://square.github.io/okhttp/3.x/okhttp/okhttp3/Request.Builder.html#tag-java.lang.Class-T-)?   Perhaps such an API could be added to the RequestFactory?

Since the method parameter is a template for the URI Path, it's advantageous to associate a specific okhttp.Call to this annotation such that a FQDN doesn't need to be reverted back to its template in order to "name" metrics.

**Comment by JakeWharton** [comment]
Retrofit automatically adds an instance of [`Invocation`](https://square.github.io/retrofit/2.x/retrofit/retrofit2/Invocation.html) to OkHttp's `Request` which you can then read inside an interceptor in order to centrally log metrics. That type has the Java reflection `Method` on which you can read the annotation and gets its path template. Unfortunately you'll have to check for all 6 annotations which could be used, but at least that code only gets written once so it's not so bad.

We have a sample showing how it could be used here: https://github.com/square/retrofit/blob/dd143e6dfcc5b2b7b92abe7ebc08cb710f6a5bc4/samples/src/main/java/com/example/retrofit/InvocationMetrics.java

Do you think that covers your use case sufficiently? Or is there something else missing?

**Comment by kylannjohnson** [comment]
@JakeWharton, that's exactly what I was looking for.  I just tried it out in my setup and it seems to work.  Thanks!
