### ISSUE TITLE
Converter is called on main thread when parsing query param

### ISSUE THREAD

**Issue by wellwhatever** [square/retrofit#3989]
Hi,
I have noticed that the .convert() function of the provided Converter is invoked on the main thread when parsing query parameters. I am uncertain whether this behavior is intentional. There is lack of info about this in documentation so, could you please clarify it in the documentation and specifically why is it executed on the main thread. This might be worth considering as a potential issue.

**Comment by PiotrBandurski** [comment]
I noticed same issue, and it is kind problematic in large applications when there is number of calls with complex responses on startup. Example from app which I work on:
<img width="510" alt="image" src="https://github.com/square/retrofit/assets/12571316/8b785f29-7ac3-423e-a613-6636595f4a4a">
<img width="359" alt="image" src="https://github.com/square/retrofit/assets/12571316/ffa7f754-00a1-407d-b452-52f51ce0a922">

**Comment by Endeavour233** [comment]
I think it's because `.convert()` is invoked when `retrofit2.Call` (current core implementation is `OkHttpCall`) creates a `okhttp3.Call`, which actually executes the network request,  by `createRawCall()`(to be more specific, when `requestFactory#create(@Nullable Object instance, Object[] args)` is invoked to create a `okhttp3.Request`). and `createRawCall` happens on the thread where you invoke `retrofit2.Call#enqueue`  or  `retrofit2.Call#execute`.

**Comment by JakeWharton** [comment]
You're close. As you surmised, we need to convert all parameters which contribute to the URL synchronously so that we can create the underlying OkHttp `Call` to then wrap in our `Call`. This does not execute the request.

A future design might consider doing this differently, but we don't really have a choice with the current design.

**Comment by Endeavour233** [comment]
> I think it's because `.convert()` is invoked when `retrofit2.Call` (current core implementation is `OkHttpCall`) creates a `okhttp3.Call`, which actually executes the network request, by `createRawCall()`(to be more specific, when `requestFactory#create(@Nullable Object instance, Object[] args)` is invoked to create a `okhttp3.Request`). and `createRawCall` happens on the thread where you invoke `retrofit2.Call#enqueue` or `retrofit2.Call#execute`.

To be clear, by saying "which actually executes the network request", I mean that network request is delegated to `okhttp3.Call`.
