### ISSUE TITLE
How to send GET Request with JSON body?

### ISSUE THREAD

**Issue by PanosHatz** [square/retrofit#4033]
Is it possible to send a **GET request with a JSON body** to an API using Retrofit? 

I've seen that a way to do it is using the following but I can't make it work, I get 400 bad request:

`@HTTP(method = "get", path = "/restapi.php", hasBody = true)                                                                 Call<ResponseModel> myMethod(@Body RequestModel myRequest);`

Are there any **full code examples** on this? Do we need two classes ResponseModel and RequestModel where the first has the get methods (for the return of values) and the other sets the body variables via the constructor just like most POST/GET code examples of Retrofit API calls?

I need to send a json (containing username and password) to a PHP API that has been already created to accept a GET call for login and can't be changed.

**Comment by Goooler** [comment]
In your example, your code should be
```java
@HTTP(method = "GET", path = "/restapi.php", hasBody = true)
Call<ResponseModel> myMethod(@Body RequestModel myRequest);
```
note the `method` should be uppercased, and execute it, there will be an exception thrown: `java.lang.IllegalArgumentException: method GET must not have a request body`.

Like the exception described, you shouldn't use GET request with body in REST APIs.

**Comment by Goooler** [comment]
We probably check `method` is uppercased and throw it eagerly?

**Comment by JakeWharton** [comment]
The exception comes from OkHttp which prevents bodies on GET requests because the interaction semantics with things like caching and transparent retries are unclear. Retrofit prevents the body with the `@GET` annotation for similar reasons, but you can of course bypass it as noted here (and in the [other issue you commented on](https://github.com/square/retrofit/issues/3735#issuecomment-1127929948)) because Retrofit is merely a request factory and doesn't try too hard to enforce semantics. OkHttp, however, has to.

Your only option is to slot in an alternative HTTP client by implementing `Call.Factory` and applying the mapping to and from OkHttp's request and response model.

I don't believe there's any action to take here.
