### ISSUE TITLE
Unable to build project

### ISSUE THREAD

**Issue by IgorGanapolsky** [square/retrofit#4123]
What kind of issue is this?

This is a bug.  Steps:
1) checkout repo
2) open repo in Android Studio Iguana (2023.2.1)
3) compile project

EXPECTED:
project should build

ACTUAL:
compilation error - 
> Could not resolve all dependencies for configuration ':retrofit:compileClasspath'.
Failed to calculate the value of task ':retrofit:compileJava14Java' property 'javaCompiler'.
Cannot find a Java installation on your machine matching this tasks requirements: {languageVersion=14, vendor=AZUL, implementation=vendor-specific} for MAC_OS on aarch64.
No locally installed toolchains match and the configured toolchain download repositories aren't able to provide a match either.

**Comment by JakeWharton** [comment]
You should really be using IntelliJ IDEA not Android Studio. It might work in Studio, it might not. This isn't an Android project.

I'm not sure why Azul seems to have stopped providing JDK 14. It's still available from https://github.com/mdogan/homebrew-zulu.

Aside from that, I will eventually migrate the project from using toolchains (boo!) to `--release` (yay!), but I haven't had the time. For now you'll have to get a JDK 14 and JDK 16 from somewhere because that's what Gradle toolchains demand. It does work on CI, but that might be because it's an x64 system not ARM.

**Comment by IgorGanapolsky** [comment]
Thank you for the advice.  I was under the impression that the samples are for Android, since I'm learning how to use Retrofit on Android.  I misunderstood.
