### ISSUE TITLE
UnknownHostException in V 2.9.0

### ISSUE THREAD

**Issue by saikrupa** [square/retrofit#4155]
What kind of issue is this?

 - [ ] **Question.** I see a UnknownHostException in my production app with a good amount of failure but it's not the issue with every user, I see 30 to 40% of users were seeing this issue and trying to understand is there anything wrong with the retrofit in recent versions(2.9.0). Because it's not happening to one host name, My app is integrated with several host's and most of the host names were having the same issue some are failing with 10 to 20% and some with 30 to 40%. I have the **android.permission.INTERNET**,**android.permission.ACCESS_NETWORK_STATE** permissions set properly, and Network_security_config.xml is also added 

 - [ ] **Bug report.** responseCode - java.net.UnknownHostException: Unable to resolve host "XYZ.com/api": No address associated with hostname

**Comment by yuvashreenarayanan3** [comment]
I'll take up this issue

**Comment by JakeWharton** [comment]
Retrofit does not participate at the level at which this exception is occurring. This exception happens when the Android OS attempts to resolve the host name you provided into an IP address. This is something many layers down, and is a step over which Retrofit has no influence. Put another way, if you issued the same request that you are with Retrofit directly to OkHttp you would receive the same error. Moreover, if you bypassed OkHttp and asked Android to resolve the hostname to an IP yourself (such as though Java's `URL` class) you would see the same exception thrown.

**Comment by saikrupa** [comment]
@JakeWharton I see this thread for the okHttp https://github.com/square/okhttp/issues/7677 which is a dependent library of Retrofit. Do you think this could be the reason for the issue?

**Comment by JakeWharton** [comment]
No. Host resolution happens in the OS, and that thread has multiple links out to the code in the OS showing where there's a potential problem with a 2-second cache and a potential fix in the OS itself.

**Comment by brunorodriguesaraujo** [comment]
I noticed that this error happens when trying to add an interceptor to the client with the internet turned off
