### ISSUE TITLE
Set logging interceptor based on API

### ISSUE THREAD

**Issue by armanTabib** [square/retrofit#4156]
As projects grow the number of API requests sent by the application also grows, and hence the debugging of APIs gets more complicated. It would be much convenient to be able to specify API calls by some annotation to output okhttp log. Something like this:

```
@LogInterceptor(DefaultHttpLogInterceptor())
@POST("/users/sign-in-phone")
    suspend fun loginPhone(@Body body: LoginPhoneRequestDto): Response<LoginResponseDTO.LoginSuccessfulResponseDTO>
```
This would print out the log of this specific API instead of whole network connection to server. 
Is it feasible to add such thing to Retrofit?

**Comment by JakeWharton** [comment]
We cannot do this because Retrofit doesn't actually assume the implementation of `Call.Factory` is an `OkHttpClient`. Moreover, we don't require the dependency on OkHttp's 'logging-interceptor', nor know where to send the logs even if we did.

That being said, Retrofit is designed so that you can build these things yourself.

Create an annotation, and then build an OkHttp interceptor which checks for the annotation on the `Request`'s `Invocation` and conditionally delegates to the logging interceptor. I added one to our samples in #4159.
