### ISSUE TITLE
How to get the URL endpoint and the GET/POST method when an Exception occurs?

### ISSUE THREAD

**Issue by vstung89** [square/retrofit#4174]
Hello everyone, I need help with an issue.

I use a suspend function to call the API as shown in the code below. How can I get the URL endpoint and the GET/POST method when an Exception occurs?

```
suspend fun <T : BaseResponse> safeCallApi(
	api: suspend () -> Response<T>
): Result<T> {
	return try {
		val response = api()
		if (response.isSuccessful) {
			val body = response.body()
			if (body != null) {
				Result.success(body)
			} else {
				Result.failure(BodyNullException())
			}
		} else {
			Result.failure(ServerException())
		}
	} catch (e: Exception) {
		// I want to obtain the information about the URL endpoint and the GET/POST method there.
		Result.failure(UnknownException(e))
	}
}
```

**Comment by angusholder** [comment]
You'll need to change your API method from

    suspend fun myApiMethod(): Response<T>

to 

    fun myApiMethod(): Call<T>

then change your code above to

```kotlin
val call: Call<T> = api()
try {
    val response: Response<T> = call.awaitResponse()
    ..
} catch (e: Exception) {
    call.request().method // use me
    call.request().url // use me
    Result.failure(UnknownException(e))
}
```

**Comment by JakeWharton** [comment]
Yeah there's basically no way to do this when using a "raw" suspend function because we become at the mercy of underlying libraries and how they throw exceptions. An `HttpException` includes a `Response` from which you can get the `Request`, but `IOException` subtypes won't have that. The only way to retrieve that information is as posted above, where you create the `Call` explicitly and perform suspended-execution separately.
