### ISSUE TITLE
Slash at the relative path beginning

### ISSUE THREAD

**Issue by lsuski** [square/retrofit#420]
Hi,
what is the reason to require putting slash at the path beginning, e.g POST("/")?
I have server url like this: " http://aaa.company.com/service "  and it's not a directory so sending POST to " http://aaa.company.com/service/ " does not work.

**Comment by kvenn** [comment]
I'm running into a problem with duplicate slashes and I'm wondering if there is a solution built into Retrofit.

My server provides the base URL we should be using which will look something like this: `.setEndpoint(http://some.url.com/)`

The server also passes down a path URI that should be appended to that endpoint (with various requests). So my server might send back `/channels/videos`.

This gets handed to Retrofit through the following method
```
@GET("/{uri}")
void GET(@Header("Authorization") String authHeader, @Path(value = "uri", encode = false) String uri,
         @Header("Cache-Control") String cacheHeaderValue, Callback<Object> callback);
```

This is then problematic because the URL that is getting hit with the GET method is `http://some.url.com//channels/videos` which will not work correctly in my situation.

I tried manually stripping out the trailing slash from my base endpoint - but I still saw a duplicate slash which I'm assuming resulted from the `"/{uri}"` and the `/channels/videos`.

I think my problem would be fixed by removing the leading slash in `"/{uri}"` but that isn't allowed in Retrofit. And removing the leading slash in the path URI I get back from my server isn't entirely feasible.

`throw methodError("URL path \"%s\" must start with '/'.", path);`
`retrofit.RetrofitError: GET: URL path "{uri}" must start with '/'.`

Is there another solution to this problem?

**Comment by siggijons** [comment]
I had a similar issue but did not find a solution more elegant than
stripping the leading slash from the incoming "uri"

e.g. `/channels/videos` -> `channels/videos` which would then be processed
to `http://some.url.com/channels/video`
