### ISSUE TITLE
Get the compiled request URL?

### ISSUE THREAD

**Issue by xbroak** [square/retrofit#452]
I'm looking to generate a HMAC using the request url, is there anyway of simply doing a 'getUrl()' on the request so i can see the compiled url?

**Comment by JakeWharton** [comment]
I'll note that you can do this with version 1.9.0 by using an [OkHttp interceptor][1]. Not sure the Retrofit interceptors will have access to the full URL in 2.0 yet.

 [1]: https://github.com/square/okhttp/wiki/Interceptors

**Comment by JakeWharton** [comment]
The HTTP client interceptors or the current Retrofit's Client is where this should be done (HMAC). Logging is being tracked elsewhere (but also can be done with OkHttp's interceptors). The whole point of Retrofit is creating the request (including its interceptors) and handing it off to the client when completed. If you need the completed request, you need to be the client (be it `Client` or underlying HTTP client itself).

**Comment by dimsuz** [comment]
I am in similar situation as the OP: I need to pass an auth token based on whole url. So I cannot use `@Query String token` param, because it can be calculated only later.

Using interceptors as hinted above solves the problem, but only in the case when *all* methods of the service will use this interceptor which applies (&token=<hash>). 
In my case, however, only *some* methods will need token while others won't.

So I currently cope with that by separating those methods which must go without 'token' into a separate service which is configured with a 'clean' interceptor-less instance of OkClient.
And this feels a bit ugly because I have to separate services not by their logical functionality, but rather based on whether they need token or not.

If anyone could give me a hint on how to deuglify this, I'd be grateful :) Or maybe this is not the case to use Retrofit?

**Comment by swankjesse** [comment]
@dimsuz you could add a request header to all requests like this:

```
  Sign-Request: true
```

Then your OkHttp interceptor unconditionally _removes_ that header and either signs the request or doesn't.

**Comment by dimsuz** [comment]
@swankjesse oh, I thought about that, but then started to search for other ways and forgot. Seems like a good compromise: I can do something like 

`void myServiceCall(@Header("SignRequest") boolean signRequest, ...)`.

Thanks!

**Comment by swankjesse** [comment]
Yup. Or you can make the decision statically:
```
@Headers({
  "Sign-Request: true"
})
@GET("/")
```

**Comment by dimsuz** [comment]
Yes, ended up doing exactly this.
