### ISSUE TITLE
Is it possible to use query string arrays - e.g. a[]=2&a[]=3&a[]=4

### ISSUE THREAD

**Issue by benclayton** [square/retrofit#472]
A server for a project I've been working on uses the 'query array' syntax to pass an array of items in for a single named query key.

E.g.  a = {"2","3","4}  can be passed on the query string as a[]=2&a[]=3&a[]=4.

It looks like there's no way of doing this via the QueryMap function. Is there an alternative?

**Comment by smaspe** [comment]
Any particular reason why this is limited to
> The non-Map-based annotations
?

**Comment by JakeWharton** [comment]
See #626

**Comment by smaspe** [comment]
thanks

**Comment by alexnum** [comment]
Thanks a lot, i saved my task :)

**Comment by b95505017** [comment]
But what about two query string arrays?
e.g. a[]=2&a[]=3&a[]=4&b[]=2&b[]=3&b[]=4

**Comment by sudeeps-r** [comment]
@JakeWharton  Can you please tell me how i can pass array in GET request 

Format   http://www.xyz.com?ids=["1","2"];

**Comment by yljxcn** [comment]
haha

**Comment by NightlyNexus** [comment]
@sudeeps-r `Arrays.toString(strArr)` should give you that exact format. Just pass that as the value for the parameter.

**Comment by egpayawal** [comment]
Hi Guys,
How do you make this sample query on 2.0?
sample:
checkeditems[0][studentid]=249&checkeditems[0][checkvalue]=2&checkeditems[0][remarks]=sample remarks

and

attachfileuri[0]=http://www.planwallpaper.com/static/images/wallpaper-of-love.jpg

Thanks.

**Comment by Kolyall** [comment]
@egpayawal did you find solution? for 
sample:
checkeditems[0][studentid]=249&checkeditems[0][checkvalue]=2&checkeditems[0][remarks]=sample

**Comment by Mark-William-Schumacher** [comment]
@egpayawal @Kolyall and all others who may be looking for a possible solution to using Query string arrays with retrofit. To make that sample query you have listed above define your api call like so:

@POST("/api/blah")
public void apiCallMethod( @FieldMap Map<String,String> fields );

Now in the calling code for the apiCallMethod before making the request map the code like so...
`
   Map<String,String> fields = new HashMap<>();
    for (int i=0;i<users.size();i++) {
        User user= users.get(i);
        fields.put("user["+i+"][email]",user.email);
        fields.put("user["+i+"][password]",user.password);
    } 
`

Seems a little hacky, but it works. 
Credit goes to liangroger2007 on this http://stackoverflow.com/questions/27267593/how-to-post-array-parameters-with-retrofit

**Comment by Philipp91** [comment]
To avoid this `assignment_ids[]=[123, 234, 456]` and get the desired `assignment_ids[]=123&assignment_ids[]=234&assignment_ids[]=456`, you can alternatively pass in a multi map that implements `java.util.Map.entrySet()` to return a set with the desired entries of type `Entry<String, String>`. (In that case, the value type should actually be `String` and not `Object` because the same converter will be used for all items.

https://pastebin.com/NkAi63FK
Here's an implementation that takes arbitrarily nested objects (with arrays, sets, lists, ...), uses Gson to serialize them and then walks the Gson tree to construct the query string in the form of a custom `Map<String, String>`.

**Comment by efemoney** [comment]
Damn @Phillipp91. That is a great idea!
I needed to implement a `ids[]=2&ids[]=3&ids[]=6` kind of url with over 20 distinct keys of possible arrays (So using individual `@Query` arguments would have been painful to say the least). 

Implemented a builder that gathers all arguments but your clue was all I needed to cross the finish line. Thanks a lot. I will be implementing the equivalent of your pastebin in Java 7.

**Comment by fakir22** [comment]
I was facing the same issue as @efemoney and was struggling with @Philipp91 solution because I wasn't exactly sure of what to do. 

So here's @Philipp91 's QueryObjectConverter for Java 7 (no lambda expression) and without the need of an injection library (@inject) : https://pastebin.com/qVB3ZgDE

Then you can use it with something like this : 

`...

ArrayList<String> contractsParam = new ArrayList<>();
contractsParam .add("cdi");
contractsParam .add("cdd");

Map<String, List<String>> mulitpleQueryArg = new HashMap<>();
mulitpleQueryArg.put("contract_type", contracts);

QueryObjectConverter qConverter = new QueryObjectConverter(new Gson());
Map<String,String> convertedMap = qConverter.convert(mulitpleQueryArg);

....

foo.searchJobs(convertedMap);
`

Hope this helps !

**Comment by danielgomezrico** [comment]
If anyone is having trouble with that, I have my retrofit service like:

```
fun getContactsByNumbers(
        @Query("numbers[]") numbers: List<String>
    ) ...
```

and this sends the numbers like:

> <url>?numbers%5B%5D=111&numbers%5B%5D=333&numbers%5B%5D=444
> <url>?numbers[]=111&numbers[]=333&numbers[]=444

**Comment by jqgsninimo** [comment]
> @JakeWharton Can you please tell me how i can pass array in GET request
> 
> Format [http://www.xyz.com?ids=["1","2"]](http://www.xyz.com?ids=%5B%221%22,%222%22%5D);

Use Iterable to encapsulate the String list, or use a two-dimensional String array.

 - How to define:

       public interface XyzService {
           @GET(".")
           Call<Result> method1(@Query("ids") Iterable<List<String>> ids);
   
           @GET(".")
           Call<Result> method2(@Query("ids") String[][] ids);
       }

 - How to use:

       Retrofit retrofit = new Retrofit.Builder()
           .baseUrl("http://www.xyz.com")
           .addConverterFactory(GsonConverterFactory.create())
           .build();
       XyzService service = retrofit.create(XyzService.class);
       
       // Use the first method.
       List<String> data1 = Arrays.asList("1","2");
       Iterable ids1 = Arrays.asList(data1);
       Call<Result> method1Call = service.method1(ids1);
       
       // Use the second method.
       String[] data2 = new String[]{"1","2"};
       String[][] ids2 = new String[][]{data2};
       Call<Result> method2Call = service.method2(ids2);
       
       // Execute enqueue() or execute() of method1Call or method2Call.

**Comment by mtariquekhan** [comment]
I need to hit GET API in which I have to pass Query Param something like

student[][id]=1&student[][name]=ABC&student[][id]=2&student[][name]=XYZ

How should I pass the param?
