### ISSUE TITLE
URL syntax w/ query parameters enclosed in square brackets

### ISSUE THREAD

**Issue by mattlogan** [square/retrofit#556]
The URL String for a GET request from the Overpass API for OpenStreetMap looks like this:

http://www.overpass-api.de/api/xapi?way[highway=track][bbox=11.54,48.14,11.543,48.145]

It doesn't appear that Retrofit has any built-in way of handling this syntax -- either the the standalone "way" parameter or the query parameters enclosed in square brackets.

**Comment by rhonyabdullah** [comment]
Sorry @JakeWharton, Is that possible to achieve query with this url ?
`http:my-url:8080/product/70900?option[]=200936:4633&option[]=200179:3394`

Previously before using that above endpoint url i was using `@QueryMap` in order to hit this endpoint `http:my-url:8080/product/70900?option=200936:4633&option=200179:3394` with encoded = true and i got this result `http:my-url:8080/product/70900?option=200179:8054%26option%3D200936:4633` so i talked to our backend team that we should try to use square bracket like that first above endpoint pattern, reading this [issues](https://github.com/square/retrofit/issues?utf8=%E2%9C%93&q=bracket) i'm still confuse how to hit our new endpoint pattern with retrofit.

**Comment by NightlyNexus** [comment]
@rhonyabdullah `myServiceMethod(@Query("option[]") List<String> options)` should do what you want.
See the test: https://github.com/square/retrofit/blob/e27099390cac98877aed5360e22f0dff6c066bf7/retrofit/src/test/java/retrofit2/RequestBuilderTest.java#L1056
