### ISSUE TITLE
not convert interface Object to JSON

### ISSUE THREAD

**Issue by guileen** [square/retrofit#571]
I have a interface object `Location`,  provide `getNation`, `getProvince`, `getDistrict` method, only getter, no setter. But I can't seriealize the class Implemented the interface to the server.

LocationAdapter.java
```
public class LocationAdapter extends TypeAdapter<Location>{

	@Override
	public void write(JsonWriter out, Location value) throws IOException {
		System.out.print(".... write object....");
		out.beginObject()
		.name("city").value(value.getCity())
		.name("district").value(value.getDistrict())
		.name("nation").value(value.getNation())
		.name("provider").value(value.getProvider())
		.endObject();
	}
}
```

API define
```
@POST("/user/geo")
public void updateLocation(@Body Location location, Callback<Response> callback);
```

Create service
```
Gson gson = new GsonBuilder()
		.registerTypeAdapter(Location.class, new LocationAdapter().nullSafe())
		.create();


	RestAdapter restAdapter = new RestAdapter.Builder()
  	    .setConverter(new GsonConverter(gson))
	    .build();

```

**Comment by BobReid** [comment]
I ran into this issue trying to serialize a generic type. Gson was erroring not being able to resolve the type because json.toJson(object) is being called and not json.toJson(object, type). 

IMO the toBody method on the converter should include the Type just like the fromBody method. Unfortunately this a public API change like you said


```java
@Override public TypedOutput toBody(Object object, Type type) {
    ...
}
```

**Comment by JakeWharton** [comment]
@BobReid got a small test case?
