### ISSUE TITLE
How to handle java.net.UnknownHostException while using retrofit

### ISSUE THREAD

**Issue by leelei** [square/retrofit#644]
I'm using retrofit to get and post data from the server. However, if my phone loses internet connection in middle of the app then I see error like this:

<pre>
 java.net.UnknownHostException: Unable to resolve host "api.weibo.com": No address associated with hostname
            at java.net.InetAddress.lookupHostByName(InetAddress.java:457)
            at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
            at java.net.InetAddress.getAllByName(InetAddress.java:215)
            at com.squareup.okhttp.internal.Dns$1.getAllByName(Dns.java:29)
</pre>

I would like to handle this error gracefully. I would like to catch the exception and show a toast message like "No internet connection".

<pre>
 RestClient.get().getUser("uid", new Callback<User>() {
            @Override public void success(User user, Response response) {
            }

            @Override public void failure(RetrofitError error) {
                // when connection not available , i want to show a toast
                Toast.makeText(getActivity(), error.toString(), Toast.LENGTH_SHORT).show();
            }
        });
</pre>

**Comment by IgorGanapolsky** [comment]
It looks like `RetrofitError.Kind.NETWORK` also includes Uknown Host error.  So one would have to parse that error message string to determine its exact cause.

**Comment by MohammadFahimi** [comment]
Hi
I have the save error with Retrofit
now I also have HTTP FAILED: java.net.SocketTimeoutException 
other apps on my device works fine. but my app get this error. 
it occurs just when I am using wifi. but when I'm using other network it works fine.

**Comment by Mordag** [comment]
I have this issue also using the latest retrofit version (2.3.0) but the onFailure() is not called. What could I do without using 1.7 as mentioned above?

**Comment by timmutton** [comment]
Im seeing this as well (matter of fact, its my biggest cause of crashes currently). Is there any way to catch this error in 2.3 instead of it crashing?

**Comment by johnnyfivedev** [comment]
> onFailure() is not called

Same thing. And this "makes your life harder".

@JakeWharton any suggestions?

**Comment by gmiklos-inst** [comment]
This also affects Kotlin coroutines in such a way that it is not possible to handle any error related to name resolution because the exception is not propagated to the calling suspending function. This is a very similar problem that folks have here with onFailure() never called causing the whole application to crash.

One can definitely check whether there is network connectivity before making the calls but I still wonder whether that would only be a partial fix because name resolution can still fail in various ways despite being connected to a network. I also  cannot tell at the moment what other kinds of errors do not get propagated to the callers and instead crash the whole application.

**Comment by gmiklos-inst** [comment]
Ah, sorry. I misinterpreted what I have seen with my application. The exception does get propagated to the suspend function but the app process dies so fast than I'm not being able to do anything in the debugger. There is a direct correspondence between that suspending call and the whole application crashing. I do catch the exception but that does not prevent from the whole from crashing.

**Comment by gmiklos-inst** [comment]
Managed to resolve it. For me, the problem was that in some cases the kotlin coroutines library omits some data from stack traces and the actual problem was that there was a suspending call that was not wrapped in a try-catch call deep in the application code but this information was completely missing from the stack trace and only OkHttp's code was included in it.

The only way I could find this out was to register an uncaught exception handler and inside the exception handler observe the stack trace which indicated the error was from a suspending call that is not present in the stack trace whatsoever. 

All in all the issue was not with OkHttp in this case but I would suggest to improve upon the exceptions that get reported through the `await()` function in `KotlinExtensions.kt` to include the caller in the stack trace somehow.

**Comment by arunkbabu-l7** [comment]
> Managed to resolve it. For me, the problem was that in some cases the kotlin coroutines library omits some data from stack traces and the actual problem was that there was a suspending call that was not wrapped in a try-catch call deep in the application code but this information was completely missing from the stack trace and only OkHttp's code was included in it.
> 
> The only way I could find this out was to register an uncaught exception handler and inside the exception handler observe the stack trace which indicated the error was from a suspending call that is not present in the stack trace whatsoever.
> 
> All in all the issue was not with OkHttp in this case but I would suggest to improve upon the exceptions that get reported through the `await()` function in `KotlinExtensions.kt` to include the caller in the stack trace somehow.

This fixed my issue! Right when I fetch the data from the Data Source _(deep inside the application code)_ I need to wrap the method inside a `try-catch`  block to catch the error and handle it

This saved me a lot of time. Thanks for the solution @gmiklos-ltg  :)

**Comment by arunkbabu90** [comment]
> Managed to resolve it. For me, the problem was that in some cases the kotlin coroutines library omits some data from stack traces and the actual problem was that there was a suspending call that was not wrapped in a try-catch call deep in the application code but this information was completely missing from the stack trace and only OkHttp's code was included in it.
> 
> The only way I could find this out was to register an uncaught exception handler and inside the exception handler observe the stack trace which indicated the error was from a suspending call that is not present in the stack trace whatsoever.
> 
> All in all the issue was not with OkHttp in this case but I would suggest to improve upon the exceptions that get reported through the `await()` function in `KotlinExtensions.kt` to include the caller in the stack trace somehow.

This fixed my issue! Right when I fetch the data from the Data Source _(deep inside the application code)_ I need to wrap the method _(that fetches the data from the network using Retrofit)_ inside a `try-catch`  block to catch the error and handle it

This saved me a lot of time. Thanks for the solution @gmiklos-ltg  :)

**NB:**  You can use  `instanceof`  in java or  `is`  in Kotlin to check if the exception is 
 **UnknownHostException**  inside the  `catch`  block and show more fine-grained messages to the user
