### ISSUE TITLE
Feature Request: Add Ability to Generate Link using Interface

### ISSUE THREAD

**Issue by mrcritical** [square/retrofit#648]
It would be really helpful if we could generate a URL/link from the same interface used for calls. This would be very helpful for HATEOS support. So it doesn't actually making the HTTP request, but just returns the URL that would have been used to do so.

**Comment by JakeWharton** [comment]
I see no way to support this currently.

Retrofit's interface declarations are about creating requests, not URLs. The URL aspect is a part of it, yes, but the majority of the annotations and features are around the other aspects of requests (headers, body, and the various serialization mechanisms). Moreover, the return type or callback of a method is strongly typed to the response which provides no means of supporting both creation of a URL as well as handling the normal HTTP response representation.

However, in 2.0 there will almost certainly be a `Call` abstraction which is returned which _will not_ actually execute the request. With this `Call` you'll be able to retrieve the yet-unexecuted request object which will have a URL. This means that you can call interface methods to create a `Call` and then yank the corresponding URL out of it having never ran it and under no obligation to.

Look for that in the next few months. Closing this out since the explicit feature cannot be supported directly.
