### ISSUE TITLE
Conversion error on empty body in response

### ISSUE THREAD

**Issue by johan-miller** [square/retrofit#698]
Retrofit version 1.8.0.

I have a query which in some cases returns a response body and other cases has an empty response body. Currently it seems that Retrofit RestAdapter does not correctly handle empty response body. I would expect a null object to be returned by RestAdapter perhaps around line 353 but currently the empty body is being passed to a converter on line 362 (JacksonConverter in my case) which then throws a JsonMappingException since the InputStream is empty. Maybe line 353 should be changed to also check the length of the body and if it is 0 then return null? I also thought about creating a local JacksonConverter to return null on content with length 0 but then logResponseBody on line 363 would throw a NullPointerException when logging is turned on.

**Comment by cachapa** [comment]
We had the same problem. In our case the API always returns an empty body for POST and DELETE requests, using only the status code for feedback.

We managed to solve our particular case by setting the return type to retrofit.client.Response, which according to the documentation gives us the raw data, thereby skipping the conversion attempt.

In any case this seems to be a valid bug since conversion shouldn't be attempted on an empty body.

**Comment by JakeWharton** [comment]
Empty body is valid. The converters need to handle this, not Retrofit.
