### ISSUE TITLE
Malformed JSONException for lenient or unquoted json content 

### ISSUE THREAD

**Issue by ghost** [square/retrofit#700]
Json conent that parses fine when using a Gson parser, throws the above exception , MalformedJSonException (by RetroFitError) when trying to read the content. Is there a way how JSonReader.setLenient(True) can be set?
Or somehow the unquoted or relaxed Json content  at the url that is being passed, needs to be validated.. Any help?

**Comment by gangeshwari** [comment]
yup.. i know Gson is lenient otherwise, but was wondering why it was not
able to parse the highlighted line of code:
The value2colour has a value that is a function( the exception is thrown
here after function (x)  when the *{ *begins. any steps on how exactly this
needs to be passed?

color:{binCount:7,value2color:function (x) { var y = Math.log(x)*0.25
+ 1;  return (y < 0 ? 0 : y); }},


Thanks

**Comment by JakeWharton** [comment]
That's not really JSON. That's just Javascript.

**Comment by gangeshwari** [comment]
ok.. thanks
