### ISSUE TITLE
Executor/Rx Scheduler of Retrofit Observable

### ISSUE THREAD

**Issue by jondwillis** [square/retrofit#715]
From Retrofit's documentation:

> Observable requests are subscribed asynchronously and observed on the same thread that executed the HTTP request. To observe on a different thread (e.g. Android's main thread) call observeOn(Scheduler) on the returned Observable.

My understanding is that in RxJava, a ```Scheduler``` is backed by an ```Executor```, and Retrofit allows you to change the default ```Executor```s of a ```RestAdapter``` using ```setExecutors()```. However, if I wanted all Retrofit HTTP operations to happen on the same Executor as, say, Schedulers.io(), how might that look? One option that comes to mind is to create a new ```Scheduler.from(myExecutor)``` and then use ```setExecutors(myExecutor, ...)```, but that creates extra Executors/Schedulers that need to be managed in client code.

Is my thinking on this overblown?

**Comment by JakeWharton** [comment]
This stuff is currently in the process of dying on `master`. The threading model of Retrofit is 4 years old. It predates OkHttp 2.0 which can manage threads more intelligently than Retrofit and it pre-dates RxJava which brought the `Scheduler` to which you refer.

Retrofit is changing such that it will no longer own the threading model of the HTTP request (at least not in the core like it does now).

> in RxJava, a `Scheduler` is backed by an `Executor`

This usually is not true. Schedulers execution behavior is much better served when it manages threads  and queued jobs directly. You can make a `Scheduler` from an `Executor`, but it will be less efficient at performing work.

I'm closing this because the Retrofit you know today is dying. The RxJava integration will behave much differently in the next major version to allow composition of requests without the scheduling problems that happen today as a result of setting the background scheduler by default.
