### ISSUE TITLE
Modify Callback interface

### ISSUE THREAD

**Issue by daimonkor** [square/retrofit#741]
Please add function 
```java 
void onstart(String url);
```
when RestHandler started request, 
```java
 void onfinish(String url);
```
 when finished request (with success or fealure result).
I will use it for show/hide loading view. Thanks

**Comment by JakeWharton** [comment]
You can do this yourself. Start is the same as when you call the Retrofit method so you can show the loading view whenever that happens. Finish is whether either the success or failure callback is called. If you want a common handler, use a callback baseclass instead of the interface which has the common finish method that is invoked for both.

**Comment by daimonkor** [comment]
I can not add onstart/onfinish function to Callback interface, because I can not create custom RestAdapter (modify invoke function), so for example I have 10 request at activity and I call onstart/onfinish for every request. It is uncomfortably. Please add functions

**Comment by JakeWharton** [comment]
```java
public abstract class StartStopCallback<T> implements Callback<T> {
  StartStopCallback() {
    onStart();
  }

  public final void onSuccess(T body, Response response) {
    onSuccess2(body, response);
    onFinish();
  }

  public final void onFailure(RetrofitError error) {
    onFailure2(error);
    onFinish();
  }

  public abstract void onStart();
  public abstract void onFinish();
  public abstract void onSuccess2(T body, Response response);
  public abstract void onFailure2(RetrofitError error);
```

**Comment by daimonkor** [comment]
Thank you very much
