### ISSUE TITLE
0-byte response returns as null, and skips the converter

### ISSUE THREAD

**Issue by jnlopar** [square/retrofit#746]
Looks like retrofit turns empty responses into nulls. There are some valid cases for converting an empty response, particularly in decoding a protocol buffer, since a valid 'default' proto message would be an empty response body.

It appears to be nullifying here: https://github.com/square/retrofit/blob/master/retrofit/src/main/java/retrofit/RestAdapter.java#L294

**Comment by casidiablo** [comment]
I think it's not a retrofit problem. Rather, the converter you are using could be unmarshalling the response as `null`. It shouldn't be a problem to workaround though. What converter are you using?

**Comment by jnlopar** [comment]
The converters never get called in the empty case, since retro won't call a converter with a null response.

**Comment by casidiablo** [comment]
My bad. I thought the problem was after that. In that case, it's the HTTP client fault. Are you using okhttp?

**Comment by jnlopar** [comment]
Yes. I use the default client. Someone else I'm working with tried with both a default and a custom client. This was discovered while attempting to upgrade to 1.9.0. It handles empty responses fine on 1.6.0.

**Comment by eheilm** [comment]
More details:

In 1.6, an empty object was correctly returned.

In 1.9, there is [OkClient](https://github.com/square/retrofit/blob/c175b65d9387e455eb52ad77ce61ca6858606542/retrofit/src/main/java/retrofit/client/OkClient.java), in which, an early return returns null if the body is of 0 length. Later,  the converter never gets a chance to return an empty object.

That class has since been deleted/moved. So I don't know for sure where this behavior is in 2.0+, but I did appear to still run into it.

**Comment by JakeWharton** [comment]
A 0-byte 200 should go to the converter. A 204 and 205 will skip the converter (#735).

**Comment by joe-spanning** [comment]
What about a 201? Does it go to the converter?

**Comment by joe-spanning** [comment]
Nevermind, I misread the status code definition for 201.

**Comment by JakeWharton** [comment]
This was fixed on `master` weeks ago. The behavior will change for 2.0.
