### ISSUE TITLE
Add first-party LoganSquare converter.

### ISSUE THREAD

**Issue by jfragosoperez** [square/retrofit#762]
I had in mind to build a LoganSquare converter, but checking if you had already done it, I have seen that you are working on changes for next release, talking about the converters part. I was wondering if you have already a fixed date for the update or you have to deal with many other milestones before releasing. I wait for your feedback. Thanks a lot

**Comment by JakeWharton** [comment]
Go for it.

**Comment by jfragosoperez** [comment]
I will try to find some time to work on this over weekend. Keep you updated

**Comment by sockeqwe** [comment]
Found [that](https://gist.github.com/aurae/8427b93b27483763d9cb)  at https://github.com/bluelinelabs/LoganSquare/issues/5 

Looks good so far and works for me

**Comment by jfragosoperez** [comment]
I already saw this @sockeqwe , but the thing is that it works for the current version of retrofit, but it won't work for next version, as some base in the converters has changed

**Comment by jfragosoperez** [comment]
Alright, in this case I will try to find some time to work on this during next week. Thanks @JakeWharton

**Comment by aurae** [comment]
Proposed in Pull Request #988

**Comment by JakeWharton** [comment]
We aren't going to be adding any more JSON converters. Copying a response I put on another PR for explanation:

Retrofit already offers 3 first-party JSON converters. Gson and Jackson are the two leading serializers for which we offer converters, and we include Moshi just because it's a Square library. Similarly, we have two first-party protocol buffer converters, one using the official library and one with Wire because it's a Square library. We have a single XML converter because... well no one really knows.

There are many more eclectic and specialized JSON converters just as there are for other serialization formats. Maintaining a bunch of these is burdensome as we have to track the APIs and changes in 6 external libraries which have nothing to do with Retrofit's core. I can think of at least 5 other JSON libraries that have popped up recently almost always just being built on top of Jackson or Gson.

Retrofit was modified (by me, actually) to be agnostic to converters well before it hit 1.0 a few years ago. The point was that as libraries and formats change in popularity, no changes in Retrofit would be needed to support them. This is very much the case with the forthcoming version 2.0 as well.

As such, we won't be adding any more first-party converters unless a compelling reason can be made as to why we should. Since we already have 3 JSON converters, there is little argument to be made for more.

However, there's no reason that these cannot be turned into third-party libraries that exist on their own. I have [made a wiki page][1] for listing third-party converters so that they are able to be discovered in one place.

Thanks for taking the time to implement this, despite that fact that we aren't able to accept it into the main repo.

 [1]: https://github.com/square/retrofit/wiki/Converters

**Comment by aurae** [comment]
@jfragosoperez @sockeqwe Version 1.0.0 of the LoganSquare converter has been released [and added to the wiki](https://github.com/square/retrofit/wiki/Converters)! Further maintenance will happen in its dedicated repository from now on.

**Comment by sockeqwe** [comment]
Awesome! Thanks!

**Comment by filipebezerra** [comment]
Awesome. Thanks @aurae for your contribution
