### ISSUE TITLE
Populate Android ListView successively as data load

### ISSUE THREAD

**Issue by mKontakis** [square/retrofit#790]
Is it possible to populate a ListView successively as data load?
I know that this is possible with AsyncTask's method onProgressUpdate  but i would like to use Retrofit.
The data i want to load onto the ListView are a lot, thats why i want to use that option if possible.

What i want to do implemented with AsyncTask:
http://stackoverflow.com/questions/15381806/how-to-update-listview-in-onprogressupdate

**Comment by JakeWharton** [comment]
No. Retrofit waits until the configured `Converter` returns an object instance until returning it to the caller. Normally this operation is so fast that it makes no difference.

Are you responses so large that you cannot wait for the entire thing to deserialize?

**Comment by mKontakis** [comment]
I can wait but this would make the app more efficient

**Comment by JakeWharton** [comment]
Actually it makes the app less efficient since you spam the main thread's
handler and force your ListView to incrementally inflate, bind, measure,
and layout each of the first individual items and then constantly spam
notifyDataSetChanged despite the items not be visible. I suspect your app
degrades in performance while this is happening whereas a single update
will only cause the work to happen once.

**Comment by mKontakis** [comment]
Thanks for the useful tip Jake. I'm still new to Android world. I will stick to your solution. Thanks
