### ISSUE TITLE
Adding configurable timeouts?

### ISSUE THREAD

**Issue by mattylase** [square/retrofit#813]
I wondered if there was any interest in adding configurable timeouts to `Platform#defaultClient` through `RestAdapter.Builder` (aside from using `setClient`)? I figure there is a methodology in separating the functionality of OkHttp & Retrofit, but I thought this would be handy when creating adapters.

**Comment by JakeWharton** [comment]
The only reason we provide default timeouts is because clients have stupid defaults (that is, no timeouts by default). Additionally, not every client supports the same amount of timeouts (connect, read, write). For v2 we're only supporting OkHttp as the client which makes it very easy to set timeouts and I think the HTTP client is exactly where this belongs. Retrofit's job is simply mapping Java interfaces to HTTP calls on the underlying client, the configuration of that client can be kept wholly separate.
