### ISSUE TITLE
Apply field naming policy to @Part argument

### ISSUE THREAD

**Issue by johnjohndoe** [square/retrofit#818]
I noticed that the `FieldNamingPolicy` from [Gson][gson] or `PropertyNamingStrategy` from [Jackson][jackson] is **not** applied to the name of the `@Part` argument.

I use *underscores* for parameters in the server JSON API. It would be handy if *camelcase* strings in the Java client would be **automatically converted** to underscores as dictated by one of the above mentioned settings.

[gson]: https://github.com/google/gson
[jackson]: https://github.com/FasterXML/jackson

**Comment by JakeWharton** [comment]
The parameter name is not used at all and is arbitrary. Are you referring to the string value inside of `@Part`? This isn't surfaced anywhere in the API, calling code, or Javadoc of the method so you should be using the underscore version there since that's what the server expects.

Even if you don't buy into that, this can never be done since Gson or Jackson might not be available (similar to #711). We don't use Retrofit with Gson or Jackson in our apps. The converter is only used for serializing object instances and it's completely opaque to the other parts of Retrofit. Surfacing behavior from the converter to other parts would not only conflate its purpose, but also has strange applicability on different serialization mechanisms. How does it work when I'm using XML or protocol buffers or even just plain text? There's simply too much room for corner cases and conditional behavior to make this make sense.

**Comment by johnjohndoe** [comment]
Okay. Thank you for your feedback.
