### ISSUE TITLE
Setting a request's priority

### ISSUE THREAD

**Issue by mrmaffen** [square/retrofit#820]
Hey guys,
first of all: Great work so far! Keep it up :)

Here's my problem:
In my app I want to run some long syncing operations in the background while still being able to use Retrofit to fetch other data from my API. Currently the syncing operations block Retrofit completely for (in some cases) over 60 seconds which means that no other data can be fetched in the meantime. This is obviously not acceptable wrt UX.
I couldn't however find an easy way to set a request's priority with Retrofit. I'd love to see a feature like this to be implemented. If I could simply annotate the type of request in my API interface with some priority value, that would be great.

Thanks!

**Comment by mrmaffen** [comment]
Here's my workaround/solution:
```java
Executor httpExecutor = Executors.newCachedThreadPool(new ThreadFactory() {
    @Override
    public Thread newThread(final Runnable r) {
        return new Thread(new Runnable() {
            @Override
            public void run() {
                android.os.Process.setThreadPriority(THREAD_PRIORITY_LOWEST);
                r.run();
            }
        }, "Retrofit-Idle-Background");
    }
});
restAdapter = new RestAdapter.Builder()
        .setExecutors(httpExecutor, new MainThreadExecutor())
        .build();
mImplementation = restAdapter.create(API.class);
```

I can now use mImplementation for my sync operations. Even though this is obviously not an optimal solution, since I use 2 ThreadPools and prioritize the Thread instead of the actual Runnable, it still works fine as a temporary workaround it seems.

**Comment by JakeWharton** [comment]
> Currently the syncing operations block Retrofit completely for (in some cases) over 60 seconds which means that no other data can be fetched in the meantime.

Are you sure this happens? Retrofit uses an unbounded pool of threads so we'll happily execute multiple request concurrently.

Definitely looking for more info regarding the above, but I'm going to close this issue for now because:

Retrofit v2 is pushing the threading model down into the HTTP client rather than having its own. This will increase throughput as well as allow the HTTP client to do smarter things such as limiting per-server connections to a specified amount or multiplexing requests over a single connection with HTTP/2.
