### ISSUE TITLE
How to setup a retrofit call to do automatic retries on a GET

### ISSUE THREAD

**Issue by inder123** [square/retrofit#828]
For a GET operation, I want to be able to specify that retry it 3 times with a 500ms wait in between.

Is this already possible? If so, documentation will be quite helpful. Thanks.

**Comment by DSteve595** [comment]
You'd probably do this through setting the HTTP client, I think OkHttp supports this. Also, ask things like this on StackOverflow, not as a bug on the project.

**Comment by inder123** [comment]
Sure. I created the issue to add the documentation to the retrofit page at http://square.github.io/retrofit/, or to implement the feature if it is worth doing. Go ahead and close the issue if neither is a possibility.

**Comment by JakeWharton** [comment]
What you describe is an application-level policy that must be implemented by the application. Retrofit exists solely as a mechanism for creating requests from high-level Java objects, executing them on the underlying HTTP client, and marshaling the response back to high-level Java objects.

Policy like what you describe is vast and subjective. Thus, it's very hard to implement in any useful way with a reasonable API so we simply choose not to. This policy is much easier to implement at the application level because it doesn't need to be generalized and it can use additional information from the response to affect policy.

**Comment by JakeWharton** [comment]
Or, as suggested, you could have an HTTP client transparently implement this. OkHttp's interceptors come to mind, but then such policy applies globally to every request made.

**Comment by inder123** [comment]
Ok, that makes sense. Thanks Jake and DSteve

**Comment by SamiKh94** [comment]
@JakeWharton is it possible to re-execute a pre-defined Observable? 

`https://stackoverflow.com/questions/47619115/how-to-retry-a-consumed-observable`?

**Comment by JakeWharton** [comment]
Subscribe to it again.
