### ISSUE TITLE
Feature Request: Request queuing in the absence of internet/request batching

### ISSUE THREAD

**Issue by behl1** [square/retrofit#833]
Hello,

Firstly, thanks for your amazing support and work on Retrofit and other Android libraries. They rock!
Secondly, apologies in advance if this feature is already in place, but I could not find anything about such a case anywhere.

I want to be able to batch requests/queue them in the absence of internet. Is it possible to do this with the existing structure of retrofit or okhttp? It'll be a boon.

Cheers.

**Comment by JakeWharton** [comment]
This is a complicated task with many different requirements and application needs that I don't think we can address at this time–or maybe ever.

Some people will not want this which is obvious and we would presume that this would be opt-in. But in designing the system that would accommodate what you describe for the reset, there are just tons of things to consider.

 * How will the requests be batched? Per-endpoint or all calls? What if only some requests we care about success and others we dont?
 * What happens if the same request is made twice? Do we merge them? Ignore the second?
 * Do we persist the failed requests? What mechanism do we use (file, sqlite)? What serialization format? What if the objects are not able to be serialized or transient? What if the data is private and shouldn't be persisted?
 * When do we retry? What's the number of attempts and what backoff rate do we apply?

As you can see there is so many things to consider to design a system that's usable for everyone.

Now, if you were building a system for a specific application, you have answers to all of these questions and can hard-code everything to be specific to what you want. This is the much better approach and there are libraries out there that help. Path has a job queue, Android has a built-in job queue now, we have a library called Tape. These all do very different things to solve part of this problem.

To reiterate my first sentence, this is complicated and Retrofit isn't the right place to solve it.

**Comment by behl1** [comment]
Hey Jake,
Thanks for your in-depth answer. It is a very complicated problem and I understand why you would not want to solve it with Retrofit.

Cheers.
