### ISSUE TITLE
No response (also no error) in chained/nested rxjava callbacks

### ISSUE THREAD

**Issue by adi1133** [square/retrofit#835]
This happens if you can together multiple Api calls using operators like switchMap, flatMap or concatMap.
I get no output from Retrofit and my code is stuck waiting for a response.
By no output I mean that none of the subscriber's methods get called(onNext, onError or onComplete)

Possible solutions for others who have the same issue:   

  - use the timeout operator from rjxava, or 
  - invoke the nested api calls from other threads than the ones that retrofit provides. You can do this by using the observeOn operator (any threadpool is ok, including using the UI thread)

Sample project that reproduces this issue and shows how to use a workaround to avoid the bug
https://github.com/adi1133/Retrofit-Issue

**Comment by JakeWharton** [comment]
Not quite sure the cause here. When I debug it succeeds. The third API request is definitely subscribed to and from what I can tell its enqueued to the executor successfully which creates a new thread but that thread never runs (hence the API call is never made).

Was only debugging with the immutable sources from the Retrofit dependency. I'll have to load up Retrofit from source so I can add more logging at some point.

**Comment by GNima** [comment]
Experiencing the same issue when combining api calls with `zip`. 

```apiClient.getUserProfile().zipWith(apiClient.getUserBalance(), ....).subscribe(...);``` never initiates retrofit network calls, therefore no onNext, onError or onComplete is called

**Comment by adi1133** [comment]
if I use **subscribeOn(Schedulers.io()).concatMap(**... it seems to cause a timeout exception.
