### ISSUE TITLE
retrofit & okhttp & gson

### ISSUE THREAD

**Issue by a464538715** [square/retrofit#878]
```
OkHttpClient client = new OkHttpClient();
        int cacheSize = 10 * 1024 * 1024; // 10 MiB
        File cacheDirectory = new File(getCacheDir().getAbsolutePath(), "responses");
        if (!cacheDirectory.exists()) {
            cacheDirectory.mkdirs();
        }
        final Cache cache = new Cache(cacheDirectory, cacheSize);
        client.setCache(cache);
        mRestAdapter = new RestAdapter.Builder()
                .setEndpoint(Constants.BASE_URL)
                .setClient(new OkClient(client))
                .build();
```
this is my code, i want to read cache when offline, but it doesn't work.

```
new Callback<PublicTimeLine>() {
                    @Override
                    public void success(PublicTimeLine publicTimeLine, Response response) {
                        closeRefresh();
                    }

                    @Override
                    public void failure(RetrofitError error) {
                        closeRefresh();
                    }
                });
```
and i also don't know how which method to handle cache if i can get cache

**Comment by a464538715** [comment]
Is there some good samples? I want to learn

**Comment by JakeWharton** [comment]
Retrofit is just asking the OkHttp client for the resource every time. If the cache is installed in the client *and* the response from a previous request had headers that indicated it was cacheable *and* those headers indicate that the cached value was still valid at the current time you will get the response. If you want true offline mode you will need to keep your own cache that you manage (e.g., in a database).

Usage questions are much better asked on StackOverflow. Each of these three projects has a tag you can include in order to target the right developers. In addition to that, StackOverflow is a much better place to search and archive usage questions, as well as discuss the merits of various approaches.
