### ISSUE TITLE
Internet connection

### ISSUE THREAD

**Issue by mistrydarshan99** [square/retrofit#883]
Hello,

I have to used this library in my project but issue is i cannot check internet connection.I have got error no host found when my internet is off.So how to check internet connection before request api.

**Comment by zhakid** [comment]
You need to use a interceptor

**Comment by JakeWharton** [comment]
This depends on the platform. If you are on Android you can use http://developer.android.com/training/monitoring-device-state/connectivity-monitoring.html#DetermineConnection. In practice, though, you need to handle these error states regardless because the connection may drop in the middle of a connection.
