### ISSUE TITLE
MockRestAdapter try to reach real endpoint

### ISSUE THREAD

**Issue by danielgomezrico** [square/retrofit#941]
I´m trying to mock my server but I found that MockRestAdapter goes to the endpoint.
```
MockRestAdapter mockRestAdapter = MockRestAdapter.from(ApiManager.REST_ADAPTER);
mockRestAdapter.setDelay(0);
```

and then 

```
MockService mockService = new MockService();
MyModel.SERVICE = mockRestAdapter.create(Service.class, mockService);
```

And it works, I mean, it mock the Service with my mockService responses but it still try to reach the RestAdapter end point, so if I don´t have internet it breaks, if It´s not fine authenticated breaks, then it dosen´t make sense.

What I am doing wrong? what´s the point of MockRestAdapter?

**Comment by JakeWharton** [comment]
This can't happen. The instance returned by `create` has no way of calling through to the real implementation which would hit the network.

Can you write a test case that demonstrates this?

**Comment by danielgomezrico** [comment]
Sure, I use it like this:

```
@RunWith(AndroidJUnit4.class)
@LargeTest
public class MainDrawerActivityTests {

    @Rule
    public ActivityTestRule<MainDrawerActivity> mActivityRule = new ActivityTestRule<>(MainDrawerActivity.class);

    @Before
    public void setup() {
        Customer.clearPreferences();
    }

    @Test
    public void openOrderShowBookedTitleAndCard() {
        MockRestAdapter mockRestAdapter = MockManager.getRestAdapter();
        MockCustomerService mockCustomerService = new MockCustomerService();
        mockCustomerService.setSession("session_token);
        Customer.SERVICE = mockRestAdapter.create(CustomerService.class, mockCustomerService);

        isDisplayed(R.id.status_card_open);
        toolbarHasTitle(getString(R.string.status_open));
    }

}

public class MockManager {

    public static MockRestAdapter getRestAdapter() {
        MockRestAdapter mockRestAdapter = MockRestAdapter.from(ApiManager.REST_ADAPTER);
        mockRestAdapter.setDelay(0);
        return mockRestAdapter;
    }

}


@VisibleForTesting
public interface CustomerService {

    @POST("url")
    Observable<Session> createSession(@Body Credential credential);

}

public class ApiManager {
	public static RestAdapter REST_ADAPTER;

	static {
	    OkHttpClient okHttpClient = new OkHttpClient();
	    okHttpClient.setConnectTimeout(30, TimeUnit.SECONDS); // Initial value: 10
	    okHttpClient.setWriteTimeout(30, TimeUnit.SECONDS);
	    okHttpClient.setReadTimeout(30, TimeUnit.SECONDS);

	    REST_ADAPTER = new RestAdapter.Builder()
            .setEndpoint(host)
            .setRequestInterceptor(new SessionRequestInterceptor())
            .setConverter(new GsonConverter(JsonHelper.GSON))
            .setClient(new OkClient(okHttpClient))
            .setErrorHandler(new MyErrorHandler())
            .setLog(Timber::d)
            .build();
    }
}

public class Customer implements Serializable {

    @VisibleForTesting
    public transient static CustomerService SERVICE = ApiManager.REST_ADAPTER.create(CustomerService.class);

}

public class MockCustomerService implements CustomerService {

	private String mSession;

    @Override
    public Observable<String> createSession(@Body Credential credential) {
        return Observable.just(mSession);
    }

}
```

**Comment by JakeWharton** [comment]
Just guessing since I can't run this, but the activity rule is going to start the activity before the test runs. This means that by the time you try to replace the `SERVICE` instance it's too late, the activity has already made a request with the real service.

Either pass `true, false` as the second and third argument to the [rule's constructor][1] and call `mActivityRule.launchActivity` after changing the service or move the code that configures the mock service to happen in `@Before` (although you might find that the activity has already started, I'm not sure).

This is a usage problem than a bug. StackOverflow and our 'retrofit' question tag is a better place for general usage questions like this, but I understand it's not that well documented and can be complicated. I'm closing this for now, but feel free to continue asking questions and I'll do the best I can do answer.

 [1]: http://developer.android.com/reference/android/support/test/rule/ActivityTestRule.html#ActivityTestRule(java.lang.Class<T>, boolean, boolean)

**Comment by danielgomezrico** [comment]
:+1: thanks it worked and excuse me for posting it here, thought it was a bug but yeah, complete misunderstood about what was happening.
