### ISSUE TITLE
Exceptions emitted in Rx Subscription onError()s are silently swallowed

### ISSUE THREAD

**Issue by orospakr** [square/retrofit#955]
If my onError throws an exception, then it is silently swallowed:

```kotlin
        val kaseNetworkClient = rest.create(javaClass<KaseRetrofitClient>())

        kaseNetworkClient.myRestMethod().subscribe(
            { kase: Kase ->
            throw RuntimeException("Initial error")
        }, { error ->
            Log.e(LOG_TAG, "This message appears in the log just fine!")
            throw RuntimeException("And now, as the dev, I've screwed the pooch twice and crashed in my error handler!")
        })
```

The above results in no visible effects.  No log messages, no app crashes, nothing.  If I replace the Retrofit observable with with a simple cold subject, such as `Observable.just(1)`, then the expected crash behaviour happens.  I'm not sure if this is a Retrofit bug, an Rx/RxAndroid bug, or an interaction.  I figured this would be the best place to report it first, though!

This is particularly painful because the single-Action version Observable's subscribe() uses an implementation of Subscription that throws a NotImplementedException from its `onError`.

**Comment by orospakr** [comment]
A great workaround (and something one shoud typically be doing in a lot of cases, anyway), is to be ensure that you run schedule your observer on the main thread. In this way, if your Subscription throws an exception, it doesn't get thrown back up into Retrofit:

```
... retrofit proxy call expression...
.observeOn(AndroidSchedulers.mainThread())
```

**Comment by JakeWharton** [comment]
When you throw in a subscriber there's not a lot RxJava can do. These are sent to the thread's uncaught exception handler. Retrofit uses an Executor for running requests whose uncaught exception handler does nothing.

If you want a crash, pass in an HTTP executor with a thread factory that installs an uncaught exception handler which crashes your app. In Retrofit 2 we've gotten rid of the HTTP executor and instead use OkHttp's built-in async execution. I'll have to test its default behavior for exceptions thrown on the callback threads.

In either case, this isn't a Retrofit problem, per-say. Throwing in a subscriber is very bad because you leave RxJava few choices on what to do, but this is common to _all_ RxJava not just Retrofit.
