### ISSUE TITLE
Retrofit 307 Temporary Redirect

### ISSUE THREAD

**Issue by mistrydarshan99** [square/retrofit#968]
I have used retrofit for networking in my project in android.I have got Retrofit 307 Temporary Redirect. How to resolve it ?

**Comment by JakeWharton** [comment]
The HTTP client should handle redirects. Are you using one that does (like OkHttp)?

Otherwise, you need to read the `Location` header and issue a request to the new URL. Retrofit really isn't set up to do this (although the forthcoming version 2 will make it possible). This is why we rely on the HTTP client to follow redirects.

**Comment by lotfi10** [comment]
I have used retrofit for networking in my project in android.I have got this Error when I make a POST request:
failure : retrofit.RetrofitError: 307 Temporary Redirect

I add to line in gradle like that:

 compile 'com.squareup.retrofit:retrofit:1.9.0'
 compile 'com.squareup.okhttp:okhttp:2.4.0'
**************************************************************
How to resolve it ?
