### ISSUE TITLE
Backwards compatibility?

### ISSUE THREAD

**Issue by jjshanks** [square/retrofit#987]
It looks like the changes for v2 are going to break the existing API. For example SimpleXMLConverter is public in 1.9.0 but the current code has it as package private with this change https://github.com/square/retrofit/commit/fe6d0f9b2a68063a086fa9da80d04293fbe3becf#diff-2f965284db1eb8ed59e161694f170ff3

Other things like removing the ability to specify the charset in the gson converter seem like things people might depend on.

It'd be nice to maintain backwards compatibility and if not shouldn't v2 be it's own repo like retrofit2 to allow for fixes in v1?

**Comment by JakeWharton** [comment]
> It looks like the changes for v2 are going to break the existing API.

Yes, it will break everything–and that's exactly the point! I am fixing all the horrible mistakes that were made over the past 4 years (mostly by me).

> For example SimpleXMLConverter is public in 1.9.0 but the current code has it as package private

All of the converter types are now implementation details in favor of converter factories which create converter instances for a single type. This is a giant win in practice since the types never change and we can cache these instances.

> Other things like removing the ability to specify the charset in the gson converter seem like things people might depend on.

The Gson converter now uses the charset specified in the content type which was a mechanism we did not have back when the custom charset feature was added.

> It'd be nice to maintain backwards compatibility

No compatibility will be attempted.

> shouldn't v2 be it's own repo like retrofit2 to allow for fixes in v1?

The version 1 code is still in the history, but just about every remaining bug is a design flaw. Unless something extraordinary comes up, 1.9.0 was the last v1 release.

Think of v2 as one giant fix for the bug that was v1's design.

**Comment by tvietinghoff** [comment]
I am currently facing an issue with using Fabric's TwitterKit/TwitterCore which has a dependency on v1, in combination with v2, which I am using for my own code. Since v2 of retrofit wins gradle's dependency resolution, TwitterCore crashes when trying to instantiate the now gone RestAdapter.Builder with a ClassNotFoundException. 

How can I solve this? I don't think I can bet on Fabric to rebuild TwitterKit with retrofit v2 anytime soon.

**Comment by tvietinghoff** [comment]
Never mind, I just found the https://github.com/square/retrofit/issues/1152 which discusses this already.
