### ISSUE TITLE
Make possible return Response object in case of error response

### ISSUE THREAD

**Issue by avarabyeu** [square/retrofit#989]
Basically, i need possibility to specify some custom error handler which is not throwing exceptions. 
I would like to obtain Response object and decide by yourself whether throw exception or not. For now, if ErrorHandler return null instead of exception, IllegalStateException is appeared.

**Comment by caseykulm** [comment]
```
public RestAdapter.Builder setErrorHandler(ErrorHandler errorHandler)

The error handler allows you to customize the type of exception thrown for errors on synchronous requests.
```

**Comment by avarabyeu** [comment]
@caseykulm ErrorHandler has the following method signature:

 Throwable handleError(RetrofitError cause);

So, you need to return Throwable. In my case i don't need any exception to be thrown. I need Response object to be returned even if status code is 4xx or 5xxx

**Comment by caseykulm** [comment]
[`RetrofitError#getResponse()`](http://square.github.io/retrofit/javadoc/retrofit/RetrofitError.html#getResponse--) has the response, it will simply be routed to onError instead of onSuccess. If you use the ErrorHandler to convert the specific error responses you still want to use to a class that you can call instanceof on in onError then you can pipe those responses on to the same code you pipe onSuccessResponses to.

**Comment by JakeWharton** [comment]
So this remained open because it would have been a breaking change. The error handling mechanism changed in v2.0 and this change is no longer needed. When a response is received, it is always returned to the caller even in non-200 cases.
