### ISSUE TITLE
MockRestAdapter should support ErrorHandler for asynchronous calls.

### ISSUE THREAD

**Issue by vgonda** [square/retrofit#999]
When `ErrorHandler` was updated to support asynchronous calls (#439) `MockRestAdapter` [wasn't updated](https://github.com/square/retrofit/blob/00f4c420166eb070a035cdd641b7afa101f65602/retrofit-mock/src/main/java/retrofit/MockRestAdapter.java#L242-L272) to reflect this change. `MockRestAdapter` should be edited so it uses the provided `ErrorHandler` for errors on asynchronous calls.

**Comment by caseykulm** [comment]
Note: RestAdapter is not a class in Retrofit anymore as of version 2.

**Comment by JakeWharton** [comment]
> RestAdapter is not a class

It was just renamed `Retrofit`.

That said, `ErrorHandler` is not a class anymore. The problematic `RetrofitError` class was removed, and synchronous execution can now properly throw `IOException` (and friends) and return non-200 responses in a type-safe way.

I don't think there's any action to take since the concept has been totally removed.

**Comment by tomkoptel** [comment]
Hello @JakeWharton !
You have already mentioned several times that `RetrofitError` is problematic and terribly designed class. I am curious about your concerns around class. What are the issues you see with it? 

I would be grateful if you shed some light on this mystical problems of `RetrofitError`.

**Comment by JakeWharton** [comment]
It conflates two different things: a successful HTTP response that
indicates an error and an unsuccessful HTTP call as the result of an
exception. It makes no sense for them to be represented as one type.
